import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "../../../lib/supabase/server.js";

export default async function AppDashboard({ params }) {
  const { id } = await params;
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/auth");
  const { data: app, error } = await supabase.from("apps").select("id,name,description,created_at,updated_at,current_version_id,visibility,publish_status").eq("id", id).eq("owner_id", user.id).single();
  if (error || !app) redirect("/my-apps");
  const [{ data: versions }, { data: backend }, { data: media }, { data: workflows }, { data: integrations }, { data: offers }] = await Promise.all([
    supabase.from("app_versions").select("id,version_no,specification,change_summary,created_at").eq("app_id", id).order("version_no", { ascending: false }),
    supabase.from("app_backend_models").select("status,schema_json,updated_at").eq("app_id", id).eq("owner_id", user.id).maybeSingle(),
    supabase.from("project_assets").select("id,asset_id,suggested_page,suggested_role,placement_reason").eq("app_id", id).eq("owner_id", user.id),
    supabase.from("app_workflows").select("id,enabled").eq("app_id", id).eq("owner_id", user.id),
    supabase.from("project_integrations").select("id,enabled").eq("app_id",id).eq("owner_id",user.id),
    supabase.from("monetization_offers").select("id,enabled").eq("app_id",id).eq("owner_id",user.id)
  ]);
  const current = versions?.find(v => v.id === app.current_version_id) || versions?.[0];
  const spec = current?.specification || {};
  const pages = Array.isArray(spec.pages) ? spec.pages : [];
  const features = Array.isArray(spec.features) ? spec.features : [];
  const dataGroups = Array.isArray(backend?.schema_json?.entities) ? backend.schema_json.entities.length : 0;
  const mediaCount = media?.length || 0;
  const workflowCount = workflows?.length || 0;
  const activeWorkflowCount = (workflows || []).filter(w => w.enabled).length;
  const integrationCount=(integrations||[]).filter(x=>x.enabled).length;
  const offerCount=(offers||[]).filter(x=>x.enabled).length;
  return <main className="page"><div className="wrap">
    <Link href="/my-apps" className="back">← Project Center</Link>
    <header><div><div className="eyebrow">CUSTOMER PROJECT FOLDER</div><h1>{app.name}</h1><p>{app.description || "Your App and Website workspace."}</p></div><span className="status">{app.publish_status === "published" ? "App + Website Published" : "Draft"}</span></header>
    <section className="stats"><div><small>Version</small><strong>{current?.version_no || 1}</strong></div><div><small>Website Sections</small><strong>{pages.length}</strong></div><div><small>App Features</small><strong>{features.length}</strong></div><div><small>Data Groups</small><strong>{dataGroups}</strong></div><div><small>Customer Media</small><strong>{mediaCount}</strong></div><div><small>Workflows</small><strong>{activeWorkflowCount}/{workflowCount}</strong></div></section>
    <section className="deliverables">
      <article><div className="eyebrow">📱 CUSTOMER APP</div><h2>Functional App</h2><p>Interactive customer App with customer media, data, navigation and install options.</p><div className="actions"><Link href={`/a/${id}?demo=1`} className="primary">Open App Demo</Link><Link href={`/editor/${id}`} className="secondary">Modify App</Link></div></article>
      <article><div className="eyebrow">🌐 CUSTOMER WEBSITE</div><h2>Responsive Website</h2><p>Business Website for mobile and desktop, generated from the same project and media.</p><div className="actions"><Link href={`/website/${id}`} className="primary">Preview Website</Link><Link href={`/website/${id}?domain=1`} className="secondary">Domain Settings</Link></div></article>
    </section>
    <section className="card"><div className="eyebrow">PROJECT ACTIONS</div><h2>Manage everything without seeing the infrastructure</h2><div className="actions"><Link href={`/editor/${id}`} className="primary">Visual Editor</Link><Link href={`/database/${id}`} className="secondary">Database Builder</Link><Link href={`/workflows/${id}`} className="secondary">Workflow Automation</Link><Link href={`/integrations/${id}`} className="secondary">Integration Center</Link><Link href={`/monetization/${id}`} className="secondary">Monetization</Link><Link href={`/analytics/${id}`} className="secondary">Analytics</Link><Link href={`/operations/${id}`} className="secondary">AI Operations</Link><Link href={`/app-dashboard/${id}/versions`} className="secondary">Version History / Rollback</Link><Link href={`/release/${id}`} className="secondary">Publishing Center</Link><a href={`/api/apps/${id}/export`} className="secondary">Export Project</a></div><div className="flow"><span>Demo</span><i>→</i><span>App + Website</span><i>→</i><span>Media</span><i>→</i><span>Data</span><i>→</i><span>Automation</span><i>→</i><span>Payments</span><i>→</i><span>Quality</span><i>→</i><span>Publish</span><i>→</i><span>Improve</span></div></section>
    <section className="card"><div className="eyebrow">CUSTOMER MEDIA</div><h2>{mediaCount ? `${mediaCount} private media assets connected` : "Add customer photos or video"}</h2><p>{mediaCount ? "SoolenAI has associated customer-owned media with relevant generated pages. Published projects can show only the media explicitly attached to that project." : "Upload photos, video or sketches during One-Click Create and SoolenAI will analyze, save and place them into the project."}</p>{mediaCount ? <div className="rows">{media.slice(0,8).map((item)=><div className="row" key={item.id}><strong>{item.suggested_page || "Main"}</strong><span>{item.suggested_role || "content"} · {item.placement_reason || "AI placement"}</span></div>)}</div> : null}</section>
    <section className="card"><div className="eyebrow">BUSINESS ENGINE</div><h2>{activeWorkflowCount} workflows · {integrationCount} project integrations · {offerCount} monetization offers</h2><p>CRM/order actions can run internally. Email, SMS, calendar and payment actions use managed server-side adapters when their platform delivery credentials are configured.</p><div className="actions"><Link href={`/workflows/${id}`} className="primary">Workflow Automation</Link><Link href={`/integrations/${id}`} className="secondary">Integration Center</Link><Link href={`/monetization/${id}`} className="secondary">Monetization</Link></div></section>
    <section className="card"><div className="eyebrow">DATA LAYER</div><h2>{backend ? "Project data model connected" : "Build the project data layer"}</h2><p>{backend ? `${dataGroups} business data groups are organized behind this project. The infrastructure provider stays hidden from the customer.` : "AI App Builder can turn the current project into a private-by-default data structure without requiring the customer to learn databases."}</p><div className="actions"><Link href={`/database/${id}`} className="primary">{backend ? "Open Database Builder" : "Build Data Structure"}</Link></div></section>
    <section className="card"><div className="eyebrow">CURRENT VERSION</div><h2>Shared project structure</h2>{pages.length ? pages.map((p,i)=><div className="row" key={i}><strong>{p?.name || `Page ${i+1}`}</strong><span>{p?.purpose || "App page and Website section"}</span></div>) : <p>No page structure available yet.</p>}</section>
    <section className="card"><div className="eyebrow">OWNERSHIP & PORTABILITY</div><h2>Customer project export</h2><p>Export the project specification, versions, data model, workflows, media placements, non-secret integration settings, monetization offers and project-learning settings. Provider secrets are deliberately excluded.</p><div className="actions"><a href={`/api/apps/${id}/export`} className="primary">Download Project Export</a></div></section>
    <footer><Link href={`/operations/${id}`}>AI Operations</Link><Link href={`/analytics/${id}`}>Analytics</Link><Link href={`/integrations/${id}`}>Integrations</Link><Link href={`/release/${id}`}>Publishing</Link><Link href="/my-apps">Project Center</Link></footer>
  </div><style>{`.page{min-height:100vh;padding:36px 18px 80px;background:linear-gradient(145deg,#03100d,#0a2119 58%,#06140f);color:#f5fff9}.wrap{max-width:1050px;margin:auto}.back,footer a{color:#d8bf62;text-decoration:none}.eyebrow{color:#d8bf62;letter-spacing:.18em;font-size:11px;font-weight:900}.page header{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;margin:22px 0 26px}.page h1{font-size:46px;margin:8px 0}.page p{color:#93aaa0;line-height:1.6}.status{color:#79d7ac;border:1px solid rgba(121,215,172,.2);border-radius:999px;padding:9px 13px;font-size:12px;font-weight:800}.stats{display:grid;grid-template-columns:repeat(6,1fr);gap:10px;margin-bottom:16px}.stats div,.card,.deliverables article{border:1px solid rgba(255,255,255,.08);background:rgba(3,16,13,.78);border-radius:20px;padding:20px}.stats small,.stats strong{display:block}.stats small{color:#7f9990;font-size:10px}.stats strong{font-size:24px;margin-top:5px}.deliverables{display:grid;grid-template-columns:1fr 1fr;gap:14px}.deliverables h2{font-size:28px;margin:9px 0}.card{margin-top:16px}.card h2{margin:8px 0 18px}.actions{display:flex;gap:10px;flex-wrap:wrap}.primary,.secondary{display:inline-flex;padding:12px 16px;border-radius:12px;font-weight:800;text-decoration:none}.primary{background:#d8bf62;color:#07130e}.secondary{border:1px solid rgba(216,191,98,.25);color:#d8bf62;background:transparent}.flow{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin-top:20px;color:#a9bbb4}.flow span{padding:8px 11px;border-radius:10px;background:#0e3024;color:#d8bf62}.row{display:grid;grid-template-columns:220px 1fr;gap:18px;padding:14px 0;border-top:1px solid rgba(255,255,255,.06)}.row span{color:#8ea69c}footer{display:flex;justify-content:space-between;gap:14px;margin-top:24px;flex-wrap:wrap}@media(max-width:900px){.stats{grid-template-columns:repeat(3,1fr)}}@media(max-width:700px){.stats,.deliverables{grid-template-columns:1fr 1fr}.page header{flex-direction:column}.row{grid-template-columns:1fr}footer{flex-direction:column;gap:12px}}`}</style></main>;
}
