import { createHash } from "node:crypto";
import { NextResponse } from "next/server";
import { createClient } from "../../../../../../lib/supabase/server.js";
import { createAdminClient } from "../../../../../../lib/supabase/admin.js";
import { getVideoComputePolicy } from "../../../../../../lib/video/compute-policy.js";
import { checkVideoRenderStatus, getVideoRendererConfig, normalizeVideoOutputPath, startVideoRender, VideoRenderGatewayError } from "../../../../../../lib/video/render-gateway.js";
import { persistRenderedVideo, DurableVideoOutputError } from "../../../../../../lib/video/output-persistence.js";
import { consumeAiCredits,refundAiCredits } from "../../../../../../lib/app-builder-finance.js";

const MAX_REQUEST_BYTES=256*1024;
const REQUEST_ID=/^[A-Za-z0-9._:-]{1,160}$/;
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const VIDEO_RENDER_CREDIT_COST=Math.max(1,Number(process.env.VIDEO_RENDER_CREDIT_COST||5));
function noStore(payload,status=200){return NextResponse.json(payload,{status,headers:{"Cache-Control":"private, no-store, max-age=0","Pragma":"no-cache","X-Content-Type-Options":"nosniff"}});}
function requestHash(value){return createHash("sha256").update(JSON.stringify(value)).digest("hex");}
function safeSourceUrl(value){const raw=String(value||"").trim();if(!raw||raw.length>2000)return null;let url;try{url=new URL(raw)}catch{return null}if(url.protocol!=="https:"||url.username||url.password)return null;const allow=new Set(String(process.env.VIDEO_SOURCE_HOST_ALLOWLIST||"").split(",").map(v=>v.trim().toLowerCase()).filter(Boolean));try{const supabase=new URL(String(process.env.NEXT_PUBLIC_SUPABASE_URL||""));allow.add(supabase.hostname.toLowerCase())}catch{}return allow.has(url.hostname.toLowerCase())?url.toString():null;}
function sanitizeClip(value,index){const rawSource=typeof value?.sourceUrl==="string"?value.sourceUrl.trim():"";const approved=rawSource?safeSourceUrl(rawSource):null;return{id:String(value?.id||`clip-${index+1}`).replace(/[^A-Za-z0-9._:-]/g,"-").slice(0,120),assetId:typeof value?.assetId==="string"&&UUID.test(value.assetId)?value.assetId:null,sourceUrl:approved,unsafeSource:Boolean(rawSource&&!approved),durationSeconds:Math.max(0.1,Math.min(20,Number(value?.durationSeconds)||1)),trimStartSeconds:Math.max(0,Number(value?.trimStartSeconds)||0),trimEndSeconds:value?.trimEndSeconds==null?null:Math.max(0,Number(value.trimEndSeconds)||0),transition:["cut","fade","crossfade","slide"].includes(value?.transition)?value.transition:"cut",style:["realistic","cartoon","mixed"].includes(value?.style)?value.style:"mixed",caption:String(value?.caption||"").replace(/[\u0000-\u001f\u007f]/g," ").slice(0,1000)};}
function publicVersion(row){const render=row?.edit_json?.render||{};return{id:row?.id,version_no:row?.version_no,duration_seconds:row?.duration_seconds,render_status:row?.render_status,output_path:normalizeVideoOutputPath(row?.output_path)||null,jobAccepted:Boolean(render.jobId||row?.output_asset_id),durableOutput:Boolean(row?.output_asset_id),created_at:row?.created_at,replayed:Boolean(row?.replayed)};}
async function ownedAssetSet(supabase,userId,ids){const unique=[...new Set(ids.filter(id=>typeof id==="string"&&UUID.test(id)))];if(!unique.length)return new Set();const{data,error}=await supabase.from("asset_library").select("id").eq("user_id",userId).in("id",unique);if(error)throw new Error("VIDEO_ASSET_LOOKUP_FAILED");return new Set((data||[]).map(row=>row.id));}
function assetId(value){return typeof value==="string"&&UUID.test(value)?value:null;}
async function updateProject(supabase,{id,userId,status,editJson}){const{error}=await supabase.from("video_projects").update({status,edit_json:editJson,updated_at:new Date().toISOString()}).eq("id",id).eq("owner_id",userId);if(error)throw error;}
async function finalizeClaim(admin,{userId,projectId,versionId,claimToken,editJson,renderStatus,outputPath=null,outputAssetId=null}){const{data,error}=await admin.rpc("server_finalize_video_render_v2",{p_user_id:userId,p_project_id:projectId,p_version_id:versionId,p_claim_token:claimToken,p_edit_json:editJson,p_render_status:renderStatus,p_output_path:outputPath,p_output_asset_id:outputAssetId});if(error)throw error;if(!data?.id)throw new Error("VIDEO_RENDER_FINALIZE_FAILED");return data;}
function replayPlan(version,policy,note){const render=version?.edit_json?.render||{};return{serverRender:true,rendererConfigured:Boolean(render.rendererConfigured),renderStarted:Boolean(render.jobId||version?.render_claim_token),jobAccepted:Boolean(render.jobId||version?.output_asset_id),submissionClaimed:Boolean(version?.render_claim_token),outputPath:normalizeVideoOutputPath(version?.output_path)||null,status:version?.render_status,autoConnect:Boolean(version?.edit_json?.autoConnected),clipCount:Array.isArray(version?.edit_json?.clips)?version.edit_json.clips.length:0,durationSeconds:Number(version?.duration_seconds||0),aspectRatio:version?.edit_json?.aspectRatio||"9:16",experience:policy.label,durableOutput:Boolean(version?.output_asset_id),note};}

export async function GET(request,{params}){
  let userId=null,refundRequestId=null,refundAmount=0;
  try{
    const {id}=await params;const versionId=String(new URL(request.url).searchParams.get("versionId")||"").trim();if(!UUID.test(versionId))return noStore({error:"A valid video version id is required."},400);
    const supabase=await createClient();const {data:{user},error:userError}=await supabase.auth.getUser();if(userError||!user)return noStore({error:"Authentication required."},401);userId=user.id;
    const {data:project}=await supabase.from("video_projects").select("id,status").eq("id",id).eq("owner_id",user.id).maybeSingle();if(!project)return noStore({error:"Video project not found."},404);
    const {data:version,error}=await supabase.from("video_versions").select("id,project_id,owner_id,version_no,duration_seconds,render_status,output_path,output_asset_id,source_request_id,render_claim_token,render_claimed_at,edit_json,created_at").eq("id",versionId).eq("project_id",id).eq("owner_id",user.id).maybeSingle();if(error)throw error;if(!version)return noStore({error:"Video version not found."},404);
    const render=version.edit_json?.render||{};refundRequestId=String(render.creditRequestId||"");refundAmount=Math.max(0,Number(render.creditAmount)||0);
    if(["completed","failed","draft"].includes(version.render_status)){if(version.render_status==="failed"&&refundRequestId&&refundAmount){try{await refundAiCredits(user.id,{requestId:refundRequestId,amount:refundAmount,description:"AI video render failed - automatic refund",metadata:{operation:"video_render",projectId:id,versionId:version.id}})}catch{}}return noStore({success:true,checked:false,version:publicVersion(version)});}
    if(!render.jobId)return noStore({success:true,checked:false,version:publicVersion(version),note:version.render_claim_token?"This renderer submission is already claimed. LANERIQ AI will not launch a duplicate job while provider acknowledgement is unavailable.":"This version has no accepted renderer job yet."});
    const renderer=getVideoRendererConfig();if(!renderer.configured||!renderer.statusEndpoint)return noStore({success:true,checked:false,version:publicVersion(version),note:"This render job has no connected status-check endpoint yet."});
    const checked=await checkVideoRenderStatus({jobId:render.jobId});if(!checked.checked)return noStore({success:true,checked:false,version:publicVersion(version)});
    const admin=createAdminClient();const providerStatus=checked.status||version.render_status;
    if(providerStatus==="completed"){
      if(!checked.outputPath)throw new DurableVideoOutputError("Renderer reported completion without a usable output.","VIDEO_DURABLE_OUTPUT_MISSING",502);
      const durable=await persistRenderedVideo({admin,userId:user.id,projectId:id,versionId:version.id,requestId:version.source_request_id,outputPath:checked.outputPath});
      const nextJson={...version.edit_json,render:{...render,status:"completed",providerStatus:"completed",outputPath:durable.stablePath,outputAssetId:durable.assetId,providerOutputCaptured:true,lastCheckedAt:new Date().toISOString(),completedAt:new Date().toISOString()}};
      let updated;if(version.render_claim_token)updated=await finalizeClaim(admin,{userId:user.id,projectId:id,versionId:version.id,claimToken:version.render_claim_token,editJson:nextJson,renderStatus:"completed",outputPath:durable.stablePath,outputAssetId:durable.assetId});else{const{data,error:updateError}=await supabase.from("video_versions").update({render_status:"completed",output_path:durable.stablePath,output_asset_id:durable.assetId,edit_json:nextJson}).eq("id",version.id).eq("project_id",id).eq("owner_id",user.id).select("id,version_no,duration_seconds,render_status,output_path,output_asset_id,edit_json,created_at").single();if(updateError)throw updateError;updated=data;}
      await updateProject(supabase,{id,userId:user.id,status:"completed",editJson:nextJson});return noStore({success:true,checked:true,version:publicVersion(updated),durable:true});
    }
    if(providerStatus==="failed"){
      if(refundRequestId&&refundAmount){try{await refundAiCredits(user.id,{requestId:refundRequestId,amount:refundAmount,description:"AI video render failed - automatic refund",metadata:{operation:"video_render",projectId:id,versionId:version.id}})}catch{}}
      const nextJson={...version.edit_json,render:{...render,status:"failed",providerStatus:"failed",lastCheckedAt:new Date().toISOString(),failedAt:new Date().toISOString()}};let updated;if(version.render_claim_token)updated=await finalizeClaim(admin,{userId:user.id,projectId:id,versionId:version.id,claimToken:version.render_claim_token,editJson:nextJson,renderStatus:"failed"});else{const{data,error:updateError}=await supabase.from("video_versions").update({render_status:"failed",edit_json:nextJson}).eq("id",version.id).eq("project_id",id).eq("owner_id",user.id).select("id,version_no,duration_seconds,render_status,output_path,output_asset_id,edit_json,created_at").single();if(updateError)throw updateError;updated=data;}await updateProject(supabase,{id,userId:user.id,status:"failed",editJson:nextJson});return noStore({success:true,checked:true,version:publicVersion(updated)});
    }
    const nextJson={...version.edit_json,render:{...render,status:"rendering",providerStatus,lastCheckedAt:new Date().toISOString()}};let updated;if(version.render_claim_token)updated=await finalizeClaim(admin,{userId:user.id,projectId:id,versionId:version.id,claimToken:version.render_claim_token,editJson:nextJson,renderStatus:"rendering"});else{const{data,error:updateError}=await supabase.from("video_versions").update({render_status:"rendering",edit_json:nextJson}).eq("id",version.id).eq("project_id",id).eq("owner_id",user.id).select("id,version_no,duration_seconds,render_status,output_path,output_asset_id,edit_json,created_at").single();if(updateError)throw updateError;updated=data;}await updateProject(supabase,{id,userId:user.id,status:"rendering",editJson:nextJson});return noStore({success:true,checked:true,version:publicVersion(updated)});
  }catch(error){console.error("VIDEO_RENDER_STATUS_ERROR",error?.code||error?.name||"unknown");if(error instanceof DurableVideoOutputError)return noStore({error:"The renderer finished, but LANERIQ AI could not secure the MP4 in your private Asset Library yet. Retry status safely; the renderer job will not be restarted.",code:error.code},error.status);if(error instanceof VideoRenderGatewayError)return noStore({error:"Unable to check the connected video render right now.",code:error.code},error.status);return noStore({error:"Unable to check this video render."},500);}
}

export async function POST(request,{params}){
  let userId=null,creditRequestId=null,charged=false,claimToken=null,versionForFailure=null,supabase=null,admin=null,projectId=null;
  try{
    const contentLength=Number(request.headers.get("content-length")||0);if(contentLength>MAX_REQUEST_BYTES)return noStore({error:"Video edit request is too large."},413);
    const {id}=await params;projectId=id;supabase=await createClient();const {data:{user},error:userError}=await supabase.auth.getUser();if(userError||!user)return noStore({error:"Authentication required."},401);userId=user.id;if(!user.confirmed_at&&!user.email_confirmed_at&&!user.phone_confirmed_at)return noStore({error:"Account verification is required."},403);
    const {data:project}=await supabase.from("video_projects").select("id,owner_id,name,device_class,max_duration_seconds,style").eq("id",id).eq("owner_id",user.id).maybeSingle();if(!project)return noStore({error:"Video project not found."},404);
    const body=await request.json().catch(()=>null);if(!body)return noStore({error:"Invalid video edit request."},400);if(Buffer.byteLength(JSON.stringify(body),"utf8")>MAX_REQUEST_BYTES)return noStore({error:"Video edit request is too large."},413);
    const requestId=String(body?.requestId||"").trim();if(!REQUEST_ID.test(requestId))return noStore({error:"A stable video compile request ID is required."},400);creditRequestId=requestId;
    const clips=Array.isArray(body?.clips)?body.clips.slice(0,40).map(sanitizeClip):[];if(!clips.length)return noStore({error:"At least one video clip is required."},400);if(clips.some(clip=>clip.unsafeSource))return noStore({error:"A clip source URL is not from an approved private media host."},400);
    for(const clip of clips){const end=clip.trimEndSeconds??clip.durationSeconds;if(clip.trimStartSeconds>=end)return noStore({error:`Clip ${clip.id} has an invalid trim range.`},400);}
    const total=clips.reduce((sum,clip)=>sum+Math.max(0.1,(clip.trimEndSeconds??clip.durationSeconds)-clip.trimStartSeconds),0);if(total>project.max_duration_seconds+0.01)return noStore({error:`This project is limited to ${project.max_duration_seconds} seconds on the current experience mode.`},400);
    const musicAssetId=assetId(body?.musicAssetId),voiceOverAssetId=assetId(body?.voiceOverAssetId),logoAssetId=assetId(body?.logoAssetId);const mediaIds=[...clips.map(clip=>clip.assetId),musicAssetId,voiceOverAssetId,logoAssetId].filter(Boolean);const owned=await ownedAssetSet(supabase,user.id,mediaIds);if(mediaIds.some(mediaId=>!owned.has(mediaId)))return noStore({error:"One or more video assets are unavailable or not owned by this account."},404);
    const policy=getVideoComputePolicy(project.device_class),renderer=getVideoRendererConfig(),rendererConfigured=renderer.configured;const aspectRatio=["9:16","16:9","1:1"].includes(body?.aspectRatio)?body.aspectRatio:"9:16";const quality=body?.quality==="best"?"best":"balanced";const autoConnect=Boolean(body?.autoConnect!==false);const cleanClips=clips.map(({unsafeSource,...clip},index)=>({...clip,order:index}));const hash=requestHash({clips:cleanClips,audio:{musicAssetId,voiceOverAssetId},branding:{logoAssetId},aspectRatio,quality,autoConnect});
    let editJson={version:2,autoConnected:autoConnect,aspectRatio,clips:cleanClips,audio:{musicAssetId,voiceOverAssetId,normalize:true},branding:{logoAssetId},render:{location:"server",quality,devicePreviewOnly:true,rendererConfigured,jobId:null,status:rendererConfigured?"queued":"draft",outputPath:null,outputAssetId:null,providerOutputCaptured:false,creditRequestId:rendererConfigured?creditRequestId:null,creditAmount:rendererConfigured?VIDEO_RENDER_CREDIT_COST:0}};
    const initialRenderStatus=rendererConfigured?"queued":"draft";admin=createAdminClient();const{data:version,error:versionError}=await admin.rpc("server_create_video_version_v2",{p_user_id:user.id,p_project_id:id,p_request_id:requestId,p_request_hash:hash,p_edit_json:editJson,p_duration_seconds:Number(total.toFixed(2)),p_render_status:initialRenderStatus});if(versionError){if(String(versionError.message||"").includes("video_version_request_conflict"))return noStore({error:"This video compile request ID was already used for a different edit.",code:"VIDEO_COMPILE_REQUEST_CONFLICT"},409);throw versionError;}if(!version?.id)throw new Error("VIDEO_VERSION_SAVE_FAILED");versionForFailure=version;
    const persistedRender=version?.edit_json?.render||{};
    if(version.replayed&&(version.render_status!=="queued"||version.render_claim_token||persistedRender.jobId||version.output_asset_id||!rendererConfigured))return noStore({success:true,replayed:true,version:publicVersion(version),renderPlan:replayPlan(version,policy,version.render_claim_token&&!persistedRender.jobId?"This compile request already owns the renderer submission claim. LANERIQ AI will not launch a duplicate job while acknowledgement is unknown.":"This compile request was already saved; the exact persisted version was returned without creating a duplicate.")});
    if(!rendererConfigured){if(version.render_status!=="draft"){editJson={...version.edit_json,render:{...persistedRender,rendererConfigured:false,status:"draft"}};const{error:updateError}=await supabase.from("video_versions").update({render_status:"draft",edit_json:editJson}).eq("id",version.id).eq("project_id",id).eq("owner_id",user.id);if(updateError)throw updateError;}await updateProject(supabase,{id,userId:user.id,status:"draft",editJson});return noStore({success:true,replayed:Boolean(version.replayed),version:publicVersion({...version,render_status:"draft",edit_json:editJson}),renderPlan:{serverRender:true,rendererConfigured:false,renderStarted:false,jobAccepted:false,submissionClaimed:false,outputPath:null,status:"draft",autoConnect:editJson.autoConnected,clipCount:cleanClips.length,durationSeconds:Number(total.toFixed(2)),aspectRatio:editJson.aspectRatio,experience:policy.label,durableOutput:false,note:"Edit version is saved safely as a draft. No final video renderer is connected, so LANERIQ AI does not claim that an MP4 is rendering or complete."}});}

    const charge=await consumeAiCredits(user.id,{amount:VIDEO_RENDER_CREDIT_COST,requestId:creditRequestId,description:"AI video rendering",metadata:{operation:"video_render",projectId:id,versionId:version.id}});charged=Boolean(charge?.charged);
    const{data:claim,error:claimError}=await admin.rpc("server_claim_video_render_v2",{p_user_id:user.id,p_project_id:id,p_version_id:version.id,p_request_id:requestId});if(claimError)throw claimError;if(!claim?.id)throw new Error("VIDEO_RENDER_CLAIM_FAILED");versionForFailure=claim;
    if(!claim.claimed)return noStore({success:true,replayed:true,version:publicVersion(claim),renderPlan:replayPlan(claim,policy,"This exact render submission is already claimed. LANERIQ AI will not start a second provider job for the same compile request.")});
    claimToken=claim.claimToken;editJson=claim.edit_json;
    try{
      const render=await startVideoRender({project,version:claim,editJson,requestId});
      if(render.status==="completed"&&render.outputPath){
        const durable=await persistRenderedVideo({admin,userId:user.id,projectId:id,versionId:claim.id,requestId,outputPath:render.outputPath});const completedJson={...editJson,render:{...editJson.render,jobId:render.jobId,status:"completed",providerStatus:"completed",outputPath:durable.stablePath,outputAssetId:durable.assetId,providerOutputCaptured:true,startedAt:new Date().toISOString(),completedAt:new Date().toISOString()}};const finalized=await finalizeClaim(admin,{userId:user.id,projectId:id,versionId:claim.id,claimToken,editJson:completedJson,renderStatus:"completed",outputPath:durable.stablePath,outputAssetId:durable.assetId});await updateProject(supabase,{id,userId:user.id,status:"completed",editJson:completedJson});return noStore({success:true,replayed:Boolean(version.replayed),version:publicVersion(finalized),renderPlan:{serverRender:true,rendererConfigured:true,renderStarted:true,jobAccepted:true,submissionClaimed:true,outputPath:durable.stablePath,status:"completed",autoConnect:completedJson.autoConnected,clipCount:cleanClips.length,durationSeconds:Number(total.toFixed(2)),aspectRatio:completedJson.aspectRatio,experience:policy.label,durableOutput:true,credits:{charged:charged?VIDEO_RENDER_CREDIT_COST:0,requestId:creditRequestId,balance:charge?.balance??null},note:"Final MP4 was captured into your private Asset Library before LANERIQ AI marked this version complete."}});
      }
      const renderingJson={...editJson,render:{...editJson.render,jobId:render.jobId,status:"rendering",providerStatus:render.status||"queued",outputPath:null,outputAssetId:null,providerOutputCaptured:false,startedAt:new Date().toISOString()}};const finalized=await finalizeClaim(admin,{userId:user.id,projectId:id,versionId:claim.id,claimToken,editJson:renderingJson,renderStatus:"rendering"});await updateProject(supabase,{id,userId:user.id,status:"rendering",editJson:renderingJson});return noStore({success:true,replayed:Boolean(version.replayed),version:publicVersion(finalized),renderPlan:{serverRender:true,rendererConfigured:true,renderStarted:true,jobAccepted:Boolean(render.jobId),submissionClaimed:true,outputPath:null,status:"rendering",autoConnect:renderingJson.autoConnected,clipCount:cleanClips.length,durationSeconds:Number(total.toFixed(2)),aspectRatio:renderingJson.aspectRatio,experience:policy.label,durableOutput:false,credits:{charged:charged?VIDEO_RENDER_CREDIT_COST:0,requestId:creditRequestId,balance:charge?.balance??null},note:"The authorized server renderer accepted one replay-safe job. LANERIQ AI will report completion only after the MP4 is captured into your private Asset Library."}});
    }catch(renderError){
      if(charged){try{await refundAiCredits(user.id,{requestId:creditRequestId,amount:VIDEO_RENDER_CREDIT_COST,description:"AI video render failed - automatic refund",metadata:{operation:"video_render",projectId:id,versionId:version.id}})}catch{}charged=false;}
      const failedJson={...editJson,render:{...editJson.render,status:"failed",failedAt:new Date().toISOString(),errorCode:renderError?.code||"VIDEO_RENDER_FAILED"}};if(claimToken){try{versionForFailure=await finalizeClaim(admin,{userId:user.id,projectId:id,versionId:version.id,claimToken,editJson:failedJson,renderStatus:"failed"});}catch{}}try{await updateProject(supabase,{id,userId:user.id,status:"failed",editJson:failedJson});}catch{}const status=renderError instanceof VideoRenderGatewayError||renderError instanceof DurableVideoOutputError?renderError.status:502;return noStore({success:false,error:renderError instanceof DurableVideoOutputError?"The renderer returned output, but LANERIQ AI could not secure the MP4 in your private Asset Library. The render credit charge was refunded and no duplicate renderer job will be started for this request.":"The video edit is saved, but the authorized renderer could not start or confirm this job.",code:renderError?.code||"VIDEO_RENDER_FAILED",version:publicVersion(versionForFailure||version)},status);
    }
  }catch(error){
    console.error("VIDEO_COMPILE_ERROR",error?.code||error?.name||"unknown");if(charged&&creditRequestId&&userId){try{await refundAiCredits(userId,{requestId:creditRequestId,amount:VIDEO_RENDER_CREDIT_COST,description:"AI video render failed - automatic refund",metadata:{operation:"video_render",projectId}})}catch{}}
    const message=String(error?.message||"");if(/insufficient credits/i.test(message))return noStore({error:"Insufficient credits.",requiredCredits:VIDEO_RENDER_CREDIT_COST},402);if(message.includes("video_version_request_conflict"))return noStore({error:"This video compile request ID was already used for a different edit.",code:"VIDEO_COMPILE_REQUEST_CONFLICT"},409);return noStore({error:"Unable to save this video version."},500);
  }
}
