export const APP_TEMPLATES = [
  ["real-estate-crm","Real Estate CRM","Leads, properties, follow-ups and appointments"],
  ["property-listing","Property Listing","Public property catalogue with enquiry forms"],
  ["restaurant-menu","Restaurant Menu","Digital menu, categories and enquiry/order capture"],
  ["restaurant-inventory","Restaurant Inventory","Ingredients, stock levels and low-stock alerts"],
  ["cafe-ordering","Cafe Ordering","Simple menu and customer order collection"],
  ["event-registration","Event Registration","Registration form, attendee list and export"],
  ["gym-members","Gym Members","Membership, attendance and renewal tracking"],
  ["salon-booking","Salon Booking","Services, staff schedules and appointments"],
  ["car-sales","Car Sales","Vehicle listings, leads and sales follow-ups"],
  ["car-rental","Car Rental","Vehicle availability, bookings and customer records"],
  ["invoice-manager","Invoice Manager","Customers, invoices, payment status and export"],
  ["expense-tracker","Expense Tracker","Expenses, categories and monthly reports"],
  ["small-business-crm","Small Business CRM","Contacts, leads, tasks and notes"],
  ["customer-feedback","Customer Feedback","Feedback forms, ratings and response tracking"],
  ["appointment-booking","Appointment Booking","Public booking form and appointment dashboard"],
  ["staff-schedule","Staff Schedule","Shifts, availability and simple attendance"],
  ["inventory-manager","Inventory Manager","Products, stock movements and low-stock alerts"],
  ["sales-dashboard","Sales Dashboard","Sales records, targets and summary reports"],
  ["order-manager","Order Manager","Orders, customers, statuses and exports"],
  ["supplier-manager","Supplier Manager","Supplier directory, orders and payment notes"],
  ["repair-shop","Repair Shop","Jobs, customers, parts and job status"],
  ["cleaning-service","Cleaning Service","Clients, bookings, staff and job tracking"],
  ["renovation-tracker","Renovation Tracker","Projects, milestones, tasks and expenses"],
  ["contractor-quote","Contractor Quote","Customer details, items and quotation totals"],
  ["tuition-class","Tuition Class","Students, classes, attendance and fees"],
  ["school-club","School Club","Members, activities and event registration"],
  ["daycare","Daycare","Children, guardians, attendance and notes"],
  ["pet-grooming","Pet Grooming","Pets, owners, services and appointments"],
  ["pet-clinic","Pet Clinic","Pet records, visits and appointment requests"],
  ["medical-appointment","Medical Appointment","Patient enquiry and appointment requests"],
  ["travel-booking","Travel Booking","Customers, itineraries and booking status"],
  ["tour-guide","Tour Guide","Tours, schedules, customers and enquiries"],
  ["hotel-booking","Hotel Booking","Rooms, availability and reservation requests"],
  ["home-services","Home Services","Services, customers and job bookings"],
  ["laundry-service","Laundry Service","Orders, customers, pickup and delivery status"],
  ["beauty-business","Beauty Business","Services, customers and appointments"],
  ["freelancer-portfolio","Freelancer Portfolio","Services, portfolio items and enquiry form"],
  ["agency-projects","Agency Projects","Clients, projects, tasks and deadlines"],
  ["content-calendar","Content Calendar","Content ideas, status, channels and schedule"],
  ["social-media-planner","Social Media Planner","Posts, platforms, dates and approval status"],
  ["newsletter-manager","Newsletter Manager","Contacts, campaigns and content planning"],
  ["community-members","Community Members","Members, announcements and events"],
  ["membership-club","Membership Club","Members, plans, renewals and benefits"],
  ["church-community","Community Group","Members, events, announcements and notes"],
  ["volunteer-manager","Volunteer Manager","Volunteers, shifts and event assignments"],
  ["nonprofit-donations","Donation Tracker","Donors, donations and campaign totals"],
  ["simple-survey","Simple Survey","Public survey, responses and CSV export"],
  ["lead-capture","Lead Capture","Public form, lead list and follow-up status"],
  ["product-feedback","Product Feedback","Ideas, votes, comments and status"],
  ["internal-weekly-report","Weekly Report","Team updates, blockers and weekly summaries"],
];

export const TEMPLATE_OBJECTS = APP_TEMPLATES.map(([id, name, description]) => ({ id, name, description }));
