"use client";

import { useEffect,useRef,useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "../../lib/supabase/client";
import { PRODUCT_BRAND } from "../../lib/product-brand.js";

export default function AccountNav(){
  const router=useRouter();const rootRef=useRef(null);const[supabase,setSupabase]=useState(null);const[user,setUser]=useState(null);const[open,setOpen]=useState(false);const[signingOut,setSigningOut]=useState(false);
  useEffect(()=>{const client=createClient();setSupabase(client);let mounted=true;client.auth.getUser().then(({data})=>{if(mounted)setUser(data.user||null)});const close=e=>{if(rootRef.current&&!rootRef.current.contains(e.target))setOpen(false)};document.addEventListener("pointerdown",close);return()=>{mounted=false;document.removeEventListener("pointerdown",close)}},[]);
  async function signOut(){if(!supabase||signingOut)return;setSigningOut(true);setOpen(false);try{await supabase.auth.signOut()}finally{window.location.assign("/auth")}}
  function go(path){setOpen(false);router.push(path)}
  if(!user)return null;
  const displayName=user.user_metadata?.full_name||user.user_metadata?.name||user.email?.split("@")[0]||"Account";
  return <div className="accountNav" ref={rootRef}><div className="accountBar"><button className="accountTrigger" onClick={()=>setOpen(v=>!v)} aria-expanded={open} aria-label="Open account menu"><span className="avatar">{String(displayName).slice(0,1).toUpperCase()}</span><b>{displayName}</b><i>⌄</i></button><button className="visibleLogout" onClick={signOut} disabled={signingOut} aria-label="Logout">{signingOut?"Signing out…":"Logout"}</button></div>{open&&<div className="accountMenu"><small>{PRODUCT_BRAND.name} · {PRODUCT_BRAND.capabilities}</small><button onClick={()=>go("/my-apps")}>📁 My Projects</button><button onClick={()=>go("/studio")}>✦ Studio</button><button onClick={()=>go("/community-chat")}>Community</button><button onClick={()=>go("/credits")}>Credits</button><button className="signout" onClick={signOut}>Sign out</button></div>}<style jsx>{`.accountNav{position:fixed;right:14px;top:70px;z-index:1000;font-family:Inter,system-ui,-apple-system,sans-serif}.accountBar{display:flex;align-items:center;gap:7px}.accountTrigger{display:flex;align-items:center;gap:8px;max-width:220px;border:1px solid rgba(216,191,98,.26);border-radius:999px;padding:6px 10px 6px 6px;background:rgba(3,16,13,.9);color:#fff;box-shadow:0 12px 34px #0006;backdrop-filter:blur(14px);cursor:pointer}.visibleLogout{min-height:42px;border:1px solid rgba(216,191,98,.34);border-radius:999px;padding:0 13px;background:rgba(3,16,13,.94);color:#e9c968;font-size:11px;font-weight:950;letter-spacing:.02em;box-shadow:0 12px 34px #0006;backdrop-filter:blur(14px);cursor:pointer}.visibleLogout:disabled{opacity:.55}.avatar{display:grid;place-items:center;width:30px;height:30px;border-radius:50%;background:linear-gradient(135deg,#f1d77c,#b88428);color:#07130e;font-weight:1000}.accountTrigger b{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:11px}.accountTrigger i{color:#d8bf62;font-style:normal}.accountMenu{position:absolute;right:0;top:49px;width:230px;padding:10px;border:1px solid rgba(216,191,98,.25);border-radius:17px;background:#03120ff5;box-shadow:0 22px 60px #0009;backdrop-filter:blur(20px)}.accountMenu small{display:block;padding:6px 8px 9px;color:#d8bf62;font-size:9px;letter-spacing:.1em;font-weight:900}.accountMenu button{display:block;width:100%;border:0;border-radius:10px;background:transparent;color:#dce7e2;text-align:left;padding:10px 9px;font-weight:800;cursor:pointer}.accountMenu button:hover{background:#ffffff0d}.accountMenu .signout{margin-top:5px;border-top:1px solid #ffffff10;color:#ffb9b2}@media(max-width:720px){.accountNav{right:10px;top:62px}.accountTrigger{max-width:118px}.accountTrigger b{display:none}.visibleLogout{min-height:40px;padding:0 11px;font-size:10px}.accountMenu{width:220px}}`}</style></div>;
}
