"use client";

import { useEffect } from "react";
import { usePathname } from "next/navigation";
import { BUILD_JOURNEY_STAGES } from "../../lib/ai/premium-experience-system.js";

const PREMIUM_PREFIXES=["/create","/app-dashboard/","/editor/","/pro/","/release/","/publish/","/image-studio","/video-studio","/media-studio","/asset-library","/templates","/studio","/generated/","/a/","/database/","/workflows/","/integrations/","/monetization/","/analytics/","/operations/"];
function pageType(path){if(path==="/"||path==="")return"home";if(path.startsWith("/create"))return"create";if(path.startsWith("/app-dashboard/"))return"dashboard";if(path.startsWith("/editor/"))return"editor";if(path.startsWith("/pro/"))return"pro";if(path.startsWith("/release/")||path.startsWith("/publish/"))return"publish";if(path.startsWith("/image-studio"))return"image";if(path.startsWith("/video-studio"))return"video";if(path.startsWith("/media-studio"))return"media";if(path.startsWith("/asset-library"))return"assets";if(path.startsWith("/templates"))return"templates";if(path.startsWith("/generated/")||path.startsWith("/a/"))return"preview";if(path.startsWith("/database/"))return"data";if(path.startsWith("/workflows/"))return"automation";if(path.startsWith("/integrations/"))return"connect";if(path.startsWith("/monetization/"))return"payments";if(path.startsWith("/analytics/"))return"analytics";return"studio";}
function stageFor(type){return({home:"idea",create:"understand",dashboard:"preview",editor:"building",pro:"building",publish:"publish",image:"planning",video:"building",media:"building",assets:"planning",templates:"idea",preview:"preview",data:"data",automation:"automation",connect:"automation",payments:"testing",analytics:"testing",studio:"planning"})[type]||"idea";}
export default function PremiumJourneyTheme(){const pathname=usePathname()||"/";useEffect(()=>{const premium=pathname==="/"||PREMIUM_PREFIXES.some(prefix=>pathname.startsWith(prefix));if(!premium)return;const type=pageType(pathname),stage=stageFor(type),stageIndex=Math.max(0,BUILD_JOURNEY_STAGES.findIndex(item=>item.id===stage)),body=document.body;body.dataset.premiumJourney="true";body.dataset.premiumPage=type;body.dataset.premiumStage=stage;body.dataset.premiumStageIndex=String(stageIndex);try{window.dispatchEvent(new CustomEvent("ai-build-stage-change",{detail:{stage,index:stageIndex}}))}catch{}return()=>{delete body.dataset.premiumJourney;delete body.dataset.premiumPage;delete body.dataset.premiumStage;delete body.dataset.premiumStageIndex}},[pathname]);return null;}
