"use client";

import { useEffect,useState } from "react";
import Link from "next/link";

export default function ProjectPortabilityPanel({appId}){
  const[state,setState]=useState(null);const[open,setOpen]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[message,setMessage]=useState("");
  const[acks,setAcks]=useState({share:false,ownership:false,continuing:false});
  async function load(){if(!appId)return;try{const r=await fetch(`/api/apps/${appId}/migration-agreement`,{cache:"no-store",credentials:"same-origin"});const d=await r.json();if(r.ok)setState(d)}catch{}}
  useEffect(()=>{void load()},[appId]);
  async function sign(){setBusy(true);setError("");setMessage("");try{const r=await fetch(`/api/apps/${appId}/migration-agreement`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({termsVersion:"LANERIQ-PORTABILITY-10PCT-v1",acknowledge10Percent:acks.share,acknowledgeCustomerOwnership:acks.ownership,acknowledgeContinuingShare:acks.continuing})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to sign migration agreement.");setMessage("Agreement recorded. This project may now be migrated outside LANERIQ AI without platform lock-in.");await load()}catch(e){setError(e.message||"Unable to sign migration agreement.")}finally{setBusy(false)}}
  if(!appId)return null;
  const signed=state?.migrationAllowed===true;
  return <section className="portabilityCard" data-liui-portability="true">
    <div className="portabilityTop"><div><small>POST-PUBLISH OWNERSHIP & PORTABILITY</small><h2>Stay with LANERIQ AI or move your project out.</h2><p>Your project remains yours. After publishing, you can keep editing, versioning, Self-Heal testing and republishing here, or migrate it to your own hosting / another development team.</p></div><span className="ownerBadge">CUSTOMER OWNED</span></div>
    <div className="portabilityChoices">
      <article><div className="choiceIcon">✦</div><b>Keep building here</b><p>Continue using LANERIQ AI Editor, Database, Automation, Versions, Testing, Analytics and Publish Center.</p><Link href={`/editor/${appId}`}>Continue in LANERIQ AI →</Link></article>
      <article className="migrate"><div className="choiceIcon">↗</div><b>Migrate outside LANERIQ AI</b><p>No technical platform lock-in and no migration fee. Before full external migration, sign the project-specific 10% Revenue Share Agreement.</p><button onClick={()=>setOpen(v=>!v)}>{signed?"Agreement signed ✓":"Review 10% Agreement"}</button></article>
    </div>
    {open&&<div className="agreementPanel">
      <div className="agreementHead"><div><small>MIGRATION AGREEMENT · PROJECT SPECIFIC</small><h3>10% Revenue Share after external migration</h3></div><button onClick={()=>setOpen(false)} aria-label="Close">×</button></div>
      <p>This agreement does not transfer project ownership to LANERIQ AI. It does not charge a migration fee. It records a continuing 10% LANERIQ AI share of this project’s software revenue after migration. Unrelated underlying customer business transactions are excluded.</p>
      {signed?<div className="signedState"><b>Agreement recorded ✓</b><span>Signed {state?.agreement?.signedAt?new Date(state.agreement.signedAt).toLocaleString():""}</span><small>Revenue share: {state?.agreement?.revenueSharePercent||10}% · Platform lock-in: No</small></div>:<div className="ackList">
        <label><input type="checkbox" checked={acks.ownership} onChange={e=>setAcks(a=>({...a,ownership:e.target.checked}))}/> I understand I keep ownership of this project and may migrate it outside LANERIQ AI.</label>
        <label><input type="checkbox" checked={acks.share} onChange={e=>setAcks(a=>({...a,share:e.target.checked}))}/> I agree that LANERIQ AI receives 10% of this project’s software revenue after migration.</label>
        <label><input type="checkbox" checked={acks.continuing} onChange={e=>setAcks(a=>({...a,continuing:e.target.checked}))}/> I understand the 10% obligation continues after the project leaves LANERIQ AI.</label>
        <button className="signButton" disabled={busy||!acks.ownership||!acks.share||!acks.continuing} onClick={sign}>{busy?"Recording…":"Sign & Unlock External Migration"}</button>
      </div>}
      <small className="legalNote">Production legal wording must be reviewed by qualified counsel for the jurisdictions where LANERIQ AI operates before contractual enforcement.</small>
      {message&&<p className="ok">{message}</p>}{error&&<p className="err" role="alert">{error}</p>}
    </div>}
    <style jsx>{`.portabilityCard{margin-top:22px;border:1px solid rgba(242,200,103,.30);border-radius:24px;padding:22px;background:linear-gradient(145deg,rgba(7,25,48,.90),rgba(23,18,57,.82));box-shadow:0 24px 70px #0007;backdrop-filter:blur(22px);color:#f7fbff}.portabilityTop{display:flex;justify-content:space-between;gap:18px;align-items:flex-start}.portabilityTop small,.agreementHead small{color:#f1ca67;font-size:10px;font-weight:950;letter-spacing:.14em}.portabilityTop h2{font-size:clamp(26px,4vw,38px);margin:8px 0 9px}.portabilityTop p,.agreementPanel>p{color:#aebfcb;line-height:1.6;max-width:780px}.ownerBadge{white-space:nowrap;border:1px solid #72dfad55;border-radius:999px;padding:8px 10px;color:#83e6b9;font-size:10px;font-weight:950}.portabilityChoices{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:17px}.portabilityChoices article{border:1px solid #ffffff18;border-radius:18px;padding:18px;background:rgba(255,255,255,.055)}.portabilityChoices .migrate{background:linear-gradient(145deg,rgba(74,50,130,.18),rgba(255,255,255,.04))}.choiceIcon{font-size:26px;color:#f0ce72}.portabilityChoices b{display:block;margin:8px 0;font-size:17px}.portabilityChoices p{color:#a9bbc6;font-size:12px;line-height:1.55;min-height:58px}.portabilityChoices a,.portabilityChoices button{display:inline-flex;align-items:center;min-height:44px;border-radius:12px;padding:10px 13px;text-decoration:none;font-weight:900;border:1px solid #f0ce7250;background:rgba(241,202,103,.10);color:#f2d57c}.agreementPanel{margin-top:12px;border:1px solid #ffffff18;border-radius:18px;padding:17px;background:rgba(2,13,28,.76)}.agreementHead{display:flex;justify-content:space-between;gap:12px}.agreementHead h3{margin:5px 0;font-size:22px}.agreementHead button{border:0;background:transparent;color:#fff;font-size:25px}.ackList{display:grid;gap:10px}.ackList label{display:flex;gap:9px;align-items:flex-start;color:#d7e0e6;font-size:12px;line-height:1.48}.signButton{min-height:46px;border:0;border-radius:13px;background:linear-gradient(135deg,#f5d779,#c9902e);color:#101925;font-weight:950;padding:12px 15px}.signButton:disabled{opacity:.45}.signedState{display:grid;gap:5px;padding:13px;border-radius:14px;background:rgba(77,203,146,.10);border:1px solid rgba(77,203,146,.25)}.signedState b{color:#7ee2af}.signedState span,.signedState small{color:#b9c9c2}.legalNote{display:block;margin-top:13px;color:#7f909a;line-height:1.45}.ok{color:#7fe5b1}.err{color:#ff9f98}@media(max-width:700px){.portabilityTop{display:grid}.ownerBadge{justify-self:start}.portabilityChoices{grid-template-columns:1fr}.portabilityChoices p{min-height:0}}`}</style>
  </section>;
}
