import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "../../../lib/supabase/server.js";

export default async function AnalyticsPage({params}){
  const {id}=await params;const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect(`/auth?next=${encodeURIComponent(`/analytics/${id}`)}`);
  const {data:app}=await supabase.from("apps").select("id,name,owner_id").eq("id",id).eq("owner_id",user.id).single();if(!app)redirect("/my-apps");
  const since=new Date(Date.now()-29*24*60*60*1000).toISOString().slice(0,10);
  const {data:events}=await supabase.from("analytics_daily_aggregates").select("event_day,event_name,channel,event_count").eq("app_id",id).gte("event_day",since).order("event_day",{ascending:false}).limit(1000);
  const rows=events||[];
  const sum=(predicate)=>rows.reduce((total,row)=>total+(predicate(row)?Number(row.event_count||0):0),0);
  const appViews=sum(row=>row.event_name==="app_view");const websiteViews=sum(row=>row.event_name==="website_view");const gameViews=sum(row=>row.event_name==="game_view");const totalEvents=sum(()=>true);
  const days={};for(const event of rows){const day=event.event_day;days[day]=(days[day]||0)+Number(event.event_count||0)}const daily=Object.entries(days).sort((a,b)=>a[0].localeCompare(b[0])).slice(-14);const max=Math.max(1,...daily.map(x=>x[1]));
  return <main className="page"><div className="wrap"><Link href={`/app-dashboard/${id}`} className="back">← Project Folder</Link><div className="eyebrow">LANERIQ AI · ANALYTICS</div><h1>{app.name}</h1><p>Anonymous aggregate product signals only. LANERIQ AI keeps useful totals without building a customer behavior profile.</p><section className="stats"><article><small>APP VIEWS · 30D</small><strong>{appViews}</strong></article><article><small>WEBSITE VIEWS · 30D</small><strong>{websiteViews}</strong></article><article><small>GAME VIEWS · 30D</small><strong>{gameViews}</strong></article><article><small>EVENTS · 30D</small><strong>{totalEvents}</strong></article></section><section className="card"><div className="eyebrow">LAST 14 ACTIVE DAYS</div><h2>Aggregate activity</h2>{daily.length?<div className="bars">{daily.map(([day,count])=><div key={day}><span>{day.slice(5)}</span><i><b style={{height:`${Math.max(8,Math.round(count/max*100))}%`}}/></i><strong>{count}</strong></div>)}</div>:<div className="empty">No aggregate usage data yet. Anonymous counts will appear after the App, Website or Game is opened.</div>}</section><section className="card"><div className="eyebrow">PRIVACY</div><h2>Anonymous Aggregate Analytics Only</h2><p>Counts are grouped only by project, UTC day, event type and channel. No session IDs, user IDs, IP addresses, device IDs, referrers, page paths, advertising profiles or raw customer content are stored in product analytics.</p></section></div><style>{`.page{min-height:100vh;padding:36px 18px 80px;background:linear-gradient(145deg,#03100d,#0a2119 58%,#06140f);color:#f5fff9}.wrap{max-width:1050px;margin:auto}.back{color:#d8bf62;text-decoration:none}.eyebrow{margin-top:24px;color:#d8bf62;letter-spacing:.18em;font-size:11px;font-weight:900}h1{font-size:48px;margin:8px 0}.wrap>p,.card p{color:#96aaa1;line-height:1.65;max-width:820px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:26px 0}.stats article,.card{border:1px solid rgba(255,255,255,.08);background:rgba(3,16,13,.78);border-radius:20px;padding:20px}.stats small,.stats strong{display:block}.stats small{color:#8ea49a;font-size:10px}.stats strong{font-size:34px;margin-top:7px;color:#d8bf62}.card{margin-top:14px}.card h2{margin:8px 0 18px}.bars{height:240px;display:flex;gap:8px;align-items:end;overflow:auto}.bars>div{height:100%;min-width:44px;display:grid;grid-template-rows:18px 1fr 20px;gap:7px;text-align:center}.bars span,.bars strong{font-size:10px;color:#8da299}.bars i{height:100%;display:flex;align-items:end;justify-content:center;background:#ffffff08;border-radius:8px;padding:3px}.bars i b{width:100%;display:block;border-radius:6px;background:#d8bf62}.empty{padding:40px;text-align:center;color:#8da299;border:1px dashed #d8bf6233;border-radius:15px}@media(max-width:700px){.stats{grid-template-columns:1fr 1fr}h1{font-size:38px}}`}</style></main>;
}
