"use client";
import { useRef, useState } from "react";

export default function VideoStudio(){
  const [prompt,setPrompt]=useState(""); const [story,setStory]=useState(null); const [status,setStatus]=useState(""); const [video,setVideo]=useState(""); const canvasRef=useRef(null);
  async function createStoryboard(){ if(!prompt.trim())return; setStatus("Soolen AI is planning your video…"); setVideo(""); try{const r=await fetch("/api/video/storyboard",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt:prompt.trim(),duration:12})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Video planning failed");setStory(d.storyboard);setStatus("Storyboard ready. Render your video below.");}catch(e){setStatus(e.message)}}
  async function render(){ if(!story?.scenes?.length)return; const canvas=canvasRef.current,ctx=canvas.getContext("2d"),stream=canvas.captureStream(30),rec=new MediaRecorder(stream,{mimeType:"video/webm"}),chunks=[]; rec.ondataavailable=e=>e.data.size&&chunks.push(e.data); rec.onstop=()=>{setVideo(URL.createObjectURL(new Blob(chunks,{type:"video/webm"})));setStatus("Video ready.")};rec.start();const scenes=story.scenes;for(const s of scenes){const ms=Math.max(1200,Number(s.duration)*1000||3000),start=performance.now();while(performance.now()-start<ms){const t=(performance.now()-start)/ms;ctx.fillStyle="#09251e";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle="#d8bf62";ctx.font="700 42px Arial";ctx.fillText(String(story.title||"Soolen AI").slice(0,28),60,90);ctx.fillStyle="#f7fff9";ctx.font="700 58px Arial";wrap(ctx,String(s.headline||""),60,360,900,68);ctx.fillStyle="#b8ccc4";ctx.font="28px Arial";wrap(ctx,String(s.caption||s.visual||""),60,540,900,42);ctx.globalAlpha=.18;ctx.beginPath();ctx.arc(850,220,170+80*Math.sin(t*Math.PI),0,Math.PI*2);ctx.fillStyle="#d8bf62";ctx.fill();ctx.globalAlpha=1;await new Promise(r=>requestAnimationFrame(r));}}rec.stop();}
  return <main className="page"><div className="card"><div className="eyebrow">SOOLEN AI • VIDEO ENGINE</div><h1>Create a video from an idea.</h1><p>Soolen AI creates the storyboard, then your browser renders an original motion video. No OpenAI video API is required.</p><textarea rows="5" value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Example: Create a 12-second launch video for a premium property app in Kuala Lumpur."/><div className="actions"><button onClick={createStoryboard} disabled={!prompt.trim()}>✨ Create storyboard</button>{story&&<button onClick={render}>🎬 Render video</button>}</div>{story&&<section><h2>{story.title}</h2>{(story.scenes||[]).map((s,i)=><div className="scene" key={i}><b>Scene {i+1}</b><strong>{s.headline}</strong><span>{s.caption}</span><small>{s.visual}</small></div>)}</section>}<canvas ref={canvasRef} width="1080" height="1080" className="canvas"/>{video&&<div className="result"><video controls src={video}/><a href={video} download="soolen-ai-video.webm">Save video</a></div>}<div className="status">{status}</div></div><style jsx>{`.page{min-height:100vh;padding:42px 18px;background:linear-gradient(145deg,#041713,#0d4437,#06120f);color:#f7fff9}.card{max-width:820px;margin:auto;padding:30px;border:1px solid #d8bf6233;border-radius:28px;background:#061b16dd}.eyebrow{color:#d8bf62;font-size:11px;font-weight:900;letter-spacing:.2em}h1{font-size:42px;margin:10px 0}p{color:#a5bdb4;line-height:1.6}textarea{width:100%;box-sizing:border-box;padding:15px;border-radius:15px;background:#02100d;color:#fff;border:1px solid #ffffff18;font:inherit}.actions{display:flex;gap:10px;flex-wrap:wrap}.actions button,.result a{margin-top:12px;padding:13px 18px;border:0;border-radius:13px;background:#d8bf62;color:#07130e;font-weight:900;text-decoration:none}.scene{display:grid;gap:5px;margin-top:10px;padding:14px;border-radius:14px;background:#ffffff08}.scene strong{font-size:19px}.scene span,.scene small{color:#a5bdb4}.canvas{display:none}.result video{width:100%;margin-top:20px;border-radius:18px}.status{margin-top:12px;color:#9db2aa;font-size:13px}`}</style></main>}
function wrap(ctx,text,x,y,maxWidth,lineHeight){let words=text.split(/\s+/),line="";for(const word of words){const test=line?line+" "+word:word;if(ctx.measureText(test).width>maxWidth&&line){ctx.fillText(line,x,y);line=word;y+=lineHeight}else line=test}if(line)ctx.fillText(line,x,y)}
