"use client";

import Link from "next/link";
import { useEffect,useState } from "react";

const TRIGGER_LABELS={form_submitted:"When a form is submitted",appointment_created:"When an appointment is created",order_created:"When an order is created"};
const ACTION_LABELS={save_crm:"Save customer",save_order:"Save order",notify_team:"Notify team",send_email:"Send email",send_sms:"Send SMS",send_whatsapp:"Send WhatsApp",calendar:"Add calendar event"};
const PRESETS=[
  {name:"Lead follow-up",triggerType:"form_submitted",actions:[{type:"save_crm",label:"Save customer to CRM"},{type:"send_whatsapp",label:"Send WhatsApp acknowledgement"},{type:"send_email",label:"Send confirmation email"},{type:"notify_team",label:"Notify team"}]},
  {name:"Appointment confirmation",triggerType:"appointment_created",actions:[{type:"send_email",label:"Send appointment confirmation"},{type:"send_sms",label:"Send SMS reminder"},{type:"calendar",label:"Add to calendar"}]},
  {name:"Order update",triggerType:"order_created",actions:[{type:"save_order",label:"Save order"},{type:"send_email",label:"Send receipt / confirmation"},{type:"notify_team",label:"Notify operations"}]}
];

export default function WorkflowPage({params}){
  const[appId,setAppId]=useState(null);const[app,setApp]=useState(null);const[workflows,setWorkflows]=useState([]);const[busy,setBusy]=useState(false);const[running,setRunning]=useState("");const[message,setMessage]=useState("");const[error,setError]=useState("");const[lastRun,setLastRun]=useState(null);
  useEffect(()=>{Promise.resolve(params).then(v=>setAppId(v.id))},[params]);
  useEffect(()=>{if(appId)load()},[appId]);
  async function load(){setError("");try{const r=await fetch(`/api/apps/${appId}/workflows`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d?.error||"Unable to load automations.");setApp(d.app);setWorkflows(d.workflows||[])}catch(e){setError(e.message)}}
  async function addPreset(preset){setBusy(true);setError("");setMessage("");try{const r=await fetch(`/api/apps/${appId}/workflows`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(preset)});const d=await r.json();if(!r.ok)throw new Error(d?.error||"Unable to create automation.");setMessage(`${preset.name} added.`);await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function runWorkflow(workflow){setRunning(workflow.id);setError("");setMessage("");setLastRun(null);try{const sample={name:"Test Customer",email:"customer@example.com",phone:"+60000000000",whatsapp:"+60000000000",source:"SoolenAI Safe Test"};const r=await fetch(`/api/apps/${appId}/workflows/${workflow.id}/run`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({payload:sample,dryRun:true,idempotencyKey:`safe-test-${workflow.id}-${Date.now()}`})});const d=await r.json();if(!r.ok)throw new Error(d?.error||"Unable to test automation.");setLastRun(d);setMessage("Safe Test passed. No customer data was saved and no messages were sent.")}catch(e){setError(e.message)}finally{setRunning("")}}
  return <main className="page"><div className="wrap"><Link className="back" href={appId?`/app-dashboard/${appId}`:"/my-apps"}>← Project Folder</Link><div className="eyebrow">SOOLENAI · AUTOMATIONS</div><h1>{app?.name||"Project"}</h1><p className="intro">Choose what should happen automatically. You do not need to understand workflows, triggers or code. SoolenAI keeps external actions safely blocked until the required connection is ready.</p>
  <section className="safe"><div><small>SAFE TEST MODE</small><h2>Test before anything is sent.</h2><p>Safe Test checks every step without saving customer data, sending email/SMS/WhatsApp, creating calendar events or notifying your team.</p></div><span>NO SIDE EFFECTS</span></section>
  <section className="presets"><h2>Choose an automation</h2><div className="grid">{PRESETS.map(p=><article key={p.name}><h3>{p.name}</h3><p><b>{TRIGGER_LABELS[p.triggerType]||"When needed"}</b></p>{p.actions.map((a,i)=><div key={i}>→ {a.label}</div>)}<button disabled={busy} onClick={()=>addPreset(p)}>Add this automation</button></article>)}</div></section>
  <section className="saved"><h2>Your automations</h2>{workflows.length?workflows.map(w=><article key={w.id}><div><b>{w.name}</b><small>{w.enabled?"On":"Paused"} · {TRIGGER_LABELS[w.trigger_type]||"Runs when its event happens"}</small></div><div className="right"><span>{Array.isArray(w.actions)?w.actions.length:0} steps</span><button disabled={running===w.id||!w.enabled} onClick={()=>runWorkflow(w)}>{running===w.id?"Checking safely…":"Safe Test"}</button></div></article>):<p>No automations yet.</p>}</section>
  {lastRun&&<section className="run"><h2>Latest Safe Test</h2><b>{lastRun.safeTest?"No real actions were sent":"Test result"}</b>{(lastRun.results||[]).map((result,index)=><div key={index}><span>{ACTION_LABELS[result.type]||result.type}</span><strong className={result.status}>{result.status==="simulated"?"Checked":result.status.replaceAll("_"," ")}</strong><small>{result.message||result.record?.record_type||"Completed"}</small></div>)}</section>}
  {message&&<div className="msg">{message}</div>}{error&&<div className="err">{error}</div>}
  </div><style jsx>{`.page{min-height:100vh;padding:36px 18px 80px;background:linear-gradient(145deg,#03100d,#0a2119 58%,#06140f);color:#f5fff9}.wrap{max-width:1080px;margin:auto}.back{color:#d8bf62;text-decoration:none}.eyebrow{margin-top:28px;color:#d8bf62;letter-spacing:.18em;font-size:11px;font-weight:900}h1{font-size:48px;margin:8px 0}.intro{max-width:800px;color:#9cb0a8;line-height:1.65}.safe{display:flex;justify-content:space-between;gap:20px;align-items:center;margin-top:22px;padding:20px;border:1px solid rgba(121,215,172,.25);border-radius:20px;background:rgba(24,78,57,.18)}.safe small{color:#79d7ac;font-weight:900;letter-spacing:.14em}.safe h2{margin:5px 0}.safe p{margin:0;color:#9cb0a8;line-height:1.5}.safe>span{white-space:nowrap;border:1px solid rgba(121,215,172,.35);border-radius:999px;padding:8px 11px;color:#8ce0b8;font-size:10px;font-weight:900}.presets,.saved,.run{margin-top:28px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.grid article,.saved article,.run{border:1px solid rgba(216,191,98,.2);border-radius:20px;background:rgba(3,16,13,.78);padding:20px}.grid h3{margin-top:0}.grid p,.grid article>div,.saved small,.run small{color:#97aaa2}.grid article>div{margin:7px 0;font-size:13px}.grid button,.saved button{border:0;border-radius:12px;padding:10px 13px;background:#d8bf62;color:#07130e;font-weight:900}.grid button{margin-top:15px}.saved{display:grid;gap:10px}.saved>h2{margin-bottom:4px}.saved article{display:flex;justify-content:space-between;gap:15px;align-items:center}.saved b,.saved small{display:block}.saved small{margin-top:4px}.saved span{color:#d8bf62;font-size:12px}.right{display:flex;align-items:center;gap:10px}.saved button:disabled,.grid button:disabled{opacity:.5}.run>div{display:grid;grid-template-columns:130px 160px 1fr;gap:12px;padding:11px 0;border-top:1px solid #ffffff12;align-items:center}.run strong{font-size:12px;text-transform:capitalize}.run .completed,.run .simulated{color:#83ddb5}.run .integration_required{color:#e9c56b}.run .failed{color:#ff9b90}.msg,.err{margin-top:14px;padding:12px;border-radius:12px}.msg{background:#1c6b4d33;color:#9fe2c2}.err{background:#7c2d2d44;color:#ffb5ad}@media(max-width:760px){.grid{grid-template-columns:1fr}.saved article,.safe{align-items:flex-start;flex-direction:column}.right{width:100%;justify-content:space-between}.run>div{grid-template-columns:1fr}.run{padding:16px}h1{font-size:38px}}`}</style></main>
}
