"use client";
import { useEffect,useState } from "react";

function phoneHref(value){const clean=String(value||"").replace(/[^0-9+]/g,"");return clean?`tel:${clean}`:"";}
export default function WebsiteEnquiryInbox({appId}){
  const[items,setItems]=useState([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
  async function load(){setLoading(true);setError("");try{const response=await fetch(`/api/apps/${appId}/website-enquiries?limit=20`,{cache:"no-store"});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error||"Unable to load enquiries.");setItems(Array.isArray(data?.enquiries)?data.enquiries:[])}catch(err){setError(String(err?.message||"Unable to load enquiries."))}finally{setLoading(false)}}
  useEffect(()=>{load()},[appId]);
  async function mark(item,status){try{const response=await fetch(`/api/apps/${appId}/website-enquiries`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({enquiryId:item.id,status})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error||"Unable to update enquiry.");setItems(current=>current.map(row=>row.id===item.id?{...row,status:data.enquiry.status}:row))}catch(err){setError(String(err?.message||"Unable to update enquiry."))}}
  return <section className="inbox"><div className="head"><div><small>OWNER ONLY</small><h2>Website Enquiries</h2><p>Customer messages submitted through the published website appear here.</p></div><button onClick={load} disabled={loading}>{loading?"Refreshing…":"Refresh"}</button></div>
    {error&&<div className="error" role="alert">{error}</div>}{!loading&&!items.length&&<div className="empty">No customer enquiries yet.</div>}
    <div className="list">{items.map(item=><article key={item.id}><div className="meta"><b>{item.name}</b><span>{new Date(item.createdAt).toLocaleString()}</span><em>{item.status}</em></div><p>{item.message}</p><div className="actions">{item.email&&<a href={`mailto:${item.email}`}>{item.email}</a>}{item.phone&&<a href={phoneHref(item.phone)}>{item.phone}</a>}<button onClick={()=>mark(item,item.status==="contacted"?"archived":"contacted")}>{item.status==="contacted"?"Archive":"Mark contacted"}</button></div></article>)}</div>
    <style jsx>{`.inbox{max-width:1180px;margin:0 auto 70px;padding:24px 20px 10px;color:var(--foreground)}.head{display:flex;align-items:flex-start;justify-content:space-between;gap:18px}.head small{color:var(--primary);font-weight:950;letter-spacing:.16em}.head h2{font-size:34px;margin:7px 0}.head p{opacity:.7}.head button,.actions button{border:1px solid color-mix(in srgb,var(--primary) 25%,transparent);background:var(--surface);color:var(--primary);border-radius:12px;min-height:44px;padding:10px 13px;font-weight:900}.list{display:grid;gap:12px;margin-top:18px}.list article,.empty,.error{padding:18px;border-radius:18px;background:var(--surface);border:1px solid color-mix(in srgb,var(--primary) 12%,transparent);box-shadow:0 10px 30px #0001}.meta{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.meta b{font-size:17px}.meta span{font-size:11px;opacity:.6}.meta em{font-style:normal;text-transform:uppercase;font-size:9px;letter-spacing:.1em;padding:5px 8px;border-radius:999px;background:color-mix(in srgb,var(--accent) 18%,var(--surface));color:var(--primary);font-weight:950}.list p{line-height:1.55;white-space:pre-wrap}.actions{display:flex;align-items:center;gap:9px;flex-wrap:wrap}.actions a{color:var(--primary);font-weight:800;text-decoration:none}.actions button{margin-left:auto}.error{color:#a72d2d}.empty{opacity:.65}@media(max-width:640px){.head{display:block}.head>button{width:100%;margin-top:10px}.actions button{width:100%;margin-left:0}}`}</style>
  </section>;
}
