"use client";

import {useMemo,useState} from "react";
import Link from "next/link";
import {
  createReplayRecorder,recordReplayEvent,recordReplaySnapshot,finishReplay,seekReplay,createSpectatorPolicy,
  createGuildState,guildInvite,guildJoin,createLeaderboard,submitLeaderboardScore,leaderboardRows,
  createAchievementState,progressAchievement,createCloudSaveEnvelope,mergeCloudSave,validateUgcLevel
} from "../../lib/game/game-platform-systems-v1.js";

const TABS=["Replay","Spectator","Guild","Leaderboard","Cloud Save","UGC Editor"];

export default function GamePlatformLab(){
  const[tab,setTab]=useState("Replay");
  return <main className="shell"><div className="bg"/><header><Link href="/game-builder">← GAME BUILDER</Link><span>SOOLENAI · GAME PLATFORM LAB</span></header>
    <section className="hero"><small>PRO GAME PLATFORM SYSTEMS</small><h1>Build the systems<br/><em>around the game.</em></h1><p>Replay, spectator, guild, ranked board, achievements, cloud-save conflict handling and UGC editing are tested here as provider-neutral local contracts. A successful local demo is not a claim that a live backend or platform service is connected.</p></section>
    <nav>{TABS.map(item=><button key={item} onClick={()=>setTab(item)} className={tab===item?"active":""}>{item}</button>)}</nav>
    <section className="panel">{tab==="Replay"?<ReplayLab/>:tab==="Spectator"?<SpectatorLab/>:tab==="Guild"?<GuildLab/>:tab==="Leaderboard"?<LeaderboardLab/>:tab==="Cloud Save"?<CloudSaveLab/>:<UgcLab/>}</section>
    <section className="truth"><b>Evidence boundary</b><span>Live spectator delivery, guild persistence, public ranked boards, platform achievements, cloud synchronization and public UGC still require verified provider/backend evidence, moderation, real-device testing and production observability.</span></section>
    <style jsx>{`.shell{min-height:100vh;background:#020705;color:#f0faf5;font-family:Inter,system-ui;padding-bottom:70px}.bg{position:fixed;inset:0;background:radial-gradient(circle at 78% 10%,#d9bf6120,transparent 30%),linear-gradient(180deg,#020705e8,#020705fb),url('/soolen-ai-landscape.jpg') center/cover;z-index:0}header,.hero,nav,.panel,.truth{position:relative;z-index:1;width:min(1100px,calc(100% - 28px));margin:auto}header{display:flex;justify-content:space-between;padding:24px 0;font-size:10px;letter-spacing:.13em;font-weight:900}header a{color:#fff;text-decoration:none}header span,.hero small{color:#e2c566}.hero{padding:60px 0 26px}.hero h1{font-size:clamp(48px,8vw,88px);line-height:.94;letter-spacing:-.05em;margin:10px 0}.hero em{font-style:normal;color:#e2c566}.hero p{max-width:850px;color:#aabcb4;line-height:1.7}nav{display:flex;gap:7px;flex-wrap:wrap;margin-bottom:12px}nav button{border:1px solid #ffffff12;background:#071811;color:#9fb1a9;padding:9px 12px;border-radius:999px;font-weight:800;font-size:10px}nav button.active{background:#e2c566;color:#07110d}.panel,.truth{border:1px solid #ffffff12;background:#061813e9;border-radius:24px;padding:22px;backdrop-filter:blur(16px)}.truth{margin-top:12px;display:grid;gap:5px}.truth b{color:#e2c566}.truth span{color:#8fa199;font-size:11px;line-height:1.5}:global(.labGrid){display:grid;grid-template-columns:1fr 1fr;gap:12px}:global(.card){border:1px solid #ffffff10;background:#091f17;border-radius:18px;padding:16px}:global(.card h2){margin:0 0 8px;font-size:22px}:global(.card p),:global(.card li){color:#9caf a6;font-size:11px;line-height:1.55}:global(.row){display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}:global(button.action){border:0;border-radius:12px;background:#d9bf61;color:#07110d;padding:10px 12px;font-weight:900}:global(button.secondary){border:1px solid #ffffff12;border-radius:12px;background:#0a2119;color:#d7e5de;padding:10px 12px;font-weight:800}:global(input.field),:global(textarea.field){width:100%;box-sizing:border-box;border:1px solid #ffffff12;border-radius:12px;background:#020a08;color:#fff;padding:11px;margin-top:8px}:global(.metric){font-size:30px;font-weight:950;color:#e2c566}:global(.mono){font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:10px;white-space:pre-wrap;color:#a9bbb2;background:#020a08;border-radius:12px;padding:10px;max-height:260px;overflow:auto}@media(max-width:720px){:global(.labGrid){grid-template-columns:1fr}.hero{padding-top:42px}}`}</style>
  </main>;
}

function ReplayLab(){
  const[replay,setReplay]=useState(()=>createReplayRecorder({gameVersion:"demo-1"}));const[time,setTime]=useState(0);const[closed,setClosed]=useState(null);
  function add(type){const next={...replay,events:[...replay.events],snapshots:[...replay.snapshots]};recordReplayEvent(next,{at:time,type,payload:{score:time*10}});if(type==="checkpoint")recordReplaySnapshot(next,{at:time,state:{x:time,y:0,score:time*10}});setReplay(next);setTime(t=>t+1);}
  const view=seekReplay(closed||replay,Math.max(0,time-1));
  return <div className="labGrid"><div className="card"><h2>Replay Recorder</h2><p>Records bounded deterministic events and snapshots with game-version compatibility metadata.</p><div className="metric">{replay.events.length} events</div><div className="row"><button className="action" onClick={()=>add("move")}>Record Move</button><button className="secondary" onClick={()=>add("checkpoint")}>Checkpoint</button><button className="secondary" onClick={()=>setClosed(finishReplay(replay,{duration:time}))}>Finish Replay</button></div></div><div className="card"><h2>Replay Viewer</h2><p>Seek uses the nearest prior snapshot, then replays bounded events up to the target time.</p><div className="mono">{JSON.stringify(view,null,2)}</div></div></div>;
}

function SpectatorLab(){const[delay,setDelay]=useState(8);const policy=useMemo(()=>createSpectatorPolicy({delaySeconds:delay,maxViewers:100}),[delay]);return <div className="labGrid"><div className="card"><h2>Spectator Policy</h2><p>Read-only by design. Spectators receive authoritative snapshots and never gain gameplay input authority.</p><label>Anti-stream-sniping delay<input className="field" type="number" min="0" max="120" value={delay} onChange={e=>setDelay(Number(e.target.value))}/></label></div><div className="card"><h2>Evidence</h2><div className="mono">{JSON.stringify(policy,null,2)}</div></div></div>}

function GuildLab(){const[guild,setGuild]=useState(()=>createGuildState({id:"g1",name:"Soolen Guild",ownerId:"owner"}));const[notice,setNotice]=useState("");function invite(){const next={...guild,members:new Map(guild.members),audit:[...guild.audit]};const result=guildInvite(next,{actorId:"owner",userId:`member${next.members.size}`});if(result.ok){guildJoin(next,result.invite);setGuild(next);setNotice("Member joined through role-checked invitation.");}else setNotice(result.reason);}return <div className="labGrid"><div className="card"><h2>Guild / Clan</h2><div className="metric">{guild.members.size} members</div><p>Owner/officer permission checks and audit events are enforced before membership changes.</p><button className="action" onClick={invite}>Invite Demo Member</button><p>{notice}</p></div><div className="card"><h2>Members</h2><div className="mono">{JSON.stringify([...guild.members.values()],null,2)}</div></div></div>}

function LeaderboardLab(){const[board,setBoard]=useState(()=>createLeaderboard({season:"S1",limit:10}));const[ach,setAch]=useState(()=>createAchievementState([{id:"win_3",target:3}]));const[count,setCount]=useState(0);function submit(){const next={...board,entries:new Map(board.entries)};const id=`p${count+1}`;submitLeaderboardScore(next,{playerId:id,displayName:`Player ${count+1}`,score:1000+count*130,tiebreak:20-count,validated:true});setBoard(next);const a={...ach,progress:{...ach.progress},unlocked:{...ach.unlocked},pendingSync:[...ach.pendingSync]};progressAchievement(a,"win_3",1);setAch(a);setCount(count+1);}return <div className="labGrid"><div className="card"><h2>Ranked Board</h2><button className="action" onClick={submit}>Submit Server-Validated Demo Score</button><div className="mono">{JSON.stringify(leaderboardRows(board),null,2)}</div></div><div className="card"><h2>Achievement</h2><p>Idempotent progress with an offline sync queue; platform trophy success is not assumed.</p><div className="mono">{JSON.stringify(ach,null,2)}</div></div></div>}

function CloudSaveLab(){const[rev,setRev]=useState(1);const local=createCloudSaveEnvelope({deviceId:"iphone",revision:rev,data:{level:4,coins:120}}),remote=createCloudSaveEnvelope({deviceId:"android",revision:rev,data:{level:5,coins:90}}),merged=mergeCloudSave(local,remote);return <div className="labGrid"><div className="card"><h2>Cloud Save Envelope</h2><p>Version, revision, checksum and device identity are kept separate from the save payload.</p><button className="action" onClick={()=>setRev(r=>r+1)}>Increase Local Revision</button><div className="mono">{JSON.stringify(local,null,2)}</div></div><div className="card"><h2>Conflict Resolver</h2><p>Equal revisions with different content fail closed instead of silently overwriting another device.</p><div className="mono">{JSON.stringify(merged,null,2)}</div></div></div>}

function UgcLab(){const[name,setName]=useState("Forest Trial");const[count,setCount]=useState(4);const level={name,bounds:{width:120,height:120},entities:Array.from({length:Math.max(0,count)},(_,i)=>({type:i===0?"spawn":"platform",x:i*8,y:0}))};const result=validateUgcLevel(level);return <div className="labGrid"><div className="card"><h2>UGC Visual Level Editor</h2><label>Level name<input className="field" value={name} onChange={e=>setName(e.target.value)}/></label><label>Entity count<input className="field" type="number" min="0" max="600" value={count} onChange={e=>setCount(Number(e.target.value))}/></label><p>Public sharing stays disabled until schema validation, play-test and moderation evidence exist.</p></div><div className="card"><h2>Validation</h2><div className="mono">{JSON.stringify(result,null,2)}</div></div></div>}
