"use client";

import { useState } from "react";

export default function Home() {
  const [idea, setIdea] = useState("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState("");

  async function createApp() {
    const value = idea.trim();

    if (!value) {
      setError("Tell me what you want to build.");
      return;
    }

    setLoading(true);
    setError("");
    setResult(null);

    try {
      const response = await fetch("/api/generate", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          idea: value,
        }),
      });

      const data = await response.json();

      if (!response.ok || !data.success) {
        throw new Error(data.error || "Unable to generate app.");
      }

      setResult(data);
    } catch (err) {
      setError(err?.message || "Something went wrong.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <main
      style={{
        minHeight: "100vh",
        padding: "60px 24px",
        fontFamily: "Arial, sans-serif",
        background: "#f7f7f5",
      }}
    >
      <div
        style={{
          maxWidth: 900,
          margin: "0 auto",
        }}
      >
        <h1
          style={{
            fontSize: 48,
            marginBottom: 12,
          }}
        >
          AI App Builder
        </h1>

        <p
          style={{
            fontSize: 20,
            color: "#666",
            marginBottom: 32,
          }}
        >
          Describe your idea. AI builds your app.
        </p>

        <textarea
          value={idea}
          onChange={(e) => setIdea(e.target.value)}
          placeholder="Example: Build a real estate CRM for managing clients and properties..."
          rows={6}
          style={{
            width: "100%",
            padding: 18,
            fontSize: 18,
            borderRadius: 12,
            border: "1px solid #ccc",
            resize: "vertical",
            boxSizing: "border-box",
          }}
        />

        <button
          onClick={createApp}
          disabled={loading}
          style={{
            marginTop: 16,
            padding: "15px 28px",
            fontSize: 18,
            borderRadius: 10,
            border: "none",
            cursor: loading ? "wait" : "pointer",
          }}
        >
          {loading ? "AI is building..." : "Create App"}
        </button>

        {error && (
          <div
            style={{
              marginTop: 24,
              padding: 16,
              borderRadius: 10,
              background: "#ffe8e8",
            }}
          >
            {error}
          </div>
        )}

        {result?.specification && (
          <section
            style={{
              marginTop: 40,
              padding: 28,
              background: "#fff",
              borderRadius: 16,
              border: "1px solid #ddd",
            }}
          >
            <h2>{result.specification.name}</h2>

            <p>{result.specification.description}</p>

            <h3>Pages</h3>

            <ul>
              {result.specification.pages?.map((page) => (
                <li key={page.name}>
                  <strong>{page.name}</strong>
                  {" — "}
                  {page.purpose}
                </li>
              ))}
            </ul>

            <h3>Features</h3>

            <ul>
              {result.specification.features?.map((feature) => (
                <li key={feature.name}>
                  <strong>{feature.name}</strong>
                  {" — "}
                  {feature.description}
                </li>
              ))}
            </ul>

            <p
              style={{
                marginTop: 24,
                color: "#666",
              }}
            >
              Generated by: {result.aiProvider}
            </p>
          </section>
        )}
      </div>
    </main>
  );
}
