import { NextResponse } from "next/server";
import { createClient } from "../../../lib/supabase/server.js";
import { createAdminClient } from "../../../lib/supabase/admin.js";
import { normalizeAppSpec } from "../../../lib/generator/runtime-guard.js";
import { buildAppExplanation } from "../../../lib/generator/app-explanation.js";
import { selfTestGeneratedApp } from "../../../lib/generator/self-test.js";
import { assessBuildQuality,GENERATION_QUALITY_RULES } from "../../../lib/buildStandards.js";
import { evaluateReleaseReadiness } from "../../../lib/release-readiness.js";
import { generateWithFallback } from "../../../engine/ai-provider.js";
import { buildProjectMemoryBrief,mergeProjectMemory } from "../../../lib/project-memory.js";
import { PRODUCT_BRAND,PREMIUM_VISUAL_AI_INSTRUCTION } from "../../../lib/ai/premium-visual-policy.js";
import { buildPreciseEditInstruction } from "../../../lib/editor/precise-edit-policy.js";
import { inspectProjectSpecification,buildSelfHealInstruction } from "../../../lib/ai/project-self-heal-policy.js";
import { consumeAppBuilderEntitlement,consumeAiCredits,refundAiCredits } from "../../../lib/app-builder-finance.js";
import { redesignAndAuditPremiumExperience } from "../../../lib/ai/premium-experience-system.js";

export const maxDuration=120;

const MODIFY_CREDIT_COST=Math.max(1,Number(process.env.APP_MODIFY_CREDIT_COST||5));
const PRIMARY_AI_TIMEOUT_MS=Math.min(50000,Math.max(15000,Number(process.env.MODIFY_PRIMARY_AI_TIMEOUT_MS||40000)));
const REPAIR_AI_TIMEOUT_MS=Math.min(40000,Math.max(10000,Number(process.env.MODIFY_REPAIR_AI_TIMEOUT_MS||30000)));

function extractJson(text){const raw=String(text||"").trim();try{return JSON.parse(raw)}catch{}const fenced=raw.match(/```(?:json)?\s*([\s\S]*?)\s*```/i);if(fenced){try{return JSON.parse(fenced[1])}catch{}}const start=raw.indexOf("{"),end=raw.lastIndexOf("}");if(start>=0&&end>start){try{return JSON.parse(raw.slice(start,end+1))}catch{}}throw new Error("AI returned invalid JSON.");}
function normalizeAndTest(raw){const normalized=normalizeAppSpec(raw),selfTest=selfTestGeneratedApp(normalized);if(!selfTest.ok)throw new Error(`Modified app failed self-test: ${selfTest.errors.join("; ")}`);const specification=selfTest.normalizedSpec;return{specification,selfTest,quality:assessBuildQuality(specification),selfHeal:inspectProjectSpecification(specification)};}
function qualityRegressed(before,after){if(!before||!after)return true;if(Number(after.overall||0)<Number(before.overall||0))return true;const oldMap=Object.fromEntries((before.dimensions||[]).map(x=>[x.id,Number(x.score||0)]));return(after.dimensions||[]).some(x=>Number(x.score||0)<Number(oldMap[x.id]||0));}
function visualMemory(spec){const d=spec?.designSystem||{};return{themeMode:d.themeMode||"auto",colorPreference:d.colorPreference||"",primaryColor:d.primaryColor||"",secondaryColor:d.secondaryColor||"",accentColor:d.accentColor||"",backgroundColor:d.backgroundColor||"",surfaceColor:d.surfaceColor||"",textColor:d.textColor||"",wallpaperMode:d.wallpaperMode||"random",wallpaperPreset:d.wallpaperPreset||"",visualDirection:d.visualDirection||"",imageStyle:d.imageStyle||"",cardStyle:d.cardStyle||""};}
async function withTimeout(promise,ms,label){let timer;try{return await Promise.race([promise,new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error(`${label} timed out after ${ms}ms`)),ms)})])}finally{clearTimeout(timer)}}
function preciseTargetFrom(body){const target=body?.preciseTarget;if(!target||typeof target!=="object"||Array.isArray(target))return null;return{pageName:String(target.pageName||"").trim().slice(0,160),pageIndex:Number.isInteger(target.pageIndex)?target.pageIndex:null,sectionName:String(target.sectionName||"").trim().slice(0,160),sectionIndex:Number.isInteger(target.sectionIndex)?target.sectionIndex:null,lineNumber:Number.isInteger(target.lineNumber)&&target.lineNumber>0?target.lineNumber:null,elementType:String(target.elementType||"").trim().slice(0,40),position:String(target.position||"").trim().slice(0,160)};}

export async function POST(request){
 let supabase=null,userId=null,charged=false,chargeRequestId=null,charge=null;
 try{
  supabase=await createClient();const{data:{user},error:userError}=await supabase.auth.getUser();if(userError||!user)return NextResponse.json({error:"Authentication required."},{status:401});userId=user.id;if(!user.confirmed_at&&!user.email_confirmed_at&&!user.phone_confirmed_at)return NextResponse.json({error:"Please verify your email or phone before modifying an app."},{status:403});
  const body=await request.json(),instruction=String(body?.instruction||"").trim(),clientSpecification=body?.specification,appId=body?.appId||null,preciseTarget=preciseTargetFrom(body);chargeRequestId=String(body?.requestId||crypto.randomUUID()).trim().slice(0,160);if(!instruction)return NextResponse.json({error:"Modification instruction is required."},{status:400});if(instruction.length>4000)return NextResponse.json({error:"Modification instruction is too long."},{status:413});

  let memoryRow=null,effectiveSpecification=clientSpecification,baseVersionId=null;
  if(appId){
    const{data:owned,error:e}=await supabase.from("apps").select("id,current_version_id").eq("id",appId).eq("owner_id",user.id).single();if(e||!owned)return NextResponse.json({error:"App not found or access denied."},{status:404});
    if(!owned.current_version_id)return NextResponse.json({error:"This project has no current saved version yet."},{status:409});baseVersionId=owned.current_version_id;
    const{data:currentVersion,error:versionError}=await supabase.from("app_versions").select("id,specification").eq("id",baseVersionId).eq("app_id",appId).maybeSingle();if(versionError||!currentVersion?.specification)return NextResponse.json({error:"Current project version could not be loaded safely."},{status:409});
    effectiveSpecification=currentVersion.specification;
    const{data:memory}=await supabase.from("project_memory").select("memory_json,learning_scope").eq("app_id",appId).eq("owner_id",user.id).maybeSingle();memoryRow=memory||null;
  }
  if(!effectiveSpecification)return NextResponse.json({error:"App specification is required."},{status:400});

  const entitlement=await consumeAppBuilderEntitlement(user.id,{operation:"modify",appId,requestId:chargeRequestId}),entitlementSource=entitlement?.allowed?entitlement.source:null;if(!entitlement?.allowed){charge=await consumeAiCredits(user.id,{amount:MODIFY_CREDIT_COST,requestId:chargeRequestId,description:"AI app modification",metadata:{operation:"modify",appId}});charged=Boolean(charge?.charged);}
  const memoryBrief=buildProjectMemoryBrief(memoryRow),currentQuality=assessBuildQuality(normalizeAppSpec(effectiveSpecification));
  const effectiveInstruction=preciseTarget?buildPreciseEditInstruction({...preciseTarget,instruction}):instruction;
  const prompt=`You are the modification engine for ${PRODUCT_BRAND.name}, powered by SoolenAI. Modify the existing App + Website according to this instruction:\n"${effectiveInstruction}"\n${memoryBrief?`\n${memoryBrief}\n`:""}\n\nNON-NEGOTIABLE QUALITY STANDARD:\n${GENERATION_QUALITY_RULES}\n\nPREMIUM VISUAL IDEAL:\n${PREMIUM_VISUAL_AI_INSTRUCTION}\n\nCurrent specification:\n${JSON.stringify(effectiveSpecification)}\nReturn ONLY valid JSON with name, description, designSystem, visualAssets, qualityPlan, pages, features, data, dataModels, actions and navigation. Preserve and improve the existing qualityPlan with at least 3 concrete implementation decisions for every quality dimension. A current customer request about color, theme, style or wallpaper overrides older visual preferences and must coordinate the entire visual system. Preserve existing functionality and remembered project preferences unless the customer's current instruction explicitly changes them. Do not silently remove authentication, permissions, privacy, validation, loading/error states, responsive behavior or accessibility protections. Never reuse private assets across customers. No markdown.`;
  const ai=await withTimeout(generateWithFallback(prompt),PRIMARY_AI_TIMEOUT_MS,"Primary AI modification"),finalProviderStart=ai.provider;let finalProvider=finalProviderStart,candidate=normalizeAndTest(extractJson(ai.result)),qualityRepairApplied=false,selfHealApplied=false;
  if(qualityRegressed(currentQuality,candidate.quality)){
    const repairPrompt=`You are SoolenAI Quality Repair for ${PRODUCT_BRAND.name}. The requested edit is valid, but the candidate version reduced deterministic release quality compared with the previous saved specification. Repair the candidate while preserving the customer's requested change, color/theme/wallpaper direction and every working feature.\n\nCUSTOMER REQUEST:\n${effectiveInstruction}\n\nQUALITY STANDARD:\n${GENERATION_QUALITY_RULES}\n\nPREVIOUS QUALITY:\n${JSON.stringify(currentQuality)}\n\nCANDIDATE QUALITY:\n${JSON.stringify(candidate.quality)}\n\nCANDIDATE SPECIFICATION:\n${JSON.stringify(candidate.specification)}\n\nReturn ONLY the complete repaired JSON specification, including a complete qualityPlan. Do not invent compliance claims or remove functionality.`;
    const repairedAI=await withTimeout(generateWithFallback(repairPrompt),REPAIR_AI_TIMEOUT_MS,"AI quality repair"),repaired=normalizeAndTest(extractJson(repairedAI.result));if(qualityRegressed(currentQuality,repaired.quality))throw new Error("AI edit was not saved because it would reduce the project's release quality. Try a more specific change.");candidate=repaired;finalProvider=repairedAI.provider;qualityRepairApplied=true;
  }
  if(!candidate.selfHeal.passed){
    const selfHealPrompt=`You are SoolenAI Self-Heal for ${PRODUCT_BRAND.name}. Repair only the verified structural/runtime-readiness problems in the candidate below while preserving the customer's requested edit.\n\n${buildSelfHealInstruction({specification:candidate.specification})}\n\nCUSTOMER REQUEST:\n${effectiveInstruction}\n\nPREVIOUS KNOWN-GOOD SPECIFICATION:\n${JSON.stringify(effectiveSpecification)}\n\nCANDIDATE SPECIFICATION:\n${JSON.stringify(candidate.specification)}\n\nReturn ONLY the full corrected JSON specification. Keep the previous version as the safety baseline. Do not invent external-provider success.`;
    const healedAI=await withTimeout(generateWithFallback(selfHealPrompt),REPAIR_AI_TIMEOUT_MS,"AI self-heal"),healed=normalizeAndTest(extractJson(healedAI.result));if(!healed.selfHeal.passed)throw new Error("AI edit was not saved because self-heal could not produce a safe validated version.");if(qualityRegressed(currentQuality,healed.quality))throw new Error("AI edit was not saved because self-heal reduced the project's release quality.");candidate=healed;finalProvider=healedAI.provider;selfHealApplied=true;
  }
  const visualQuality=redesignAndAuditPremiumExperience(candidate.specification,{idea:effectiveInstruction,themeMode:candidate.specification?.designSystem?.themeMode,primaryColor:candidate.specification?.designSystem?.primaryColor,accentColor:candidate.specification?.designSystem?.accentColor,backgroundColor:candidate.specification?.designSystem?.backgroundColor,wallpaperMode:candidate.specification?.designSystem?.wallpaperMode});const acceptedForPreview=visualQuality.passed;if(!acceptedForPreview)throw new Error(`AI edit failed the 100-point visual audit: ${visualQuality.after.errors.join("; ")}`);const finalSpec=visualQuality.specification,test=candidate.selfTest,finalQuality=assessBuildQuality(finalSpec),finalReadiness=evaluateReleaseReadiness(finalQuality);let savedVersion=null;
  if(appId){
    const admin=createAdminClient();const{data:version,error:versionError}=await admin.rpc("server_save_app_modification",{p_user_id:user.id,p_app_id:appId,p_expected_version_id:baseVersionId,p_request_id:chargeRequestId,p_specification:finalSpec,p_change_summary:instruction});if(versionError)throw versionError;savedVersion=version;
    const nextMemory=mergeProjectMemory(memoryRow?.memory_json,{requestedName:finalSpec.name,visualPreferences:visualMemory(finalSpec),lastModificationAt:new Date().toISOString(),lastModificationInstruction:instruction,lastPreciseTarget:preciseTarget||undefined,lastSelfHealApplied:selfHealApplied});const{error:memoryError}=await supabase.from("project_memory").upsert({app_id:appId,owner_id:user.id,memory_json:nextMemory,learning_scope:memoryRow?.learning_scope||"project_only",updated_at:new Date().toISOString()},{onConflict:"app_id"});if(memoryError)console.warn("PROJECT_MEMORY_MODIFY_SAVE_ERROR",memoryError.message);
  }
  return NextResponse.json({success:true,provider:finalProvider,specification:finalSpec,visualQuality:{before:visualQuality.before,after:visualQuality.after,acceptedForPreview},appId,version:savedVersion,preciseEdit:{applied:Boolean(preciseTarget),target:preciseTarget},selfHeal:{applied:selfHealApplied,report:candidate.selfHeal},projectMemory:{applied:Boolean(memoryBrief),updated:Boolean(appId),visualPreferences:visualMemory(finalSpec)},explanation:buildAppExplanation(finalSpec),selfTest:test,quality:{before:currentQuality,after:finalQuality,repairApplied:qualityRepairApplied,releaseReadiness:finalReadiness},entitlement:{source:entitlementSource,charged},credits:{charged:charged?MODIFY_CREDIT_COST:0,requestId:chargeRequestId,balance:charge?.balance??null}});
 }catch(error){console.error("Modify API error:",error);if(charged&&chargeRequestId&&userId){try{await refundAiCredits(userId,{requestId:chargeRequestId,amount:MODIFY_CREDIT_COST,description:"AI modification failed - automatic refund",metadata:{operation:"modify"}})}catch{}}
  const message=String(error?.message||"");if(message.includes("would reduce the project's release quality")||message.includes("self-heal could not produce")||message.includes("self-heal reduced"))return NextResponse.json({error:message},{status:409});if(message.includes("Project changed during modification"))return NextResponse.json({error:"This project changed while AI was working. Refresh the workspace and try the change again."},{status:409});if(message.includes("Insufficient credits"))return NextResponse.json({error:"Insufficient credits.",requiredCredits:MODIFY_CREDIT_COST},{status:402});if(message.includes("Server financial runtime is not configured"))return NextResponse.json({error:"Secure billing runtime is not configured yet."},{status:503});if(/timed out|time budget/i.test(message))return NextResponse.json({error:"AI modification reached its safety time limit. No new version was accepted."},{status:504});if(message.includes("All authorized AI providers failed"))return NextResponse.json({error:"AI providers are temporarily unavailable. Please try again."},{status:503});return NextResponse.json({error:"Unable to modify the app. Any charged credits were automatically refunded."},{status:500});}
}
