"use client";

import Link from "next/link";
import { useEffect,useState } from "react";

const CHANNELS=[
  ["email","Email Delivery","Send confirmations, receipts and follow-ups."],
  ["sms","SMS Delivery","Send verification, reminders and alerts."],
  ["calendar","Calendar","Create appointments and event reminders."],
  ["payments","Payments","Prepare payment and subscription connections."],
  ["maps","Maps","Prepare maps and location features."],
  ["whatsapp","WhatsApp","Prepare business messaging workflows."],
];

export default function IntegrationsPage({params}){
  const[appId,setAppId]=useState("");const[app,setApp]=useState(null);const[managed,setManaged]=useState({});const[saved,setSaved]=useState([]);const[busy,setBusy]=useState("");const[error,setError]=useState("");const[message,setMessage]=useState("");
  useEffect(()=>{Promise.resolve(params).then(v=>setAppId(v.id))},[params]);
  useEffect(()=>{if(appId)load()},[appId]);
  async function load(){setError("");try{const r=await fetch(`/api/apps/${appId}/integrations`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d?.error||"Unable to load integrations.");setApp(d.app);setManaged(d.managed||{});setSaved(d.project||[])}catch(e){setError(e.message)}}
  async function toggle(type){setBusy(type);setError("");setMessage("");try{const current=saved.find(x=>x.integration_type===type);const r=await fetch(`/api/apps/${appId}/integrations`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({type,enabled:current? !current.enabled:true})});const d=await r.json();if(!r.ok)throw new Error(d?.error||"Unable to update integration.");setMessage(`${d.integration.display_name} updated.`);await load()}catch(e){setError(e.message)}finally{setBusy("")}}
  return <main className="page"><div className="wrap"><Link className="back" href={appId?`/app-dashboard/${appId}`:"/my-apps"}>← Project Folder</Link><div className="eyebrow">SOOLENAI · INTEGRATION CENTER</div><h1>{app?.name||"Project"}</h1><p className="intro">Connect business capabilities without exposing provider names, API keys or infrastructure to customers. Platform secrets remain server-side.</p><section className="grid">{CHANNELS.map(([type,name,description])=>{const record=saved.find(x=>x.integration_type===type);const platformReady=managed?.[type]?.ready===true;const enabled=record?.enabled!==false;const operational=platformReady&&enabled;return <article key={type}><div className="top"><span>{name}</span><b className={operational?"ready":platformReady?"paused":"waiting"}>{operational?"READY":platformReady?"PAUSED":"SETUP NEEDED"}</b></div><p>{description}</p><small>{platformReady?"Managed delivery layer available":"Platform delivery credentials are not configured yet"}</small><button disabled={busy===type||!platformReady} onClick={()=>toggle(type)}>{!platformReady?"Waiting for platform setup":enabled?"Pause for this project":"Enable for this project"}</button></article>})}</section><div className="security">🔐 Customer projects never store API keys, passwords or provider secrets in visible configuration.</div>{message&&<div className="msg">{message}</div>}{error&&<div className="err">{error}</div>}</div><style jsx>{`.page{min-height:100vh;padding:34px 18px 80px;background:linear-gradient(145deg,#03100d,#0a2119 58%,#06140f);color:#f5fff9}.wrap{max-width:1100px;margin:auto}.back{color:#d8bf62;text-decoration:none}.eyebrow{margin-top:26px;color:#d8bf62;letter-spacing:.18em;font-size:11px;font-weight:900}h1{font-size:48px;margin:8px 0}.intro{max-width:800px;color:#9cb0a8;line-height:1.65}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:28px}.grid article{border:1px solid rgba(216,191,98,.18);background:rgba(3,16,13,.8);border-radius:20px;padding:20px}.top{display:flex;justify-content:space-between;gap:10px}.top span{font-weight:900}.top b{font-size:10px}.ready{color:#83ddb5}.paused{color:#e9c56b}.waiting{color:#9caea6}.grid p,.grid small{color:#94a89f}.grid small{display:block;min-height:34px}.grid button{width:100%;margin-top:16px;border:0;border-radius:11px;padding:11px;background:#d8bf62;color:#07130e;font-weight:900}.grid button:disabled{opacity:.45}.security,.msg,.err{margin-top:16px;padding:13px;border-radius:13px}.security{background:#1c6b4d22;color:#9fe2c2}.msg{background:#1c6b4d33;color:#9fe2c2}.err{background:#7c2d2d44;color:#ffb5ad}@media(max-width:800px){.grid{grid-template-columns:1fr 1fr}}@media(max-width:560px){.grid{grid-template-columns:1fr}h1{font-size:38px}}`}</style></main>}
