// Machine-refreshable, pattern-only trend evidence for LANERIQ AI.
// Do not store or inject third-party branding, copy, assets or layouts here.
// Source observations are reduced to anonymous LANERIQ pattern IDs + chart rank.

export const TREND_SIGNAL_SNAPSHOT = Object.freeze({
  schemaVersion: 1,
  region: 'MY',
  observedAt: '2026-09-03T15:02:00.000Z',
  source: 'apple-app-store-top-free',
  sourceKind: 'official-store-chart',
  sourceUrl: 'https://rss.marketingtools.apple.com/api/v2/my/apps/top-free/100/apps.json',
  chartSize: 100,
  signals: Object.freeze([
    { patternId:'group-buy-commerce', rank:1, chart:'all' },
    { patternId:'digital-identity', rank:2, chart:'all' },
    { patternId:'mobile-wallet', rank:3, chart:'all' },
    { patternId:'short-drama-stream', rank:4, chart:'all' },
    { patternId:'government-services', rank:5, chart:'all' },
    { patternId:'brand-membership', rank:6, chart:'all' },
    { patternId:'coffee-ordering', rank:7, chart:'all' },
    { patternId:'social-thread-feed', rank:8, chart:'all' },
    { patternId:'telecom-selfservice', rank:9, chart:'all' },
    { patternId:'ai-assistant-chat', rank:10, chart:'all' },
    { patternId:'travel-booking', rank:12, chart:'all' },
    { patternId:'map-navigation', rank:13, chart:'all' },
    { patternId:'photo-editor-ai', rank:14, chart:'all' },
    { patternId:'super-app-home', rank:16, chart:'all' },
    { patternId:'ecommerce-marketplace', rank:20, chart:'all' },
    { patternId:'food-delivery', rank:23, chart:'all' },
    { patternId:'fuel-mobility', rank:19, chart:'all' },
    { patternId:'short-drama-stream', rank:1, chart:'entertainment' },
    { patternId:'video-streaming', rank:9, chart:'entertainment' },
    { patternId:'photo-editor-ai', rank:1, chart:'photo-video' },
    { patternId:'video-editor-mobile', rank:2, chart:'photo-video' },
    { patternId:'design-canvas', rank:9, chart:'photo-video' },
    { patternId:'ecommerce-marketplace', rank:3, chart:'shopping' },
    { patternId:'classified-listings', rank:8, chart:'shopping' },
    { patternId:'fitness-tracker', rank:1, chart:'health-fitness' },
    { patternId:'nutrition-tracker', rank:3, chart:'health-fitness' },
    { patternId:'health-booking', rank:9, chart:'health-fitness' },
    { patternId:'gaming-platform', rank:2, chart:'games' },
    { patternId:'moba-lobby', rank:4, chart:'games' },
    { patternId:'casual-puzzle', rank:6, chart:'games' },
    { patternId:'survival-strategy', rank:9, chart:'games' },
    { patternId:'sports-game-hub', rank:10, chart:'games' },
    { patternId:'endless-runner', rank:11, chart:'games' },
    { patternId:'battle-royale-lobby', rank:12, chart:'games' },
  ]),
});
