// LANERIQ AI Trending App Reference Patterns
// Product-pattern inspiration only. Never copy third-party brand identity, source code, text,
// proprietary assets, distinctive trade dress or exact layouts.
// Refresh the evidence-backed ranking metadata independently from this bounded pattern vocabulary.

const P=(id,family,patterns,signals=[])=>Object.freeze({id,family,patterns:Object.freeze(patterns),signals:Object.freeze(signals)});

export const TRENDING_APP_REFERENCE_PATTERNS=Object.freeze([
P('ai-assistant-chat','AI assistant',['conversational command surface','multimodal input','thread history','suggested actions'],['ai','assistant','chat','agent']),
P('ai-search-answer','AI search',['answer-first search','source-aware results','follow-up exploration','saved research'],['search','research','answer engine']),
P('ai-creation-studio','AI creation',['prompt workspace','generation history','variant comparison','export/share'],['generate','creator','ai studio']),
P('short-video-feed','Short video',['vertical swipe feed','creator identity','engagement rail','sound/remix entry'],['short video','reels','tiktok','短视频']),
P('short-drama-stream','Short drama',['episode-first feed','fast resume','unlock/continue loop','episode discovery'],['short drama','drama','短剧']),
P('social-thread-feed','Social',['text-first feed','reply tree','repost/share','topic discovery'],['social','thread','discussion']),
P('photo-social-feed','Social',['visual feed','stories/status','creator profile','messaging entry'],['photo social','instagram','照片社区']),
P('community-chat','Community',['server/group navigation','channel chat','voice rooms','role-aware community'],['discord','community','group chat']),
P('private-messaging','Messaging',['conversation list','media sharing','read states','calling entry'],['messaging','whatsapp','chat']),
P('super-app-home','Super app',['service launcher','wallet balance','personalized shortcuts','cross-service activity'],['super app','grab','one app']),
P('ride-hailing','Mobility',['map-first pickup','destination search','driver status','trip safety'],['ride','taxi','car booking']),
P('food-delivery','Delivery',['merchant discovery','menu browse','cart','live order tracking'],['food delivery','restaurant delivery','外卖']),
P('grocery-delivery','Delivery',['category browse','repeat basket','substitution flow','delivery slot'],['grocery','groceries','生鲜']),
P('parcel-tracking','Logistics',['tracking timeline','map status','delivery instructions','proof of delivery'],['parcel','shipment','tracking']),
P('map-navigation','Maps',['map-first canvas','search nearby','route alternatives','live traffic'],['maps','navigation','route']),
P('travel-booking','Travel',['search matrix','price comparison','traveller details','trip management'],['flight','hotel','train','trip']),
P('travel-itinerary','Travel',['day-by-day itinerary','map pins','booking vault','collaborative planning'],['itinerary','trip planner']),
P('hotel-booking','Hospitality',['destination/date search','room comparison','guest details','booking management'],['hotel','resort','rooms']),
P('event-ticketing','Events',['event discovery','seat/ticket selection','wallet pass','event reminders'],['ticket','event','concert']),
P('ecommerce-marketplace','Commerce',['personalized discovery','product cards','cart/checkout','order tracking'],['shop','shopping','marketplace','ecommerce']),
P('group-buy-commerce','Commerce',['deal urgency','group purchase','social sharing','discount ladder'],['group buy','pinduoduo','deal']),
P('live-commerce','Commerce',['live video product pins','chat reactions','instant cart','creator storefront'],['live shopping','直播带货']),
P('brand-membership','Loyalty',['member home','points balance','offers','purchase history'],['membership','club','loyalty']),
P('coffee-ordering','Food & beverage',['quick reorder','pickup location','menu customization','rewards'],['coffee','drink','pickup']),
P('restaurant-reservation','Food & beverage',['venue discovery','availability slots','party details','reservation management'],['reservation','restaurant booking']),
P('mobile-wallet','Finance',['balance-first home','scan/pay','transfer','transaction history'],['wallet','ewallet','pay']),
P('banking-dashboard','Finance',['account overview','quick transfer','cards','spending insights'],['bank','banking','finance']),
P('digital-identity','Identity',['identity wallet','verification status','credential sharing','security recovery'],['digital id','identity','credential']),
P('government-services','Government',['service catalogue','application status','digital documents','alerts'],['government','public service','permit']),
P('pension-finance','Finance',['portfolio/account overview','contribution history','withdrawal/service flows','statements'],['pension','retirement','epf']),
P('bill-payment','Finance',['biller shortcuts','amount confirmation','receipt vault','scheduled reminders'],['bill','payment','pay bill']),
P('expense-tracker','Finance',['spending overview','category analytics','budget goals','recurring detection'],['expense','budget','spending']),
P('investing-brokerage','Finance',['portfolio overview','watchlist','trade ticket','market news'],['invest','stocks','broker']),
P('crypto-wallet','Finance',['asset portfolio','send/receive','network status','security prompts'],['crypto','wallet','token']),
P('subscription-manager','Finance',['recurring list','next charge timeline','cancel/manage','spend summary'],['subscription','recurring']),
P('video-editor-mobile','Creator tools',['timeline editor','template/preset entry','media library','export presets'],['video editor','capcut','inshot']),
P('photo-editor-ai','Creator tools',['image canvas','AI enhancement','filters','before/after'],['photo editor','meitu','picsart']),
P('design-canvas','Creator tools',['template discovery','drag/drop canvas','brand assets','export/share'],['design','canva','poster']),
P('document-scanner','Productivity',['camera scan','edge cleanup','multi-page document','PDF export'],['scanner','pdf scan']),
P('notes-ai','Productivity',['note library','rich editor','AI summarize','search/link'],['notes','goodnotes','freenotes']),
P('office-document','Productivity',['document home','editor ribbon/actions','comments/collaboration','cloud files'],['word','document','office']),
P('spreadsheet','Productivity',['grid canvas','formula/actions','charts','share/collaborate'],['spreadsheet','excel']),
P('calendar-scheduler','Productivity',['calendar canvas','agenda','event editor','invite/availability'],['calendar','schedule']),
P('task-manager','Productivity',['inbox/today','project lists','quick add','completion analytics'],['task','todo','project']),
P('team-collaboration','Productivity',['workspace nav','activity feed','documents/tasks','mentions'],['workplace','team','collaboration']),
P('video-meeting','Communication',['meeting home','join/start CTA','participant grid','chat/share controls'],['meeting','zoom','video call']),
P('email-inbox','Communication',['priority inbox','thread view','compose','search/labels'],['email','mail','inbox']),
P('browser-search','Utilities',['omnibox','tab switcher','history/bookmarks','privacy controls'],['browser','chrome']),
P('telecom-selfservice','Utilities',['plan usage','bill','top-up/add-ons','support'],['telco','mobile plan','data']),
P('utility-account','Utilities',['account status','usage meter','bill/payment','service requests'],['utility','electricity','water']),
P('fuel-mobility','Mobility',['station finder','fuel/payment','loyalty','vehicle services'],['fuel','petrol','station']),
P('parking-payment','Mobility',['zone/location','duration selector','payment','expiry reminder'],['parking','park']),
P('vehicle-government','Government',['vehicle/license cards','renewal/status','fines/services','documents'],['vehicle','license','road transport']),
P('health-booking','Health',['provider discovery','appointment slots','patient details','visit history'],['doctor','clinic','appointment']),
P('telehealth','Health',['care entry','symptom intake','video consultation','care summary'],['telehealth','consult']),
P('fitness-tracker','Health',['daily activity','workout start','progress trends','goals'],['fitness','workout']),
P('nutrition-tracker','Health',['meal logging','macro overview','food search','goal progress'],['nutrition','calorie','diet']),
P('medication-reminder','Health',['today schedule','dose confirmation','refill status','caregiver sharing'],['medication','medicine']),
P('mental-wellness','Health',['daily check-in','guided session','progress streak','support resources'],['wellness','meditation','mental']),
P('language-learning','Education',['daily lesson','bite-size exercise','streak/progress','review mistakes'],['language','duolingo','learn']),
P('course-learning','Education',['course catalogue','lesson player','progress','quiz/certificate'],['course','learning']),
P('kids-learning','Education',['visual lesson map','safe profiles','reward loop','parent dashboard'],['kids learning','children']),
P('exam-prep','Education',['study plan','question bank','mock test','weak-topic analytics'],['exam','quiz','study']),
P('music-streaming','Media',['personalized home','player','library/playlists','discovery'],['music','spotify','streaming']),
P('video-streaming','Media',['content rails','detail/player','continue watching','profiles'],['netflix','streaming','video']),
P('anime-streaming','Media',['genre discovery','episode detail','watch progress','watchlist'],['anime','crunchyroll']),
P('podcast-player','Media',['show discovery','episode queue','player','downloads'],['podcast']),
P('news-reader','Media',['headline feed','topic tabs','article reader','save/follow'],['news']),
P('creator-fan-community','Creator economy',['creator feed','membership tiers','exclusive posts','support/purchase'],['creator','fans','membership']),
P('marketplace-seller','Commerce',['seller dashboard','list product','orders','performance insights'],['seller','merchant']),
P('classified-listings','Marketplace',['search/filter','listing cards','detail/contact','saved alerts'],['classified','listing']),
P('property-marketplace','Real estate',['map/list search','property detail','agent contact','saved search'],['property','real estate','house']),
P('real-estate-crm','Real estate',['lead pipeline','property matching','viewing calendar','commission dashboard'],['real estate crm','agent crm']),
P('rental-management','Real estate',['unit overview','tenant/lease','maintenance','payments'],['rental','tenant','landlord']),
P('job-marketplace','Recruitment',['job search','job detail','application flow','saved jobs'],['jobs','career']),
P('recruiter-ats','Recruitment',['candidate pipeline','job requisitions','interviews','offer status'],['recruiter','ats','candidate']),
P('freelance-marketplace','Marketplace',['project discovery','proposal/bid','messages','milestones/payment'],['freelance','gig']),
P('professional-network','Social',['professional feed','profile/resume','connections','jobs/messages'],['professional network','linkedin']),
P('dating-discovery','Social',['profile cards','match actions','chat','safety controls'],['dating','match']),
P('local-community','Community',['neighbourhood feed','local alerts','events','trusted profiles'],['local community','neighborhood']),
P('forum-qna','Community',['topic feed','question detail','answers/votes','follow/save'],['forum','q&a','questions']),
P('sports-scores','Sports',['live score cards','league/team tabs','match detail','alerts'],['sports','scores']),
P('fantasy-sports','Sports',['team lineup','player market','live scoring','league ranking'],['fantasy','sports']),
P('gaming-platform','Games',['game discovery','friends/social','avatar/profile','in-game economy entry'],['roblox','games platform']),
P('battle-royale-lobby','Games',['season lobby','squad entry','missions/rewards','loadout'],['battle royale','pubg','free fire']),
P('moba-lobby','Games',['hero roster','matchmaking','rank/rewards','events'],['moba','mobile legends']),
P('casual-puzzle','Games',['instant play','level map','daily challenge','reward loop'],['puzzle','block blast']),
P('endless-runner','Games',['one-tap start','run HUD','mission progression','character unlocks'],['runner','subway surfers']),
P('sports-game-hub','Games',['team selection','match modes','squad management','events'],['football game','efootball']),
P('simulation-tycoon','Games',['resource dashboard','build/upgrade','quests','offline progress'],['tycoon','simulation']),
P('survival-strategy','Games',['base status','world map','missions','alliance'],['survival','strategy']),
P('kids-world-play','Games',['world map','character creator','open-ended rooms','safe play'],['toca','kids game']),
P('restaurant-ops','Business',['orders board','table status','kitchen queue','daily metrics'],['restaurant operations','kitchen']),
P('field-service','Business',['job queue','map/dispatch','job detail','proof/completion'],['field service','jobs']),
P('inventory-ops','Business',['stock overview','scan/search','purchase orders','low-stock alerts'],['inventory','stock']),
P('crm-sales','Business',['pipeline board','account detail','tasks','forecast'],['crm','sales']),
P('analytics-executive','Business',['KPI cards','trend charts','drill-down','alerts'],['analytics','dashboard']),
P('booking-service','Business',['service catalogue','availability','booking','staff schedule'],['booking','service business']),
P('membership-portal','Business',['member home','resources','events','profile/billing'],['member portal','membership']),
P('customer-support','Business',['ticket inbox','conversation detail','knowledge base','SLA/status'],['support','helpdesk']),
P('workflow-automation','Business',['trigger/action builder','run history','templates','error recovery'],['automation','workflow']),
P('developer-console','Developer',['project list','environment/config','logs','usage'],['developer','api','console']),
P('cybersecurity-dashboard','Security',['risk posture','alerts','incident detail','remediation actions'],['security','cybersecurity']),
P('smart-home-control','IoT',['home/room cards','device controls','scenes','automation'],['smart home','iot']),
P('energy-monitor','Energy',['live consumption','device/source breakdown','cost trend','alerts'],['energy','solar','electricity']),
P('vehicle-companion','Automotive',['vehicle status','remote actions','service timeline','trip insights'],['vehicle app','car app']),
P('pet-care','Lifestyle',['pet profiles','care schedule','booking','health records'],['pet','vet']),
P('beauty-booking','Lifestyle',['service/provider discovery','portfolio','booking','loyalty'],['beauty','salon','spa']),
P('home-services-marketplace','Lifestyle',['service categories','provider cards','quote/booking','job tracking'],['home service','cleaning','repair']),
P('wedding-planner','Lifestyle',['timeline/checklist','vendor directory','budget','guest list'],['wedding']),
P('event-planner','Lifestyle',['event dashboard','guest/ticket','vendors','run-of-show'],['event planner']),
P('photo-gallery-client','Creative business',['album gallery','favorites','proofing/comments','download/order'],['photography','gallery']),
]);

if(TRENDING_APP_REFERENCE_PATTERNS.length!==100)throw new Error(`Trending reference pattern count drifted: ${TRENDING_APP_REFERENCE_PATTERNS.length}`);

function normalize(value){return String(value||'').toLowerCase().slice(0,12000)}
export function selectTrendingAppReferences(input,{limit=5}={}){
  const text=normalize(input);const scored=TRENDING_APP_REFERENCE_PATTERNS.map((ref,index)=>({ref,index,score:ref.signals.reduce((n,s)=>n+(text.includes(s)?Math.max(1,s.length/4):0),0)}));
  const hits=scored.filter(x=>x.score>0).sort((a,b)=>b.score-a.score||a.index-b.index).map(x=>x.ref);
  const fallback=TRENDING_APP_REFERENCE_PATTERNS.filter(ref=>!hits.includes(ref));
  return [...hits,...fallback].slice(0,Math.max(1,Math.min(Number(limit)||5,8)));
}

export function buildTrendingReferenceContext(input){
  const refs=selectTrendingAppReferences(input,{limit:5});
  return ['LANERIQ AI Trending App Reference Layer:',...refs.map(r=>`- ${r.family}: ${r.patterns.join(', ')}`),'Use these only as abstract product/interaction references. Never reproduce third-party branding, exact layouts, copy, assets, source code or distinctive trade dress.'].join('\n');
}
