// Soolen isolated Sandbox Runtime. Deploy separately from AI App Builder.
import http from "node:http";import crypto from "node:crypto";import {createExecutor,dependencySecurity,productionGate} from "./executor.js";import {createHttpExecutorBackend} from "./backend-http.js";import {verifyWorkspacePrivacy} from "./privacy-verifier.js";
const PORT=Number(process.env.PORT||8787),TOKEN=String(process.env.SOOLEN_SANDBOX_RUNTIME_TOKEN||"");const workspaces=new Map();const executor=createExecutor(createHttpExecutorBackend());
function send(res,status,data){const raw=JSON.stringify(data);res.writeHead(status,{"content-type":"application/json","cache-control":"no-store","x-content-type-options":"nosniff","content-security-policy":"default-src 'none'"});res.end(raw.length>2_000_000?JSON.stringify({error:"RESPONSE_TOO_LARGE"}):raw);}
function auth(req){return Boolean(TOKEN)&&req.headers.authorization===`Bearer ${TOKEN}`;}async function body(req){let raw="";for await(const c of req){raw+=c;if(raw.length>2_000_000)throw new Error("BODY_TOO_LARGE");}return JSON.parse(raw||"{}");}
function clamp(v,d,max,min=1){const n=Number(v);return Number.isFinite(n)?Math.max(min,Math.min(n,max)):d;}function policy(p={}){return {network:"deny",filesystem:"ephemeral-workspace-only",secrets:"none",maxBuildMs:clamp(p.maxBuildMs,120000,120000,1000),maxTestMs:clamp(p.maxTestMs,60000,60000,1000),maxMemoryMB:clamp(p.maxMemoryMB,768,1024,128)};}
function resultShape(r,kind){const errors=[];if(!r||typeof r!=="object")errors.push(`${kind}-result-not-object`);if(r?.passed!==true&&r?.passed!==false&&r?.passed!==null)errors.push(`${kind}-passed-invalid`);if(typeof r?.status!=="string"||!r.status)errors.push(`${kind}-status-missing`);if(r?.errors&&!Array.isArray(r.errors))errors.push(`${kind}-errors-invalid`);return {passed:errors.length===0,errors};}
function testShape(r,plan={}){const base=resultShape(r,"test"),required=Array.isArray(plan.checks)?plan.checks.filter(x=>x?.required!==false):[];if(!required.length)base.errors.push("runtime-plan-empty");const checks=Array.isArray(r?.checks)?r.checks:Array.isArray(r?.results)?r.results:[];const byId=new Map(checks.filter(x=>x?.id).map(x=>[x.id,x]));for(const c of required)if(byId.get(c.id)?.passed!==true)base.errors.push(`required-check-not-passed:${c.id}`);base.passed=base.errors.length===0;return base;}
function purge(){const cutoff=Date.now()-30*60*1000;for(const [id,ws] of workspaces)if(ws.createdAt<cutoff)workspaces.delete(id);}setInterval(purge,5*60*1000).unref?.();
const server=http.createServer(async(req,res)=>{try{if(!auth(req))return send(res,401,{error:"UNAUTHORIZED"});if(req.method!=="POST")return send(res,405,{error:"POST_ONLY"});const b=await body(req);if(req.url==="/v1/workspaces"){purge();if(workspaces.size>=100)return send(res,429,{error:"WORKSPACE_LIMIT"});const security=dependencySecurity(b.specification||{});if(!security.passed)return send(res,400,{error:"DEPENDENCY_SECURITY_BLOCK",blocked:security.blocked});const id=crypto.randomUUID(),ws={id,specification:b.specification||{},policy:policy(b.policy),createdAt:Date.now(),security};ws.privacy=verifyWorkspacePrivacy(ws);if(!ws.privacy.passed)return send(res,400,{error:"PRIVACY_BLOCK",findings:ws.privacy.findings});workspaces.set(id,ws);return send(res,200,{id});}const ws=workspaces.get(String(b.workspaceId||""));if(!ws)return send(res,404,{error:"WORKSPACE_NOT_FOUND"});if(req.url==="/v1/build"){const result=await executor.build(ws),shape=resultShape(result,"build");ws.build=shape.passed?result:{passed:false,status:"invalid-build-result",errors:shape.errors};return send(res,200,ws.build);}if(req.url==="/v1/test"){if(ws.build?.passed!==true)return send(res,409,{passed:false,status:"build-not-verified",errors:["Browser tests require a verified build"]});const plan=b.plan||{},result=await executor.test(ws,plan),shape=testShape(result,plan);ws.runtime=shape.passed&&result?.passed===true?result:{...result,passed:false,status:shape.passed?String(result?.status||"tests-failed"):"invalid-test-result",errors:[...(Array.isArray(result?.errors)?result.errors:[]),...shape.errors]};ws.privacy=verifyWorkspacePrivacy(ws);const gate=productionGate({build:ws.build,runtime:ws.runtime,security:ws.security,privacy:ws.privacy});return send(res,200,{...ws.runtime,privacy:ws.privacy,productionGate:gate});}if(req.url==="/v1/cleanup"){workspaces.delete(ws.id);return send(res,200,{cleaned:true});}return send(res,404,{error:"NOT_FOUND"});}catch(e){const code=String(e?.message||"SANDBOX_ERROR");return send(res,code==="BODY_TOO_LARGE"?413:500,{error:code==="BODY_TOO_LARGE"?code:"SANDBOX_ERROR"});}});server.listen(PORT,()=>console.log(`Soolen Sandbox Runtime listening on ${PORT}`));
