export const PRODUCT_POLICY = Object.freeze({
  product: "LANERIQ AI",
  platformRelease: {
    productionPromotionHold: true,
    previewValidationFirst: true,
    explicitApprovalRequiredBeforeProduction: true,
    note: "Production promotion is intentionally held. Product, code, security, reliability and Preview readiness can continue to 100 without automatically promoting the platform to Production.",
  },
  data: {
    customerDataOwnership: "customer",
    useUploadedDataForModelTraining: false,
    uploadedDataPurpose: "app_creation_reference_only",
    crossCustomerDataUse: false,
  },
  access: {
    multiDevice: true,
    simultaneousPhoneComputerUse: true,
    deviceCountDoesNotCreateEnterprise: true,
    memberCountAloneDoesNotCreateEnterprise: true,
    organizationBasedBusinessAccess: true,
  },
  ai: {
    providerIdentityInternalOnly: true,
    providerVisibleToCustomers: false,
    freeProvidersPreferred: true,
    automaticFallback: true,
    proactiveQuotaSwitch: true,
  },
  visualDesign: {
    premiumVisualBenchmark: "polished_released_mobile_product",
    customerColorChoiceAuthoritative: true,
    wholeSystemColorCoordination: true,
    autoThemeWhenNoPreference: true,
    originalCompositionPerProject: true,
    referenceIntentNotAssetCopy: true,
    stepWallpapersRandomByDefault: true,
    customerCanSelectWallpaper: true,
    customerCanChangeWallpaperLater: true,
    wallpaperChoicesAreAiDesigned: true,
    visualChangesMustPreserveLogicAndPrivacyByDefault: true,
  },
  promotion: {
    freeFirstProject: {
      enabled: true,
      purpose: "customer_acquisition_and_product_trial",
      projectsPerEligibleCustomer: 1,
      includesAppAndWebsiteGeneration: true,
      includesReasonableAiModificationUntilReady: true,
      includesPreviewAndQualityChecks: true,
      includesPublishingWorkflow: true,
      endsWhenProjectIsPublished: true,
      fairUseApplies: true,
      externalStoreFeesExcluded: true,
      buyoutLicenseOptionAvailable: false,
      note: "Eligible customers can create one App + Website project, refine it with AI until it fits their needs, and complete the LANERIQ AI publishing workflow without a LANERIQ AI creation charge. Apple/Google developer fees and other third-party charges remain payable directly to those providers. LANERIQ AI does not offer a buyout license for App, Website or Game projects."
    }
  },
  pricing: {
    philosophy: "fair_price_fair_use_creator_first",
    fairPriceFairUse: {
      customerFacingName: "Fair Price · Fair Use",
      creatorFirst: true,
      principles: [
        "Encourage customers to keep creating; normal genuine use should feel generous.",
        "Do not degrade ordinary product quality to force an upgrade.",
        "Use temporary safeguards only when unusually heavy or automated usage risks shared reliability.",
        "A Game Creator cooldown never blocks ordinary App, Website or other normal LANERIQ AI features.",
        "When a cooldown ends, Game creation becomes available again automatically without a manual unlock.",
        "Do not create surprise per-click charges.",
        "If an optional paid upgrade exists, explain the price and added access before the customer chooses it.",
        "Preserve customer projects and ownership during any temporary usage safeguard.",
      ],
      implementationModel: "included_access_first_progressive_game_cooldown_then_creator_choice",
      note: "This is LANERIQ AI's own customer policy and should not be presented as an OpenAI endorsement or official OpenAI policy name.",
    },
    standard: {
      priceUsd: 10,
      billing: "one_time",
      existingUserConditionsUnchanged: true,
      qualityParityWithProfessional: true,
      description: "One-time Standard creation access with the same premium design, stability, security and privacy quality floor after the free first-project promotion or when otherwise applicable.",
    },
    professional: {
      priceUsd: 68,
      billing: "one_time_for_12_months",
      accessDays: 365,
      autoRenew: false,
      qualityParityWithStandard: true,
      addsDeeperControlNotBasicQuality: true,
      gameAccessPlan: "professional",
      progressiveGameCooldowns: true,
      gameCooldownMinutes: [30, 60, 120, 240, 480],
      maximumGameCooldownHours: 8,
      cooldownResetsAfterQuietDays: 7,
      ordinaryFeaturesRemainAvailableDuringGameCooldown: true,
      description: "One payment for 12 months of Professional tools, AI Copilot and deeper project control. Game creation is included under creator-first Fair Use; unusually heavy repeated Game starts can trigger a temporary 30-minute to 8-hour Game-only cooldown, after which Game creation automatically resumes. App, Website and ordinary features remain available throughout.",
    },
    fullAccess: {
      priceUsd: 199,
      billing: "one_time_for_12_months",
      accessDays: 365,
      autoRenew: false,
      gameAccessPlan: "full",
      includesProfessional: true,
      highestIncludedGameCreatorAccess: true,
      ordinaryGameCooldownExempt: true,
      safetyAndAbuseProtectionStillApplies: true,
      qualityParityWithProfessional: true,
      description: "Full Access is designed for high-volume creators. It includes Professional features and removes the ordinary progressive Game Creator cooldown. Security, automated-abuse and infrastructure-protection safeguards still apply.",
    },
    reviewPolicy: {
      reviewIntervalYears: 3,
      reviewDoesNotRequireIncrease: true,
      increaseIsOptional: true,
      mayKeepPriceUnchanged: true,
      fairPricePrincipleApplies: true,
      noAutomaticInflationIncrease: true,
      description: "Pricing may be reviewed once every three years. A review does not mean prices must increase; prices may remain unchanged when the existing price is still fair and sustainable.",
    },
    fairUse: {
      enabled: true,
      principle: "LANERIQ AI encourages creation. Normal genuine customer use should feel generous. Temporary Game-only limits protect service reliability from unusually heavy or automated usage without locking ordinary App, Website or other normal features.",
      includedUsageFirst: true,
      optionalExtraUsageOnlyWhereSupported: true,
      noSurprisePerClickCharges: true,
      transparentBeforePaidOverage: true,
      preserveCustomerProjectsAfterProExpiry: true,
      proExpiryRemovesAdvancedServiceAccessNotOwnership: true,
      adaptiveComputeAndProviderRouting: true,
      abuseProtectionRequired: true,
      credentialSharingRestricted: true,
      resaleRestricted: true,
      automatedExtractionAbuseRestricted: true,
      temporaryProtectionLimitsAllowed: true,
      progressiveGameCooldownMinutes: [30, 60, 120, 240, 480],
      gameCooldownMaximumHours: 8,
      gameCooldownOnlyAffectsGameCreation: true,
      ordinaryFeaturesRemainAvailable: true,
      gameCooldownAutomaticallyExpires: true,
      gameCooldownLevelResetsAfterQuietDays: 7,
      fullAccessOrdinaryGameCooldownExempt: true,
    },
  },
  publishing: {
    aiAutoFillStoreForms: true,
    customerAnswersOnlyKeyQuestions: true,
    customerMustReviewBeforeSubmission: true,
    storeApprovalCannotBeGuaranteed: true,
    externalStoreFees: {
      chargedByAiAppBuilder: false,
      collectedByAiAppBuilder: false,
      appleDeveloperProgram: {
        payer: "customer_direct_to_apple",
        currentReferenceUsd: 99,
        cadence: "annual",
        officialEnrollmentUrl: "https://developer.apple.com/programs/enroll/",
      },
      googlePlayDeveloper: {
        payer: "customer_direct_to_google",
        currentReferenceUsd: 25,
        cadence: "one_time",
        officialRegistrationUrl: "https://play.google.com/console/signup",
      },
      note: "Store fees are external platform fees and may vary by region or change over time. LANERIQ AI must not mark them up or collect them on behalf of Apple or Google.",
    },
  },
  monetization: {
    commercialAppCreatorDefinition: "professional_app_creation_and_operation",
    revenueShareOption: {
      enabled: true,
      ratePercent: 5,
      appliesTo: "app_revenue_only",
      excludesCustomerProductOrServiceTransactions: true,
    },
    gameCommercialization: {
      professionalOnly: true,
      buyoutLicenseAvailable: false,
      platformSalesSharePercent: 5,
      salesShareBasis: "gross_game_sales_revenue_excluding_taxes_refunds_chargebacks",
      appliesTo: "laneriq_ai_generated_games",
      appliesAcrossAllSalesChannels: true,
      includedSalesChannels: ["laneriq_ai", "apple_app_store", "google_play", "steam", "epic", "console_stores", "independent_website", "direct_sales", "other_marketplaces"],
      platformAndStoreCommissionsDoNotReduceShareBasis: true,
      continuesAfterProfessionalAccessEnds: true,
      cannotBeRemovedByBuyout: true,
      customerGameOwnershipPreserved: true,
      legalSalesReportingDefinitionRequiredBeforeProduction: true,
      note: "LANERIQ AI-generated games are Pro-only and remain owned by the customer. No game buyout license is offered. When a generated game is sold commercially, LANERIQ AI receives a continuing 5% share of game sales revenue across every sales channel, including outside LANERIQ AI. The sales-share basis excludes separately stated taxes, refunds and chargebacks; platform/store commissions and the creator's operating costs do not reduce the 5% basis. Production legal terms must define reporting and payment timing clearly before launch."
    },
    referral: {
      enabled: true,
      rewardType: "ai_app_credits",
      cashPayout: false,
      transferable: false,
      cryptoExchange: false,
      externalUse: false,
      platformOnly: true,
      allowedUses: ["create_app", "modify_app", "ai_processing", "premium_creation_tools"],
      doesNotChangeRevenueShare: true,
      doesNotCreateBuyoutLicenseOption: true,
      antiFraudRequired: true,
    },
    buyoutLicense: {
      enabled: false,
      customerFacingOption: false,
      purchasable: false,
      newEntitlementCreationEnabled: false,
      appliesToProjectTypes: [],
      availableBeforePublish: false,
      availableAfterPublish: false,
      revenueShareRemovalAvailable: false,
      customQuoteAvailable: false,
      personalPriceUsd: null,
      businessPriceUsd: null,
      enterprisePriceUsd: null,
      sourceCodeAccessByBuyout: false,
      newBuyoutSourceFolderCreation: false,
      legacyEntitlementsMayBeHonored: true,
      note: "LANERIQ AI does not offer a buyout license option for App, Website, Game or Enterprise projects. No one-time buyout payment can remove an otherwise applicable continuing revenue-share obligation."
    },
  },
  coreFlow: ["create", "modify", "preview", "test", "publish", "rollback"],
  userGuideLanguages: ["en", "zh-CN"],
});

export const NO_BUYOUT_LICENSE_POLICY = Object.freeze({
  enabled: false,
  customerFacingOption: false,
  purchasable: false,
  newEntitlementCreationEnabled: false,
  appliesToProjectTypes: [],
  availableBeforePublish: false,
  availableAfterPublish: false,
  revenueShareRemovalAvailable: false,
  customQuoteAvailable: false,
  personalPriceUsd: null,
  businessPriceUsd: null,
  enterprisePriceUsd: null,
  sourceCodeAccessByBuyout: false,
  newBuyoutSourceFolderCreation: false,
  legacyEntitlementsMayBeHonored: true,
});

export const REFERRAL_CREDIT_POLICY = Object.freeze({
  rewardType: "ai_app_credits",
  redeemableOnlyInsidePlatform: true,
  cashPayout: false,
  transferable: false,
  cryptoExchange: false,
  externalUse: false,
  allowedUses: ["create_app", "modify_app", "ai_processing", "premium_creation_tools"],
  antiFraudRequired: true,
});
