export const PRODUCT_POLICY = Object.freeze({
  product: "AI App Builder",
  data: {
    customerDataOwnership: "customer",
    useUploadedDataForModelTraining: false,
    uploadedDataPurpose: "app_creation_reference_only",
    crossCustomerDataUse: false,
  },
  access: {
    multiDevice: true,
    simultaneousPhoneComputerUse: true,
    deviceCountDoesNotCreateEnterprise: true,
    memberCountAloneDoesNotCreateEnterprise: true,
    organizationBasedBusinessAccess: true,
  },
  ai: {
    providerIdentityInternalOnly: true,
    providerVisibleToCustomers: false,
    freeProvidersPreferred: true,
    automaticFallback: true,
    proactiveQuotaSwitch: true,
  },
  pricing: {
    philosophy: "fair_price_fair_use",
    standard: {
      priceUsd: 10,
      billing: "one_time",
      existingUserConditionsUnchanged: true,
      qualityParityWithProfessional: true,
      description: "One-time Standard creation access with the same premium design, stability, security and privacy quality floor.",
    },
    professional: {
      priceUsd: 68,
      billing: "one_time_for_12_months",
      accessDays: 365,
      autoRenew: false,
      qualityParityWithStandard: true,
      addsDeeperControlNotBasicQuality: true,
      description: "One payment for 12 months of Professional tools, AI Copilot and deeper project control.",
    },
    reviewPolicy: {
      reviewIntervalYears: 3,
      reviewDoesNotRequireIncrease: true,
      increaseIsOptional: true,
      mayKeepPriceUnchanged: true,
      fairPricePrincipleApplies: true,
      noAutomaticInflationIncrease: true,
      description: "Pricing may be reviewed once every three years. A review does not mean prices must increase; prices may remain unchanged when the existing price is still fair and sustainable.",
    },
    fairUse: {
      enabled: true,
      principle: "Normal genuine customer use should feel generous. Limits exist to protect service reliability and prevent automated abuse, resale, excessive compute consumption and activity that harms other customers.",
      noSurprisePerClickCharges: true,
      transparentBeforePaidOverage: true,
      preserveCustomerProjectsAfterProExpiry: true,
      proExpiryRemovesAdvancedServiceAccessNotOwnership: true,
      adaptiveComputeAndProviderRouting: true,
      abuseProtectionRequired: true,
    },
  },
  publishing: {
    aiAutoFillStoreForms: true,
    customerAnswersOnlyKeyQuestions: true,
    customerMustReviewBeforeSubmission: true,
    storeApprovalCannotBeGuaranteed: true,
    externalStoreFees: {
      chargedByAiAppBuilder: false,
      collectedByAiAppBuilder: false,
      appleDeveloperProgram: {
        payer: "customer_direct_to_apple",
        currentReferenceUsd: 99,
        cadence: "annual",
        officialEnrollmentUrl: "https://developer.apple.com/programs/enroll/",
      },
      googlePlayDeveloper: {
        payer: "customer_direct_to_google",
        currentReferenceUsd: 25,
        cadence: "one_time",
        officialRegistrationUrl: "https://play.google.com/console/signup",
      },
      note: "Store fees are external platform fees and may vary by region or change over time. AI App Builder must not mark them up or collect them on behalf of Apple or Google.",
    },
  },
  monetization: {
    commercialAppCreatorDefinition: "professional_app_creation_and_operation",
    revenueShareOption: {
      enabled: true,
      ratePercent: 5,
      appliesTo: "app_revenue_only",
      excludesCustomerProductOrServiceTransactions: true,
    },
    referral: {
      enabled: true,
      rewardType: "ai_app_credits",
      cashPayout: false,
      transferable: false,
      cryptoExchange: false,
      externalUse: false,
      platformOnly: true,
      allowedUses: ["create_app", "modify_app", "ai_processing", "premium_creation_tools"],
      doesNotChangeRevenueShare: true,
      doesNotChangeBuyoutLicense: true,
      antiFraudRequired: true,
    },
    buyout: {
      oneAppOneLicense: true,
      personal: { priceUsd: 49 },
      business: { priceUsd: 199 },
      enterprise: { priceUsd: 499 },
      futureRevenueShareAfterBuyoutPercent: 0,
      selectionRequiredBeforePublish: true,
      unavailableAfterPublish: true,
      cannotBePurchasedAfterPublish: true,
      sourceCodeAccess: {
        enabled: true,
        storedInsideCustomerAppFolder: true,
        hiddenFolder: true,
        folderPurpose: "customer_owned_buyout_source_code",
        visibleToNonBuyoutCustomers: false,
        writableByNonBuyoutCustomers: false,
        readableByBuyoutCustomer: true,
        writableByBuyoutCustomer: true,
        accessEnforcedServerSide: true,
        uiHiddenIsNotSecurityBoundary: true,
      },
    },
  },
  coreFlow: ["create", "modify", "preview", "test", "publish", "rollback"],
  userGuideLanguages: ["en", "zh-CN"],
});

export const BUYOUT_LICENSE_POLICY = Object.freeze({
  model: "one_app_one_license",
  personalPriceUsd: 49,
  businessPriceUsd: 199,
  enterprisePriceUsd: 499,
  revenueShareAfterBuyoutPercent: 0,
  mustSelectBeforePublish: true,
  publishedAppBuyoutAvailable: false,
  sourceCodeFolder: {
    storedInsideCustomerAppFolder: true,
    hiddenFolder: true,
    buyoutCustomerCanRead: true,
    buyoutCustomerCanWrite: true,
    nonBuyoutCustomerCanRead: false,
    nonBuyoutCustomerCanWrite: false,
    serverSideAccessControlRequired: true,
  },
});

export const REFERRAL_CREDIT_POLICY = Object.freeze({
  rewardType: "ai_app_credits",
  redeemableOnlyInsidePlatform: true,
  cashPayout: false,
  transferable: false,
  cryptoExchange: false,
  externalUse: false,
  allowedUses: ["create_app", "modify_app", "ai_processing", "premium_creation_tools"],
  antiFraudRequired: true,
});
