"use client";
import { useState } from "react";

export default function ImageStudio() {
  const [prompt, setPrompt] = useState("");
  const [image, setImage] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  async function generate() {
    if (!prompt.trim()) return;
    setLoading(true); setError(""); setImage("");
    try {
      const r = await fetch("/api/images/generate", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({ prompt:prompt.trim(), size:"1024x1024", quality:"auto", background:"auto", output_format:"png" }) });
      const d = await r.json();
      if (!r.ok) throw new Error(d?.error || d?.detail || "Image generation failed.");
      setImage(d.image);
    } catch (e) { setError(e?.message || "Unable to create image."); }
    finally { setLoading(false); }
  }

  return <main className="studio"><div className="card"><div className="eyebrow">SOOLEN AI • IMAGE STUDIO</div><h1>Create original visuals for your app.</h1><p>Soolen AI can turn your app idea into original hero artwork, illustrations, backgrounds, icons and marketing visuals.</p><textarea value={prompt} onChange={(e)=>setPrompt(e.target.value)} placeholder="Example: A premium real estate app hero image, modern Kuala Lumpur skyline at sunset, elegant green and gold palette, clean editorial style, no text." rows={5}/><button onClick={generate} disabled={loading || !prompt.trim()}>{loading ? "Creating image…" : "✨ Create Image"}</button>{error && <div className="error">{error}</div>}{image && <div className="result"><img src={image} alt="Generated by Soolen AI"/><a href={image} download="soolen-ai-image.png">Save Image</a></div>}</div><style jsx>{`.studio{min-height:100vh;padding:42px 18px;background:linear-gradient(160deg,#06251f,#0e4a3b 55%,#071713);color:#f7fff9}.card{max-width:760px;margin:0 auto;padding:30px;border:1px solid #d8bf6233;border-radius:28px;background:#061b16dd;box-shadow:0 25px 80px #0006}.eyebrow{font-size:11px;letter-spacing:.2em;color:#d8bf62;font-weight:900}.card h1{font-size:40px;line-height:1.05;margin:12px 0}.card p{color:#a5bdb4;line-height:1.6}.card textarea{width:100%;margin-top:16px;padding:15px;border-radius:15px;border:1px solid #ffffff18;background:#02100d;color:#fff;resize:vertical;font:inherit}.card button,.result a{display:inline-flex;margin-top:12px;padding:13px 18px;border:0;border-radius:13px;background:#d8bf62;color:#08140f;font-weight:900;text-decoration:none;cursor:pointer}.card button:disabled{opacity:.5}.error{margin-top:12px;color:#ffb8b8}.result{margin-top:22px;display:grid;gap:12px}.result img{width:100%;border-radius:20px;display:block}`}</style></main>;
}
