"use client";

import {useMemo,useState} from "react";
import Link from "next/link";
import {
  createReproBundle,minimizeFailureTrace,isolateRootCauses,synthesizeRegressionSuite,
  classifyReleaseRisk,proposeReviewGatedPatchPlan,buildSyntheticDeviceMatrix,
  validateSaveMigrationRegression,runAutonomousDevelopmentCycle
} from "../../lib/game/autonomous-game-development-agent-v3.js";

const TABS=["Repro + Minimize","Root Cause","Regression + Patch","Release Triage","Device + Save","Full Development Cycle"];
const bugActions=["spawn","walk","pickup_key","open_gate","dash","dash","enter_boss"];
const stillFails=actions=>actions.includes("open_gate")&&actions.filter(a=>a==="dash").length>=2;

export default function GameDevelopmentLab(){
  const[tab,setTab]=useState(TABS[0]);
  return <main className="shell"><div className="bg"/><header><Link href="/game-builder">← GAME BUILDER</Link><span>SOOLENAI · AUTONOMOUS DEVELOPMENT AGENT V3</span></header>
    <section className="hero"><small>PRO · REVIEW-GATED AUTONOMOUS DEVELOPMENT</small><h1>Find the cause.<br/><em>Keep the fix reviewable.</em></h1><p>Failure repro bundles, delta minimization, root-cause isolation, regression synthesis, patch plans, release-blocker triage, synthetic device planning and save-migration regression are exercised here as bounded deterministic contracts.</p></section>
    <nav>{TABS.map(item=><button key={item} className={tab===item?"active":""} onClick={()=>setTab(item)}>{item}</button>)}</nav>
    <section className="panel">{tab===TABS[0]?<ReproLab/>:tab===TABS[1]?<CauseLab/>:tab===TABS[2]?<RegressionLab/>:tab===TABS[3]?<ReleaseLab/>:tab===TABS[4]?<DeviceSaveLab/>:<CycleLab/>}</section>
    <section className="truth"><b>Production boundary</b><span>V3 can reproduce, minimize, isolate, propose and generate regression evidence. Production auto-patching and production release authority remain disabled; human approval and real device/network evidence are still required.</span></section>
    <style jsx>{`.shell{min-height:100vh;background:#020706;color:#effaf5;font-family:Inter,system-ui;padding-bottom:72px}.bg{position:fixed;inset:0;background:radial-gradient(circle at 80% 8%,#f3d77a24,transparent 31%),linear-gradient(180deg,#020706e9,#020706fb),url('/soolen-ai-landscape.jpg') center/cover;z-index:0}header,.hero,nav,.panel,.truth{position:relative;z-index:1;width:min(1120px,calc(100% - 28px));margin:auto}header{display:flex;justify-content:space-between;padding:24px 0;font-size:10px;letter-spacing:.13em;font-weight:900}header a{color:#fff;text-decoration:none}header span,.hero small{color:#f3d77a}.hero{padding:54px 0 24px}.hero h1{font-size:clamp(48px,8vw,88px);line-height:.94;letter-spacing:-.05em;margin:10px 0}.hero em{font-style:normal;color:#f3d77a}.hero p{max-width:900px;color:#a8bbb2;line-height:1.7}nav{display:flex;gap:7px;flex-wrap:wrap;margin-bottom:12px}nav button{border:1px solid #ffffff14;background:#071a13;color:#a9bbb2;padding:9px 12px;border-radius:999px;font-weight:850;font-size:10px}nav button.active{background:#f3d77a;color:#06110d}.panel,.truth{border:1px solid #ffffff12;background:#061914e9;border-radius:24px;padding:22px;backdrop-filter:blur(16px)}.truth{margin-top:12px;display:grid;gap:5px}.truth b{color:#f3d77a}.truth span{color:#91a49b;font-size:11px;line-height:1.55}:global(.grid){display:grid;grid-template-columns:1fr 1fr;gap:12px}:global(.card){background:#0a2119;border:1px solid #ffffff10;border-radius:18px;padding:16px}:global(.card h2){font-size:21px;margin:0 0 7px}:global(.card p){font-size:11px;color:#9fb2a9;line-height:1.55}:global(.metric){font-size:30px;color:#f3d77a;font-weight:950}:global(.mono){font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:10px;white-space:pre-wrap;background:#020b08;color:#a9bbb2;border-radius:12px;padding:10px;max-height:360px;overflow:auto}@media(max-width:720px){:global(.grid){grid-template-columns:1fr}.hero{padding-top:38px}}`}</style>
  </main>;
}

function ReproLab(){const bundle=createReproBundle({id:"boss_gate_softlock",seed:"repro-01",initialState:{room:"gate",hp:100},actions:bugActions,failure:"double_dash_after_gate_causes_soft_lock"});const minimized=minimizeFailureTrace(bugActions,stillFails);return <div className="grid"><Card title="Repro Bundle" metric={bundle.trace.length+" actions"} data={bundle}/><Card title="Delta Repro Minimizer" metric={minimized.minimizedLength+" actions"} data={minimized}/></div>;}
function CauseLab(){const causes=isolateRootCauses({issues:["double_dash_after_gate_causes_soft_lock"],candidates:[{id:"movement_dash",area:"movement",prior:.6,dependencies:["state_machine"]},{id:"gate_trigger",area:"progression",prior:.5},{id:"camera",area:"camera",prior:.2}],testCandidate:c=>c.id==="movement_dash"?{resolved:1,observed:1,notes:["disabling second dash removes failure"]}:{resolved:0,observed:1}});return <div className="grid"><Card title="Root Cause Ranking" metric={causes.isolated.length?"ISOLATED":"SUSPECT"} data={causes}/><Card title="Truth Boundary" metric="EVIDENCE" data={{rule:causes.truth}}/></div>;}
function RegressionLab(){const minimized=minimizeFailureTrace(bugActions,stillFails),suite=synthesizeRegressionSuite({issueId:"boss_gate_softlock",failure:"soft_lock",seed:"repro-01",initialState:{room:"gate"},actions:minimized.actions,expectedInvariant:"player_can_reach_boss"}),patch=proposeReviewGatedPatchPlan({issue:{id:"boss_gate_softlock",type:"soft_lock",area:"movement",severity:"high"},rootCause:{area:"movement"},regressionSuite:suite});return <div className="grid"><Card title="Regression Suite" metric="PERMANENT" data={suite}/><Card title="Review-gated Patch Plan" metric={patch.autoApply?"AUTO":"REVIEW"} data={patch}/></div>;}
function ReleaseLab(){const risk=classifyReleaseRisk([{id:"save",type:"save_corruption",resolved:false},{id:"soft",type:"soft_lock",severity:"high",resolved:false},{id:"ui",type:"minor_ui",severity:"low",resolved:true}]);return <div className="grid"><Card title="Release Blocker Triage" metric={risk.canRelease?"GO":"HOLD"} data={risk}/><Card title="Release Authority" metric="HUMAN" data={{productionReleaseAuthority:risk.productionReleaseAuthority}}/></div>;}
function DeviceSaveLab(){const devices=buildSyntheticDeviceMatrix({scenario:"boss_battle"}),save=validateSaveMigrationRegression({targetVersion:3,snapshots:[{id:"v1",schemaVersion:1,data:{coins:10}},{id:"v2",schemaVersion:2,data:{coins:20,inventory:[]}}],migrate:(data,from)=>from===1?{...data,inventory:[]}:from===2?{...data,settings:{}}:data,validate:data=>Array.isArray(data.inventory)&&!!data.settings});return <div className="grid"><Card title="Synthetic Device Matrix" metric={devices.profiles.length+" tiers"} data={devices}/><Card title="Save Migration Regression" metric={save.passed?"PASS":"FIX"} data={save}/></div>;}
function CycleLab(){const cycle=useMemo(()=>runAutonomousDevelopmentCycle({issue:{id:"boss_gate_softlock",type:"soft_lock",area:"movement",severity:"high"},bundle:{id:"boss_gate_softlock",seed:"cycle",initialState:{room:"gate"},actions:bugActions,failure:"soft_lock"},fails:stillFails,candidates:[{id:"movement_dash",area:"movement",prior:.7},{id:"gate_trigger",area:"progression",prior:.4}],testCandidate:c=>c.id==="movement_dash"?{resolved:1,observed:1}:{resolved:0,observed:1},expectedInvariant:"boss_room_reachable"}),[]);return <div className="grid"><Card title="Autonomous Development Cycle" metric={cycle.readyForReviewedFix?"READY FOR REVIEW":"MORE EVIDENCE"} data={cycle}/><Card title="Safety State" metric="NO AUTO PATCH" data={{productionAutoPatch:cycle.productionAutoPatch,productionReleaseAuthority:cycle.productionReleaseAuthority}}/></div>;}
function Card({title,metric,data}){return <div className="card"><h2>{title}</h2><div className="metric">{metric}</div><div className="mono">{JSON.stringify(data,null,2)}</div></div>;}
