"use client";
import { useEffect,useState } from "react";
import Link from "next/link";

export default function AdminCreatorOpportunitiesPage(){
 const[items,setItems]=useState([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[busy,setBusy]=useState("");
 async function load(){setLoading(true);setError("");try{const r=await fetch("/api/admin/creator-opportunities",{cache:"no-store",credentials:"same-origin"});if(r.status===401){window.location.assign(`/auth?next=${encodeURIComponent("/admin/creator-opportunities")}`);return}const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to load requests.");setItems(d.requests||[])}catch(e){setError(e.message||"Unable to load requests.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function decide(id,decision){const note=window.prompt(decision==="approved"?"Optional approval note":"Reason / note for rejection")||"";setBusy(id);setError("");try{const r=await fetch("/api/admin/creator-opportunities",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({requestId:id,decision,adminNote:note})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to save decision.");await load()}catch(e){setError(e.message||"Unable to save decision.")}finally{setBusy("")}}
 const pending=items.filter(x=>x.status==="pending"),history=items.filter(x=>x.status!=="pending");
 const card=x=><article key={x.id}><div className="top"><span data-status={x.status}>{x.status.toUpperCase()}</span><small>{new Date(x.submitted_at).toLocaleString()}</small></div><h2>{x.idea_summary}</h2><h3>Commercial potential</h3><p>{x.commercial_potential}</p><div className="meta"><b>Individual only</b><b>+{Number(x.extra_platform_sales_share_percent||5)} percentage points sales share</b><code>{x.user_id}</code></div>{x.status==="pending"?<div className="actions"><button disabled={busy===x.id} onClick={()=>decide(x.id,"approved")}>Approve Full Access</button><button className="reject" disabled={busy===x.id} onClick={()=>decide(x.id,"rejected")}>Reject</button></div>:<p className="note">{x.admin_note||"No Admin note."}</p>}</article>;
 return <main className="page"><div className="wrap"><header><Link href="/admin/promo">← Admin</Link><span>LANERIQ AI · CREATOR OPPORTUNITY ADMIN</span><button onClick={load}>Refresh</button></header><section className="hero"><small>INDIVIDUAL CREATOR REVIEW</small><h1>Creator Opportunity<br/><em>Approval Queue</em></h1><p>Approve only genuine individual creators. Approval grants Full Access with no upfront LANERIQ AI access fee and records an additional 5 percentage-point platform sales share.</p></section>{error?<div className="error" role="alert">{error}</div>:null}{loading?<p>Loading…</p>:<><section className="section"><h2>Pending · {pending.length}</h2><div className="grid">{pending.length?pending.map(card):<p>No pending requests.</p>}</div></section><section className="section"><h2>History</h2><div className="grid">{history.map(card)}</div></section></>}</div><style>{`.page{min-height:100vh;background:#07110e;color:#f6fff9;padding-bottom:80px}.wrap{width:min(1100px,calc(100% - 28px));margin:auto}header{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:20px 0}header a{color:#fff;text-decoration:none}header span{font-size:11px;letter-spacing:.13em;font-weight:900}header button,.actions button{border:0;border-radius:11px;padding:10px 13px;font-weight:900}.hero{border:1px solid #e5c76738;background:linear-gradient(145deg,#14261d,#081510);border-radius:24px;padding:30px}.hero small{color:#e5c767;letter-spacing:.15em;font-weight:950}.hero h1{font-size:clamp(42px,7vw,72px);line-height:.98;margin:10px 0}.hero em{font-style:normal;color:#e5c767}.hero p{color:#aebfb7;line-height:1.65;max-width:800px}.section{margin-top:24px}.grid{display:grid;gap:12px}article{border:1px solid #ffffff14;background:#0b1c16;border-radius:20px;padding:20px}.top{display:flex;justify-content:space-between}.top span{font-size:10px;font-weight:950;letter-spacing:.1em;color:#e5c767}.top span[data-status="approved"]{color:#65e0a0}.top span[data-status="rejected"]{color:#ff9287}.top small{color:#80938a}article h2{font-size:22px;margin:13px 0}article h3{font-size:12px;color:#e5c767}article p{color:#b6c5bf;line-height:1.6}.meta{display:flex;gap:8px;flex-wrap:wrap}.meta b,.meta code{border:1px solid #ffffff12;border-radius:999px;padding:7px 9px;font-size:10px}.actions{display:flex;gap:8px;margin-top:16px}.actions button{background:#e5c767;color:#07120e}.actions .reject{background:#5c2626;color:#ffd2ce}.note{font-size:12px}.error{margin:12px 0;padding:12px;border-radius:12px;background:#642626;color:#ffd0cb}@media(max-width:640px){header span{display:none}.hero{padding:22px}.top{display:grid;gap:5px}.actions{display:grid}}`}</style></main>;
}
