import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "../../lib/supabase/server.js";

export default async function MyAppsPage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/auth");
  const { data: apps, error } = await supabase.from("apps").select("id,name,description,created_at,updated_at,visibility,publish_status").eq("owner_id", user.id).order("updated_at", { ascending: false });
  async function signOut() { "use server"; const client = await createClient(); await client.auth.signOut(); redirect("/auth"); }
  const ownerName = user.user_metadata?.full_name || user.user_metadata?.name || user.email || "Account";
  return <main className="page">
    <header><div><div className="eyebrow">LANERIQ AI</div><h1>My Projects</h1><p>Every customer App and Website is saved here automatically.</p><strong className="owner">Owner: {ownerName}</strong></div><nav><Link href="/create" className="primary">+ One-Click App + Website</Link><Link href="/studio" className="secondary">Studio</Link><form action={signOut}><button className="secondary">Sign out</button></form></nav></header>
    {error && <div className="notice">Unable to load your projects: {error.message}</div>}
    <section className="grid">{apps?.length ? apps.map(app => <article className="card" key={app.id}><div className="top"><div className="icon">✦</div><span className={app.publish_status === "published" ? "published" : "draft"}>{app.publish_status === "published" ? "App + Website Published" : "App + Website Draft"}</span></div><h2>{app.name}</h2><p>{app.description || "AI-generated customer project"}</p><div className="deliverables"><span>📱 App</span><span>🌐 Website</span></div><small>Updated {new Date(app.updated_at).toLocaleString()}</small><div className="actions"><Link href={`/app-dashboard/${app.id}`} className="primary">Project Folder →</Link><div><Link href={`/a/${app.id}?demo=1`} className="secondary">App Demo</Link><Link href={`/website/${app.id}`} className="secondary">Website</Link></div><div><Link href={`/editor/${app.id}`} className="secondary">Modify</Link><Link href={`/release/${app.id}`} className="secondary">Publish</Link></div></div></article>) : <div className="empty"><h2>No projects yet</h2><p>Name your App, add your idea and upload photos, video or sketches. SoolenAI can build the App + Website together.</p><Link href="/create" className="primary">Create your first project</Link></div>}</section>
    <style>{`.page{min-height:100vh;padding:40px 18px 80px;background:linear-gradient(145deg,#03100d,#0a2119 58%,#06140f);color:#f5fff9}.page>header,.grid{max-width:1180px;margin:auto}.page>header{display:flex;justify-content:space-between;gap:24px;align-items:flex-end;margin-bottom:30px}.eyebrow{color:#d8bf62;letter-spacing:.2em;font-size:11px;font-weight:900}.page h1{font-size:46px;margin:8px 0}.page p{color:#93aaa0;line-height:1.55}.owner{color:#b9c8c2;font-size:13px}.page nav{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.primary,.secondary{display:inline-flex;align-items:center;justify-content:center;padding:12px 16px;border-radius:12px;font-weight:800;text-decoration:none}.primary{background:#d8bf62;color:#07130e;border:0}.secondary{background:transparent;color:#d8bf62;border:1px solid rgba(216,191,98,.25)}button.secondary{font:inherit;cursor:pointer}.notice{max-width:1180px;margin:0 auto 20px;padding:14px;border:1px solid rgba(240,170,90,.35);border-radius:14px;background:rgba(100,60,20,.2)}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(300px,1fr));gap:16px}.card{padding:22px;border:1px solid rgba(255,255,255,.08);border-radius:22px;background:rgba(3,16,13,.78)}.top{display:flex;justify-content:space-between;align-items:center}.icon{width:46px;height:46px;display:grid;place-items:center;border-radius:14px;background:linear-gradient(145deg,#d8bf62,#8c7331);color:#07130e}.published{color:#79d7ac;font-size:11px;font-weight:900}.draft{color:#d8bf62;font-size:11px;font-weight:900}.card h2{margin:16px 0 8px}.card small{color:#6f867d}.deliverables{display:flex;gap:8px;margin:12px 0}.deliverables span{padding:7px 10px;border-radius:9px;background:#0d3025;color:#cbdad4;font-size:12px;font-weight:800}.actions{display:grid;gap:8px;margin-top:18px}.actions>div{display:grid;grid-template-columns:1fr 1fr;gap:8px}.empty{grid-column:1/-1;text-align:center;padding:70px 20px;border:1px dashed rgba(216,191,98,.2);border-radius:22px}@media(max-width:700px){.page>header{flex-direction:column;align-items:stretch}.page h1{font-size:38px}.page nav{flex-wrap:wrap}}`}</style>
  </main>;
}
