import { NextResponse } from "next/server";
import { createClient } from "../../../../lib/supabase/server.js";
import { generateExternalImages,getImageGenerationConfig,ImageGenerationGatewayError } from "../../../../lib/ai/image-generation-gateway.js";
import { buildImagePlacementPrompt,getImagePlacementPolicy } from "../../../../lib/ai/image-placement-policy.js";
import { consumeAiCredits,refundAiCredits } from "../../../../lib/app-builder-finance.js";

const MAX_REQUEST_BYTES=24*1024;
const REQUEST_ID=/^[A-Za-z0-9._:-]{1,160}$/;
const TYPES=new Set(["profile","game","npc","presenter","mascot"]);
const STYLES=new Set(["cinematic","3d","cartoon","fantasy","minimal","realistic"]);
const LIKENESS_MODES=new Set(["fictional","self","consented_person"]);
const AVATAR_MODEL_CREDIT_COST=Math.max(1,Number(process.env.AVATAR_GENERATE_CREDIT_COST||2));
function noStore(payload,status=200){return NextResponse.json(payload,{status,headers:{"Cache-Control":"private, no-store, max-age=0","Pragma":"no-cache","X-Content-Type-Options":"nosniff"}});}
function clean(value,max){return String(value||"").replace(/[\u0000-\u001f\u007f]/g," ").trim().slice(0,max);}
function typeLabel(type){return({profile:"profile avatar",game:"game character",npc:"NPC concept",presenter:"AI presenter",mascot:"mascot"})[type]||"avatar";}
function localAvatarSvg({type,style,variation=0}){const palettes=[['#071b16','#d8bf62','#1f5d49'],['#081427','#66b9db','#d7c36b'],['#241026','#e3a2d8','#8a6ed1']];const[bg,accent,secondary]=palettes[variation%palettes.length];const round=type==="mascot"?150:90;const head=type==="mascot"?180:150;const body=type==="game"||type==="npc"?`<path d="M270 760 Q315 520 512 520 Q709 520 754 760 L700 900 H324Z" fill="${secondary}"/><path d="M360 650 L280 800 L350 840 L430 690Z" fill="${accent}"/><path d="M664 650 L744 800 L674 840 L594 690Z" fill="${accent}"/>`:`<path d="M282 820 Q325 560 512 560 Q699 560 742 820Z" fill="${secondary}"/>`;return`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024"><defs><radialGradient id="g"><stop stop-color="${accent}" stop-opacity=".28"/><stop offset="1" stop-color="${bg}" stop-opacity="0"/></radialGradient></defs><rect width="1024" height="1024" rx="${round}" fill="${bg}"/><circle cx="780" cy="230" r="340" fill="url(#g)"/>${body}<circle cx="512" cy="390" r="${head}" fill="#d9b39b"/><path d="M365 390 Q390 205 520 225 Q665 235 668 410 Q610 325 505 320 Q430 320 365 390Z" fill="#17221e"/><circle cx="458" cy="405" r="13" fill="#111"/><circle cx="566" cy="405" r="13" fill="#111"/><path d="M465 475 Q512 505 559 475" fill="none" stroke="#7d5146" stroke-width="12" stroke-linecap="round"/><circle cx="512" cy="512" r="430" fill="none" stroke="${accent}" stroke-opacity=".22" stroke-width="8"/><text x="512" y="950" text-anchor="middle" fill="${accent}" font-family="Arial,sans-serif" font-size="28" font-weight="700">ORIGINAL ${style.toUpperCase()} CONCEPT</text></svg>`;}

export async function POST(request){
  let userId=null,requestId="",charged=false;
  try{
    const contentLength=Number(request.headers.get("content-length")||0);if(contentLength>MAX_REQUEST_BYTES)return noStore({error:"Avatar request is too large."},413);
    const supabase=await createClient();const{data:{user},error:userError}=await supabase.auth.getUser();if(userError||!user)return noStore({error:"Authentication required."},401);userId=user.id;if(!user.confirmed_at&&!user.email_confirmed_at&&!user.phone_confirmed_at)return noStore({error:"Account verification is required."},403);
    const body=await request.json().catch(()=>null);if(!body)return noStore({error:"Invalid avatar request."},400);if(Buffer.byteLength(JSON.stringify(body),"utf8")>MAX_REQUEST_BYTES)return noStore({error:"Avatar request is too large."},413);
    requestId=clean(body?.requestId,160);if(!REQUEST_ID.test(requestId))return noStore({error:"A stable avatar request ID is required."},400);
    const idea=clean(body?.idea,1200);if(!idea)return noStore({error:"Describe the avatar or character you want first."},400);
    const type=TYPES.has(body?.type)?body.type:"profile",style=STYLES.has(body?.style)?body.style:"cinematic",likenessMode=LIKENESS_MODES.has(body?.likenessMode)?body.likenessMode:"fictional",consentConfirmed=Boolean(body?.consentConfirmed);
    if(likenessMode!=="fictional"&&!consentConfirmed)return noStore({error:"Confirm that you have permission to create this real-person likeness."},400);
    const label=typeLabel(type),placement=getImagePlacementPolicy("image");const likenessRule=likenessMode==="fictional"?"Create a wholly fictional, original person or character. Do not imitate a celebrity, public figure, copyrighted character or third-party mascot.":likenessMode==="self"?"The customer declares this is a description of themself and consents to generating their likeness. Do not infer sensitive personal attributes or identity facts beyond the supplied description.":"The customer declares the described real person gave permission for this likeness. Do not infer sensitive personal attributes or identity facts beyond the supplied description.";
    const prompt=buildImagePlacementPrompt(`Create an original ${label} for an App, Website or Mobile Game. Style direction: ${style}. Customer description: ${idea}. ${likenessRule} Keep the composition clean, mobile-safe and suitable for profile, character or promotional use. Do not add logos, trademarks or text.`,"image");
    const gateway=getImageGenerationConfig();let modelFailureCode=null;
    if(gateway.configured){
      try{
        const charge=await consumeAiCredits(user.id,{amount:AVATAR_MODEL_CREDIT_COST,requestId,description:"AI avatar generation",metadata:{operation:"avatar_generate",type,style,likenessMode}});charged=Boolean(charge?.charged);
        const generated=await generateExternalImages({prompt,mode:"image",style,palette:"auto",count:1,colors:{}});if(generated.generated&&generated.images.length){const images=generated.images.slice(0,1).map((item,index)=>({...item,id:item.id||`avatar-${index+1}`,source:"model",type,style,placement}));return noStore({success:true,images,image:images[0].image,source:"model",type,style,likeness:{mode:likenessMode,consentConfirmed:likenessMode==="fictional"?null:true,rawReferenceStored:false},credits:{charged:charged?AVATAR_MODEL_CREDIT_COST:0,requestId,balance:charge?.balance??null},note:"Original avatar output is ready. Provider identity and credentials remain server-side."});}
      }catch(error){modelFailureCode=error?.code||"AVATAR_MODEL_FAILED";if(charged){try{await refundAiCredits(user.id,{requestId,amount:AVATAR_MODEL_CREDIT_COST,description:"AI avatar generation failed - automatic refund",metadata:{operation:"avatar_generate"}})}catch{}charged=false;}if(error instanceof ImageGenerationGatewayError&&error.code==="IMAGE_GENERATION_COST_POLICY_BLOCKED")modelFailureCode=error.code;}
    }
    const svg=localAvatarSvg({type,style});const image=`data:image/svg+xml;charset=UTF-8,${encodeURIComponent(svg)}`;return noStore({success:true,images:[{id:"avatar-local-1",image,source:"local",type,style,placement}],image,source:"local",type,style,likeness:{mode:likenessMode,consentConfirmed:likenessMode==="fictional"?null:true,rawReferenceStored:false},credits:{charged:0,requestId},modelFallback:Boolean(modelFailureCode),note:modelFailureCode?"The connected model did not produce an approved result, so the request was refunded and an explicitly labeled local concept was returned.":"No approved external avatar model is active, so LANERIQ AI returned an explicitly labeled local concept instead of claiming model output."});
  }catch(error){console.error("AVATAR_GENERATION_ERROR",error?.code||error?.name||"unknown");if(charged&&userId&&requestId){try{await refundAiCredits(userId,{requestId,amount:AVATAR_MODEL_CREDIT_COST,description:"AI avatar generation failed - automatic refund",metadata:{operation:"avatar_generate"}})}catch{}}const message=String(error?.message||"");if(/insufficient credits/i.test(message))return noStore({error:"Insufficient credits.",requiredCredits:AVATAR_MODEL_CREDIT_COST},402);return noStore({error:"Unable to create the avatar concept right now."},500);}
}
