const AUTH_SHA256 = "4badb9a7d10de65dab7667fed8ebc92cca2108b96a877e61444172a275f50ed9";
const OPS = new Set(["project.read","project.write","context.read","context.write","artifact.meta"]);
const ID = /^[A-Za-z0-9._:-]{1,160}$/;
const MAX_BYTES = 128 * 1024;

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: {"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"},
  });
}
function safeEqualHex(a:string,b:string){if(a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i++)diff|=a.charCodeAt(i)^b.charCodeAt(i);return diff===0;}
async function sha256Hex(value:string){const bytes=new TextEncoder().encode(value);const digest=new Uint8Array(await crypto.subtle.digest("SHA-256",bytes));return Array.from(digest,b=>b.toString(16).padStart(2,"0")).join("");}
async function authorized(req:Request){const header=req.headers.get("authorization")||"";if(!header.startsWith("Bearer "))return false;const token=header.slice(7).trim();return token.length>=32&&safeEqualHex(await sha256Hex(token),AUTH_SHA256);}
function text(value:unknown,max=2000){return String(value??"").trim().slice(0,max);}
function validate(input:any){const operation=text(input?.operation,40);if(!OPS.has(operation))return{ok:false,error:"INVALID_OPERATION"} as const;const requestId=text(input?.requestId,160),tenantId=text(input?.tenantId,160),userId=text(input?.userId,160),projectId=text(input?.projectId,160);if(![requestId,tenantId,userId,projectId].every(v=>ID.test(v)))return{ok:false,error:"INVALID_SCOPE_IDENTITY"} as const;const payload=input?.payload&&typeof input.payload==="object"&&!Array.isArray(input.payload)?input.payload:{};const serialized=JSON.stringify(payload);if(new TextEncoder().encode(serialized).byteLength>MAX_BYTES)return{ok:false,error:"PAYLOAD_TOO_LARGE"} as const;if(/(?:token|api[_-]?key|secret|password|credential|private[_-]?key|service[_-]?role)\s*[":=]/i.test(serialized))return{ok:false,error:"RAW_SECRET_FORBIDDEN"} as const;if(/\b(select|insert|update|delete|drop|alter|create)\b[\s\S]{0,30}\b(from|into|table)\b/i.test(serialized))return{ok:false,error:"ARBITRARY_QUERY_FORBIDDEN"} as const;return{ok:true,value:{operation,requestId,tenantId,userId,projectId,payload}} as const;}
function env(){const url=String(Deno.env.get("SUPABASE_URL")||"").replace(/\/$/,"");const key=String(Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"");if(!url||!key)throw new Error("PROVIDER_NOT_READY");return{url,key};}
function providerHeaders(key:string,extra:Record<string,string>={}){return{apikey:key,authorization:`Bearer ${key}`,"content-type":"application/json",...extra};}
function namespaceFor(operation:string){if(operation.startsWith("project."))return"project";if(operation.startsWith("context."))return"context";return"artifact";}
function recordKeyFor(operation:string,payload:Record<string,unknown>){if(operation==="artifact.meta")return text(payload.artifactId??payload.id??"default",160)||"default";return"default";}
function isWrite(operation:string,payload:Record<string,unknown>){if(operation.endsWith(".write"))return true;if(operation!=="artifact.meta")return false;return Object.keys(payload).some(k=>!["artifactId","id"].includes(k));}
async function readRecord(scope:any,namespace:string,recordKey:string){const{url,key}=env();const q=new URLSearchParams({tenant_id:`eq.${scope.tenantId}`,user_id:`eq.${scope.userId}`,project_id:`eq.${scope.projectId}`,namespace:`eq.${namespace}`,record_key:`eq.${recordKey}`,select:"payload,updated_at",limit:"1"});const response=await fetch(`${url}/rest/v1/laneriq_cloud_records?${q.toString()}`,{headers:providerHeaders(key),cache:"no-store"});const data=await response.json().catch(()=>[]);if(!response.ok)throw new Error("PROVIDER_READ_FAILED");const row=Array.isArray(data)?data[0]:null;return row?{found:true,payload:row.payload??{},updatedAt:row.updated_at??null}:{found:false,payload:null,updatedAt:null};}
async function writeRecord(scope:any,namespace:string,recordKey:string){const{url,key}=env();const q=new URLSearchParams({on_conflict:"tenant_id,user_id,project_id,namespace,record_key"});const body={tenant_id:scope.tenantId,user_id:scope.userId,project_id:scope.projectId,namespace,record_key:recordKey,payload:scope.payload,updated_at:new Date().toISOString()};const response=await fetch(`${url}/rest/v1/laneriq_cloud_records?${q.toString()}`,{method:"POST",headers:providerHeaders(key,{Prefer:"resolution=merge-duplicates,return=representation"}),body:JSON.stringify(body),cache:"no-store"});const data=await response.json().catch(()=>[]);if(!response.ok)throw new Error("PROVIDER_WRITE_FAILED");const row=Array.isArray(data)?data[0]:null;return{stored:true,payload:row?.payload??scope.payload,updatedAt:row?.updated_at??body.updated_at};}
Deno.serve(async(req:Request)=>{if(req.method==="GET")return json({service:"laneriq-cloud-storage-adapter",contract:"csvc1",providerOpaqueUpstream:true,live:true});if(req.method!=="POST")return json({error:"METHOD_NOT_ALLOWED"},405);if(req.headers.get("x-laneriq-cloud-contract")!=="csvc1")return json({error:"CONTRACT_MISMATCH"},409);if(!(await authorized(req)))return json({error:"UNAUTHORIZED"},401);let input:any;try{input=await req.json();}catch{return json({error:"INVALID_JSON"},400);}const checked=validate(input);if(!checked.ok)return json({error:checked.error},400);const scope=checked.value,namespace=namespaceFor(scope.operation),recordKey=recordKeyFor(scope.operation,scope.payload);try{const result=isWrite(scope.operation,scope.payload)?await writeRecord(scope,namespace,recordKey):await readRecord(scope,namespace,recordKey);return json({ok:true,operation:scope.operation,namespace,recordKey,...result});}catch(error){const message=error instanceof Error?error.message:"PROVIDER_FAILED";return json({error:message},message==="PROVIDER_NOT_READY"?503:502);}});
