"use client";

import {useEffect,useMemo,useRef,useState} from "react";
import {compileAdvancedGenreRuntimeV1,createAdvancedGenreState,stepStrategy,stepRacing,stepSimulation,playCard,guardCard,stepSports,judgeRhythm,stepSurvival} from "../../../lib/game/advanced-genre-runtime-v1.js";

const LABELS={strategy:"SLG / STRATEGY",racing:"RACING",simulation:"SIMULATION / TYCOON",card:"CARD / DECK",sports:"SPORTS",rhythm:"RHYTHM",survival:"SURVIVAL / ROGUELITE"};

export default function AdvancedGenreRuntimeClient({specification}){
  const config=useMemo(()=>compileAdvancedGenreRuntimeV1(specification),[specification]);const[state,setState]=useState(()=>createAdvancedGenreState(config));const stateRef=useRef(state);const driveRef=useRef({throttle:0,brake:0,steer:0});const survivalRef=useRef("move");
  function commit(next){stateRef.current=next;setState(next)}function restart(){commit(createAdvancedGenreState(config));driveRef.current={throttle:0,brake:0,steer:0};survivalRef.current="move";}
  useEffect(()=>{stateRef.current=state},[state]);useEffect(()=>{restart()},[config]);
  useEffect(()=>{if(config.genreId!=="racing")return;let active=true,last=performance.now(),raf=0;function frame(now){if(!active)return;const dt=Math.min(config.maxDelta,Math.max(.001,(now-last)/1000));last=now;const next=stepRacing(stateRef.current,driveRef.current,dt);if(next!==stateRef.current){stateRef.current=next;setState(next)}raf=requestAnimationFrame(frame)}raf=requestAnimationFrame(frame);return()=>{active=false;cancelAnimationFrame(raf)}},[config]);
  useEffect(()=>{if(config.genreId!=="survival")return;const timer=setInterval(()=>{const next=stepSurvival(stateRef.current,survivalRef.current,.5);commit(next)},500);return()=>clearInterval(timer)},[config]);
  const metrics=metricRows(config.genreId,state);const actions=actionRows(config.genreId,state,{commit,restart,driveRef,survivalRef});
  return <main className="shell"><header><div><small>SOOLENAI · {LABELS[config.genreId]} RUNTIME V1</small><h1>{config.title}</h1><p>{config.systems.join(" · ")}</p></div><span>iOS · Android · Web Preview</span></header>
    <section className="metrics">{metrics.map(([k,v])=><div key={k}><small>{k}</small><b>{v}</b></div>)}</section>
    <section className={`arena ${config.genreId}`}><div className="visual"><b>{visualTitle(config.genreId,state)}</b><p>{state.message}</p><div className="meter"><i style={{width:`${visualPercent(config.genreId,state)}%`}}/></div></div>{state.status!=="playing"&&<div className="overlay"><b>{state.status==="won"?"COMPLETE":state.status==="draw"?"DRAW":"FAILED"}</b><p>{state.message}</p><button onClick={restart}>Restart</button></div>}</section>
    <section className="actions">{actions}</section><footer><b>Evidence-gated specialist runtime.</b> This playable vertical slice proves the core state machine; it does not claim live multiplayer, licensed content or store approval.</footer>
    <style jsx>{`.shell{min-height:100vh;background:#05070b;color:#f5f7fa;padding:20px max(14px,env(safe-area-inset-right)) calc(28px + env(safe-area-inset-bottom)) max(14px,env(safe-area-inset-left));font-family:Inter,system-ui}header,.metrics,.arena,.actions,footer{max-width:1080px;margin:auto}header{display:flex;justify-content:space-between;align-items:end;gap:16px;padding:14px 0 18px}small{font-size:9px;letter-spacing:.1em;color:#e8ca68;font-weight:900}h1{font-size:clamp(30px,5vw,58px);margin:5px 0}p,footer{color:#9da7b5}header span{font-size:10px;border:1px solid #ffffff18;border-radius:999px;padding:9px 12px}.metrics{display:flex;gap:8px;flex-wrap:wrap}.metrics div{background:#0c1119;border:1px solid #ffffff12;border-radius:13px;padding:10px 12px;min-width:92px}.metrics b{display:block;font-size:19px;margin-top:2px}.arena{margin-top:12px;min-height:330px;border:1px solid #ffffff14;border-radius:25px;background:radial-gradient(circle at 60% 25%,#16304b,#090d14 55%);position:relative;overflow:hidden;display:grid;place-items:center;text-align:center}.arena.strategy{background:radial-gradient(circle at 55% 30%,#283d25,#090d0a 55%)}.arena.racing{background:linear-gradient(150deg,#251615,#080a0f)}.arena.simulation{background:radial-gradient(circle at 45% 20%,#243f46,#071014 60%)}.arena.card{background:radial-gradient(circle,#33274d,#090711 65%)}.arena.sports{background:radial-gradient(circle,#174027,#07110a 65%)}.arena.rhythm{background:radial-gradient(circle,#3d1e56,#08050d 65%)}.arena.survival{background:radial-gradient(circle,#45301e,#0d0906 65%)}.visual b{font-size:clamp(30px,6vw,68px)}.visual p{max-width:600px;padding:0 16px}.meter{height:8px;width:min(420px,75vw);margin:20px auto;background:#ffffff14;border-radius:99px;overflow:hidden}.meter i{display:block;height:100%;background:#e8ca68;transition:width .15s}.overlay{position:absolute;inset:0;background:#02040be8;display:grid;place-content:center;gap:10px}.overlay b{font-size:44px}.actions{display:flex;flex-wrap:wrap;gap:9px;justify-content:center;margin-top:14px}.actions :global(button){min-height:50px;border:1px solid #ffffff18;border-radius:14px;background:#141b26;color:white;font-weight:900;padding:0 22px;touch-action:manipulation}.actions :global(button.primary){background:#ab473e}.actions :global(button.alt){background:#254c3c}footer{padding-top:18px;font-size:11px;line-height:1.6}@media(max-width:620px){header{display:grid}.arena{min-height:280px}.actions :global(button){flex:1 1 42%;padding:0 12px}}`}</style>
  </main>;
}

function metricRows(id,s){switch(id){case"strategy":return[["TURN",s.turn],["FOOD",Math.round(s.food)],["WOOD",Math.round(s.wood)],["GOLD",Math.round(s.gold)],["ARMY",s.army],["TERRITORY",`${s.territory}/3`],["BASE HP",Math.round(s.baseHealth)]];case"racing":return[["LAP",`${Math.min(s.lap,s.maxLaps)}/${s.maxLaps}`],["SPEED",Math.round(s.speed)],["CHECKPOINT",`${s.checkpoint+1}/${s.maxCheckpoints}`],["POSITION",s.position],["DAMAGE",`${Math.round(s.damage)}%`],["TIME",s.totalTime.toFixed(1)]];case"simulation":return[["DAY",s.day],["CASH",Math.round(s.cash)],["POP",`${s.population}/${s.goalPopulation}`],["CAPACITY",s.capacity],["HAPPINESS",`${s.happiness}%`],["BUILDINGS",s.buildings]];case"card":return[["TURN",s.turn],["HP",s.playerHp],["ENEMY",s.enemyHp],["MANA",`${s.mana}/${s.maxMana}`],["HAND",s.hand.length],["GUARD",s.guard]];case"sports":return[["TIME",s.clock],["SCORE",`${s.score}-${s.opponentScore}`],["POSSESSION",s.possession],["FIELD",s.field],["STAMINA",Math.round(s.stamina)]];case"rhythm":return[["BEAT",`${s.beat}/${s.totalBeats}`],["SCORE",s.score],["COMBO",s.combo],["BEST",s.bestCombo],["METER",s.meter],["JUDGE",s.lastJudgement]];case"survival":return[["TIME",`${Math.floor(s.time)}/${s.targetTime}`],["HP",Math.round(s.health)],["LEVEL",s.level],["MATERIAL",s.materials],["THREAT",s.threat.toFixed(1)],["SCORE",Math.round(s.score)]];default:return[]}}
function visualTitle(id,s){return{id:``,strategy:`Territory ${s.territory}/3 · Enemy ${Math.round(s.enemyPower)}`,racing:`${Math.round(s.speed)} km/h`,simulation:`Population ${s.population}`,card:`${s.hand.map(v=>`[${v}]`).join(" ")}`,sports:`${s.score} — ${s.opponentScore}`,rhythm:s.lastJudgement,survival:`Threat ${s.threat.toFixed(1)}`}[id]||"PLAY"}
function visualPercent(id,s){switch(id){case"strategy":return Math.min(100,s.territory/3*100);case"racing":return Math.min(100,s.progress/s.maxLaps*100);case"simulation":return Math.min(100,s.population/s.goalPopulation*100);case"card":return Math.min(100,(30-s.enemyHp)/30*100);case"sports":return Math.min(100,s.field);case"rhythm":return s.meter;case"survival":return Math.min(100,s.time/s.targetTime*100);default:return 0}}
function actionRows(id,s,{commit,restart,driveRef,survivalRef}){const btn=(label,fn,cls="")=><button key={label} className={cls} onClick={fn}>{label}</button>;if(s.status!=="playing")return[btn("RESTART",restart,"primary")];switch(id){case"strategy":return["gather","build","train","research","attack"].map(a=>btn(a.toUpperCase(),()=>commit(stepStrategy(s,a)),a==="attack"?"primary":""));case"racing":return[<button key="left" onPointerDown={()=>driveRef.current.steer=-1} onPointerUp={()=>driveRef.current.steer=0}>STEER ◀</button>,<button key="throttle" className="primary" onPointerDown={()=>driveRef.current.throttle=1} onPointerUp={()=>driveRef.current.throttle=0}>THROTTLE</button>,<button key="brake" onPointerDown={()=>driveRef.current.brake=1} onPointerUp={()=>driveRef.current.brake=0}>BRAKE</button>,<button key="right" onPointerDown={()=>driveRef.current.steer=1} onPointerUp={()=>driveRef.current.steer=0}>STEER ▶</button>,btn("RESTART",restart)];case"simulation":return["build","upgrade","services","price_up"].map(a=>btn(a.replace("_"," ").toUpperCase(),()=>commit(stepSimulation(s,a)),a==="build"?"primary":""));case"card":return[...s.hand.map((v,i)=>btn(`PLAY ${v}`,()=>commit(playCard(s,i)),i===0?"primary":"")),btn("GUARD",()=>commit(guardCard(s))),btn("RESTART",restart)];case"sports":return["pass","sprint","shoot","defend"].map(a=>btn(a.toUpperCase(),()=>commit(stepSports(s,a)),a==="shoot"?"primary":""));case"rhythm":return[["PERFECT",0],["GREAT",70],["GOOD",120],["MISS",220]].map(([label,d])=>btn(label,()=>commit(judgeRhythm(s,d)),label==="PERFECT"?"primary":""));case"survival":return["move","attack","dodge","scavenge","heal"].map(a=>btn(a.toUpperCase(),()=>{survivalRef.current=a;commit(stepSurvival(s,a,.2))},a==="attack"?"primary":""));default:return[btn("RESTART",restart)]}}
