"use client";

import {useEffect,useMemo,useRef,useState} from "react";
import {compileGameRuntimeV1,initialGameState} from "../../../lib/game/runtime-v1.js";

function clamp(v,min,max){return Math.max(min,Math.min(max,v));}
function dist(a,b){const dx=a.x-b.x,dy=a.y-b.y;return Math.sqrt(dx*dx+dy*dy);}
function randomPoint(w,h,pad=50){return{x:pad+Math.random()*(w-pad*2),y:pad+Math.random()*(h-pad*2)}}

export default function GameRuntimeClient({appId,app,specification,customerMedia=[]}){
  const config=useMemo(()=>compileGameRuntimeV1(specification),[specification]);
  const canvasRef=useRef(null);const runtimeRef=useRef(null);const keysRef=useRef({});const inputRef=useRef({x:0,y:0});const rafRef=useRef(0);const audioRef=useRef(null);
  const[state,setState]=useState(()=>initialGameState(config));const[muted,setMuted]=useState(false);const[notice,setNotice]=useState("Touch the controls or drag on the game field to move.");
  const saveKey=`${config.save.keyPrefix}:${appId}`;
  const backdrop=customerMedia.find(item=>String(item?.mimeType||"").startsWith("image/"))?.url||"";

  function beep(freq=440,duration=.06){if(muted)return;try{const Ctx=window.AudioContext||window.webkitAudioContext;const ctx=audioRef.current||(audioRef.current=new Ctx());if(ctx.state==="suspended")ctx.resume();const osc=ctx.createOscillator(),gain=ctx.createGain();osc.frequency.value=freq;gain.gain.setValueAtTime(.05,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+duration);osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+duration)}catch{}}

  function freshRuntime(level=1){const w=config.scene.width,h=config.scene.height;const enemyCount=Math.min(16,config.enemies.baseCount+Math.floor((level-1)/2));return{player:{x:w*.5,y:h*.58,vx:0,vy:0},enemies:Array.from({length:enemyCount},(_,i)=>({...randomPoint(w,h,70),vx:(i%2?1:-1)*(config.enemies.speed+level*4),vy:(i%3?1:-1)*(config.enemies.speed*.72+level*3)})),orb:randomPoint(w,h,75),damageCooldown:0,last:performance.now()};}

  function persist(next){try{localStorage.setItem(saveKey,JSON.stringify({version:1,score:next.score,health:next.health,level:next.level,collected:next.collected,bestScore:Math.max(next.bestScore||0,next.score||0),savedAt:new Date().toISOString()}));setNotice("Game saved on this device.")}catch{setNotice("Unable to save on this device.")}}
  function load(){try{const raw=JSON.parse(localStorage.getItem(saveKey)||"null");if(!raw)return setNotice("No saved game yet.");const next={...initialGameState(config),...raw,paused:false,gameOver:false};setState(next);runtimeRef.current=freshRuntime(next.level);setNotice("Saved game loaded.");beep(620,.08)}catch{setNotice("Saved game could not be loaded.")}}
  function restart(){const next=initialGameState(config);setState(next);runtimeRef.current=freshRuntime(1);setNotice("New run started.");beep(520,.06)}
  function togglePause(){setState(current=>({...current,paused:!current.paused}));setNotice(state.paused?"Game resumed.":"Game paused.")}

  useEffect(()=>{runtimeRef.current=freshRuntime(1);try{const raw=JSON.parse(localStorage.getItem(saveKey)||"null");if(raw?.bestScore)setState(current=>({...current,bestScore:Number(raw.bestScore)||0}))}catch{}},[saveKey]);

  useEffect(()=>{
    const down=e=>{keysRef.current[e.key.toLowerCase()]=true;if(["arrowup","arrowdown","arrowleft","arrowright"," "].includes(e.key.toLowerCase()))e.preventDefault()};
    const up=e=>{keysRef.current[e.key.toLowerCase()]=false};window.addEventListener("keydown",down,{passive:false});window.addEventListener("keyup",up);
    const visibility=()=>{if(document.hidden)setState(current=>({...current,paused:true}))};document.addEventListener("visibilitychange",visibility);
    return()=>{window.removeEventListener("keydown",down);window.removeEventListener("keyup",up);document.removeEventListener("visibilitychange",visibility)};
  },[]);

  useEffect(()=>{
    const canvas=canvasRef.current;if(!canvas)return;const ctx=canvas.getContext("2d");let active=true;
    function frame(now){if(!active)return;const rt=runtimeRef.current;if(!rt){rafRef.current=requestAnimationFrame(frame);return}const dt=Math.min(.033,Math.max(.001,(now-rt.last)/1000));rt.last=now;
      setState(current=>{
        if(current.paused||current.gameOver)return current;
        const keys=keysRef.current;let ix=inputRef.current.x+(keys.arrowright||keys.d?1:0)-(keys.arrowleft||keys.a?1:0),iy=inputRef.current.y+(keys.arrowdown||keys.s?1:0)-(keys.arrowup||keys.w?1:0);const m=Math.hypot(ix,iy)||1;ix/=m;iy/=m;
        rt.player.vx+=(ix*config.player.speed-rt.player.vx)*Math.min(1,dt*9);rt.player.vy+=(iy*config.player.speed-rt.player.vy)*Math.min(1,dt*9);rt.player.x=clamp(rt.player.x+rt.player.vx*dt,config.player.radius,config.scene.width-config.player.radius);rt.player.y=clamp(rt.player.y+rt.player.vy*dt,config.player.radius,config.scene.height-config.player.radius);
        const speedBoost=1+(current.level-1)*config.progression.levelSpeedGrowth;for(const enemy of rt.enemies){enemy.x+=enemy.vx*dt*speedBoost;enemy.y+=enemy.vy*dt*speedBoost;if(enemy.x<22||enemy.x>config.scene.width-22)enemy.vx*=-1;if(enemy.y<22||enemy.y>config.scene.height-22)enemy.vy*=-1;enemy.x=clamp(enemy.x,22,config.scene.width-22);enemy.y=clamp(enemy.y,22,config.scene.height-22)}
        let next=current;rt.damageCooldown=Math.max(0,rt.damageCooldown-dt);if(dist(rt.player,rt.orb)<config.player.radius+15){const score=current.score+config.progression.scorePerCollectible,collected=current.collected+1;let level=current.level,levelCollected=collected;if(collected>=config.progression.collectiblesPerLevel){level=current.level+1;levelCollected=0;runtimeRef.current={...freshRuntime(level),last:now};setNotice(`Level ${level}! More enemies, faster movement.`);beep(780,.09)}else{rt.orb=randomPoint(config.scene.width,config.scene.height,75);beep(680,.05)}next={...current,score,collected:levelCollected,level,bestScore:Math.max(current.bestScore,score)}}
        if(rt.damageCooldown<=0){for(const enemy of rt.enemies){if(dist(rt.player,enemy)<config.player.radius+20){const health=Math.max(0,next.health-config.enemies.damage);rt.damageCooldown=.8;beep(180,.1);if(health<=0){const final={...next,health:0,gameOver:true,bestScore:Math.max(next.bestScore,next.score)};persist(final);setNotice("Run over. Restart or load your saved progress.");return final}next={...next,health};break}}}
        return next;
      });
      ctx.clearRect(0,0,canvas.width,canvas.height);const scaleX=canvas.width/config.scene.width,scaleY=canvas.height/config.scene.height;ctx.save();ctx.scale(scaleX,scaleY);const grad=ctx.createLinearGradient(0,0,config.scene.width,config.scene.height);grad.addColorStop(0,config.scene.background);grad.addColorStop(1,"#020705");ctx.fillStyle=grad;ctx.fillRect(0,0,config.scene.width,config.scene.height);
      ctx.globalAlpha=.16;ctx.strokeStyle=config.scene.primary;ctx.lineWidth=1;for(let x=0;x<config.scene.width;x+=48){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,config.scene.height);ctx.stroke()}for(let y=0;y<config.scene.height;y+=48){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(config.scene.width,y);ctx.stroke()}ctx.globalAlpha=1;
      ctx.shadowBlur=22;ctx.shadowColor=config.scene.accent;ctx.fillStyle=config.scene.accent;ctx.beginPath();ctx.arc(rt.orb.x,rt.orb.y,14,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;
      for(const enemy of rt.enemies){ctx.fillStyle="#ed665c";ctx.beginPath();ctx.arc(enemy.x,enemy.y,20,0,Math.PI*2);ctx.fill();ctx.fillStyle="#170604";ctx.fillRect(enemy.x-7,enemy.y-3,4,4);ctx.fillRect(enemy.x+3,enemy.y-3,4,4)}
      ctx.fillStyle=config.scene.primary;ctx.shadowBlur=18;ctx.shadowColor=config.scene.primary;ctx.beginPath();ctx.arc(rt.player.x,rt.player.y,config.player.radius,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(rt.player.x+5,rt.player.y-4,4,0,Math.PI*2);ctx.fill();ctx.restore();rafRef.current=requestAnimationFrame(frame)}
    rafRef.current=requestAnimationFrame(frame);return()=>{active=false;cancelAnimationFrame(rafRef.current)};
  },[config,muted]);

  function pointerMove(event){const canvas=canvasRef.current;if(!canvas||event.buttons===0&&event.pointerType!=="touch")return;const rect=canvas.getBoundingClientRect();const x=(event.clientX-rect.left)/rect.width*config.scene.width,y=(event.clientY-rect.top)/rect.height*config.scene.height;const p=runtimeRef.current?.player;if(!p)return;const dx=x-p.x,dy=y-p.y,m=Math.hypot(dx,dy)||1;inputRef.current={x:dx/m,y:dy/m}}
  function pointerUp(){inputRef.current={x:0,y:0}}
  function dpad(x,y){inputRef.current={x,y}}

  return <main className="gameShell" style={{"--primary":config.scene.primary,"--accent":config.scene.accent,"--bg":config.scene.background,backgroundImage:backdrop?`linear-gradient(#020705e8,#020705f5),url(${backdrop})`:undefined}}>
    <header><div><small>SOOLENAI · GAME RUNTIME V1 · 2D PLAYABLE</small><h1>{config.title}</h1><p>{config.genre} · {config.objective}</p></div><div className="platforms"><span>iOS</span><span>Android</span><span>Web Preview</span></div></header>
    <section className="hud"><div><small>SCORE</small><b>{state.score}</b></div><div><small>HEALTH</small><b>{state.health}</b></div><div><small>LEVEL</small><b>{state.level}</b></div><div><small>BEST</small><b>{state.bestScore}</b></div></section>
    <section className="stage"><canvas ref={canvasRef} width="960" height="600" onPointerDown={pointerMove} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerUp}/>{state.paused&&!state.gameOver&&<div className="overlay"><b>PAUSED</b><span>Tap Resume to continue.</span></div>}{state.gameOver&&<div className="overlay"><b>GAME OVER</b><span>Score {state.score}</span><button onClick={restart}>Restart</button></div>}</section>
    <section className="controls"><div className="dpad"><button onPointerDown={()=>dpad(0,-1)} onPointerUp={pointerUp}>▲</button><div><button onPointerDown={()=>dpad(-1,0)} onPointerUp={pointerUp}>◀</button><button onPointerDown={()=>dpad(1,0)} onPointerUp={pointerUp}>▶</button></div><button onPointerDown={()=>dpad(0,1)} onPointerUp={pointerUp}>▼</button></div><div className="actions"><button onClick={togglePause}>{state.paused?"Resume":"Pause"}</button><button onClick={()=>persist(state)}>Save</button><button onClick={load}>Load</button><button onClick={restart}>Restart</button><button onClick={()=>setMuted(v=>!v)}>{muted?"Sound Off":"Sound On"}</button></div></section>
    <div className="notice">{notice}</div><footer><b>Runtime systems:</b> Scene · Touch · Physics · Collision · Player/Enemy · Level · Score/Health · Save/Load · Audio · Pause/Restart · iPhone/Android responsive</footer>
    <style jsx global>{`.accountNav,.sv-fab,.wallpaperControl,.studioLauncher{display:none!important}.gameShell{min-height:100vh;background-color:#020705;background-size:cover;background-position:center;color:#effaf5;font-family:Inter,system-ui,-apple-system,sans-serif;padding:max(18px,env(safe-area-inset-top)) max(14px,env(safe-area-inset-right)) max(28px,env(safe-area-inset-bottom)) max(14px,env(safe-area-inset-left));touch-action:manipulation}.gameShell header,.hud,.stage,.controls,.notice,.gameShell footer{width:min(1040px,100%);margin-left:auto;margin-right:auto}.gameShell header{display:flex;justify-content:space-between;gap:18px;align-items:flex-end;padding:14px 4px}.gameShell header small{color:var(--accent);font-size:9px;font-weight:950;letter-spacing:.15em}.gameShell h1{font-size:clamp(30px,6vw,58px);line-height:1;margin:8px 0}.gameShell header p{color:#9cb1a8;max-width:720px;line-height:1.5}.platforms{display:flex;gap:6px;flex-wrap:wrap}.platforms span{border:1px solid #ffffff1e;border-radius:999px;padding:7px 9px;font-size:9px;color:#dce9e3}.hud{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-bottom:9px}.hud div{background:#081b15dc;border:1px solid #ffffff12;border-radius:13px;padding:10px 12px}.hud small{display:block;color:#76958a;font-size:8px;font-weight:900}.hud b{font-size:19px;color:#fff}.stage{position:relative;border-radius:22px;overflow:hidden;border:1px solid #ffffff18;background:#020705;box-shadow:0 24px 70px #0008;aspect-ratio:16/10}.stage canvas{display:block;width:100%;height:100%;touch-action:none}.overlay{position:absolute;inset:0;display:grid;place-content:center;text-align:center;gap:10px;background:#020705b8;backdrop-filter:blur(8px)}.overlay b{font-size:42px;color:var(--accent)}.overlay span{color:#afc1b9}.overlay button{border:0;border-radius:12px;background:var(--accent);color:#06110d;padding:12px 18px;font-weight:950}.controls{display:flex;justify-content:space-between;gap:14px;align-items:center;margin-top:12px}.dpad{display:grid;justify-items:center;gap:5px}.dpad>div{display:flex;gap:40px}.dpad button,.actions button{user-select:none;-webkit-user-select:none;border:1px solid #ffffff19;background:#0a2119;color:#fff;border-radius:14px;min-width:52px;min-height:46px;font-weight:950}.dpad button:active,.actions button:active{transform:scale(.96);background:var(--primary)}.actions{display:flex;gap:7px;flex-wrap:wrap;justify-content:flex-end}.actions button{padding:0 13px;color:#d8e7e0}.notice,.gameShell footer{margin-top:10px;border:1px solid #ffffff10;background:#071812cc;border-radius:14px;padding:11px 13px;color:#9fb2aa;font-size:11px;line-height:1.45}.gameShell footer b{color:var(--accent)}@media(max-width:650px){.gameShell header{display:grid}.hud{grid-template-columns:1fr 1fr}.controls{align-items:flex-end}.actions{max-width:190px}.actions button{min-height:40px}.dpad>div{gap:28px}}`}</style>
  </main>;
}
