"use client";

import {useEffect,useMemo,useRef,useState} from "react";
import {compileRemainingGenreRuntimeV1,createRemainingGenreState,stepShooter,stepPlatformer,stepTowerDefense,stepIdle,stepParty,stepEducational} from "../../../lib/game/remaining-genre-runtime-v1.js";

const LABELS={shooter:"FPS / TPS SHOOTER",platformer:"PLATFORMER / RUNNER",tower_defense:"TOWER DEFENSE",idle:"IDLE / INCREMENTAL",party:"PARTY / SOCIAL",educational:"EDUCATIONAL / LEARNING"};

export default function RemainingGenreRuntimeClient({specification}){
  const config=useMemo(()=>compileRemainingGenreRuntimeV1(specification),[specification]);const[state,setState]=useState(()=>createRemainingGenreState(config));const stateRef=useRef(state);
  function commit(next){stateRef.current=next;setState(next)}function restart(){commit(createRemainingGenreState(config));}
  useEffect(()=>{stateRef.current=state},[state]);useEffect(()=>{restart()},[config]);
  useEffect(()=>{if(config.genreId!=="idle")return;const timer=setInterval(()=>{commit(stepIdle(stateRef.current,"tick",1))},1000);return()=>clearInterval(timer)},[config]);
  const metrics=metricRows(config.genreId,state),actions=actionRows(config.genreId,state,{commit,restart});
  return <main className="shell"><header><div><small>SOOLENAI · {LABELS[config.genreId]} RUNTIME V1</small><h1>{config.title}</h1><p>{config.systems.join(" · ")}</p></div><span>iOS · Android · Web Preview</span></header>
    <section className="metrics">{metrics.map(([k,v])=><div key={k}><small>{k}</small><b>{v}</b></div>)}</section>
    <section className={`arena ${config.genreId}`}><div><b>{visualTitle(config.genreId,state)}</b><p>{state.message}</p><div className="meter"><i style={{width:`${visualPercent(config.genreId,state)}%`}}/></div></div>{!["playing","lobby"].includes(state.status)&&<div className="overlay"><b>{state.status==="won"?"COMPLETE":state.status==="draw"?"DRAW":"FAILED"}</b><p>{state.message}</p><button onClick={restart}>Restart</button></div>}</section>
    <section className="actions">{actions}</section><footer><b>Evidence-gated specialist runtime.</b> This vertical slice proves the local gameplay state machine. It does not claim live multiplayer, licensed assets, educational accreditation or store approval.</footer>
    <style jsx>{`.shell{min-height:100vh;background:#05070b;color:#f5f7fa;padding:20px max(14px,env(safe-area-inset-right)) calc(28px + env(safe-area-inset-bottom)) max(14px,env(safe-area-inset-left));font-family:Inter,system-ui}header,.metrics,.arena,.actions,footer{max-width:1080px;margin:auto}header{display:flex;justify-content:space-between;align-items:end;gap:16px;padding:14px 0 18px}small{font-size:9px;letter-spacing:.1em;color:#e8ca68;font-weight:900}h1{font-size:clamp(30px,5vw,58px);margin:5px 0}p,footer{color:#9da7b5}header span{font-size:10px;border:1px solid #ffffff18;border-radius:999px;padding:9px 12px}.metrics{display:flex;gap:8px;flex-wrap:wrap}.metrics div{background:#0c1119;border:1px solid #ffffff12;border-radius:13px;padding:10px 12px;min-width:92px}.metrics b{display:block;font-size:19px;margin-top:2px}.arena{margin-top:12px;min-height:320px;border:1px solid #ffffff14;border-radius:25px;position:relative;overflow:hidden;display:grid;place-items:center;text-align:center;background:radial-gradient(circle at 60% 25%,#16304b,#090d14 58%)}.arena.platformer{background:radial-gradient(circle,#254d3b,#07110b 65%)}.arena.tower_defense{background:radial-gradient(circle,#4a3825,#0d0906 65%)}.arena.idle{background:radial-gradient(circle,#3a2451,#09070f 65%)}.arena.party{background:radial-gradient(circle,#4b2345,#0f0711 65%)}.arena.educational{background:radial-gradient(circle,#1f4053,#071016 65%)}.arena>div>b{font-size:clamp(30px,6vw,68px)}.arena p{max-width:620px;padding:0 16px}.meter{height:8px;width:min(420px,75vw);margin:20px auto;background:#ffffff14;border-radius:99px;overflow:hidden}.meter i{display:block;height:100%;background:#e8ca68;transition:width .15s}.overlay{position:absolute;inset:0;background:#02040be8;display:grid;place-content:center;gap:10px}.overlay b{font-size:44px}.actions{display:flex;flex-wrap:wrap;gap:9px;justify-content:center;margin-top:14px}.actions :global(button){min-height:50px;border:1px solid #ffffff18;border-radius:14px;background:#141b26;color:white;font-weight:900;padding:0 22px;touch-action:manipulation}.actions :global(button.primary){background:#ab473e}.actions :global(button.alt){background:#254c3c}footer{padding-top:18px;font-size:11px;line-height:1.6}@media(max-width:620px){header{display:grid}.arena{min-height:275px}.actions :global(button){flex:1 1 42%;padding:0 12px}}`}</style>
  </main>;
}

function metricRows(id,s){switch(id){case"shooter":return[["HP",s.health],["ARMOR",s.armor],["AMMO",`${s.ammo}/${s.reserve}`],["TARGETS",`${s.hits}/${s.objective}`],["ENEMIES",s.enemies],["SCORE",s.score]];case"platformer":return[["PROGRESS",`${s.progress}%`],["LIVES",s.health],["CHECKPOINT",`${s.checkpoint}%`],["COINS",s.coins],["ENERGY",s.jumpEnergy]];case"tower_defense":return[["WAVE",`${s.wave}/${s.maxWaves}`],["CORE HP",s.baseHealth],["GOLD",s.gold],["TOWERS",s.towers],["UPGRADES",s.upgrades],["ENEMIES",s.enemies]];case"idle":return[["COINS",Math.floor(s.coins)],["RATE",`${s.rate.toFixed(1)}/s`],["LEVEL",s.level],["AUTO",s.automation],["PRESTIGE",s.prestige],["TOTAL",Math.floor(s.totalEarned)]];case"party":return[["ROUND",`${s.round}/${s.maxRounds}`],["YOU",s.playerScore],["BOT",s.botScore],["STREAK",s.streak],["STATE",s.status]];case"educational":return[["QUESTION",`${s.question}/${s.totalQuestions}`],["CORRECT",s.correct],["WRONG",s.wrong],["STREAK",s.streak],["MASTERY",`${s.mastery}%`],["LEVEL",s.difficulty]];default:return[]}}
function visualTitle(id,s){return{id:"",shooter:`${s.hits}/${s.objective} TARGETS`,platformer:`${s.progress}% TO EXIT`,tower_defense:`WAVE ${s.wave}`,idle:`${Math.floor(s.totalEarned)} TOTAL`,party:s.status==="lobby"?"READY?":`ROUND ${s.round}`,educational:`MASTERY ${s.mastery}%`}[id]||"PLAY"}
function visualPercent(id,s){switch(id){case"shooter":return Math.min(100,s.hits/s.objective*100);case"platformer":return s.progress;case"tower_defense":return Math.min(100,(s.wave-1)/s.maxWaves*100);case"idle":return Math.min(100,s.totalEarned/s.goal*100);case"party":return Math.min(100,s.round/s.maxRounds*100);case"educational":return s.mastery;default:return 0}}
function actionRows(id,s,{commit,restart}){const btn=(label,fn,cls="")=><button key={label} className={cls} onClick={fn}>{label}</button>;if(!["playing","lobby"].includes(s.status))return[btn("RESTART",restart,"primary")];switch(id){case"shooter":return["advance","fire","reload","cover"].map(a=>btn(a.toUpperCase(),()=>commit(stepShooter(s,a)),a==="fire"?"primary":""));case"platformer":return["move","jump","dash","rest","hazard"].map(a=>btn(a.toUpperCase(),()=>commit(stepPlatformer(s,a)),a==="jump"?"primary":""));case"tower_defense":return["build","upgrade","sell","wave"].map(a=>btn(a.toUpperCase(),()=>commit(stepTowerDefense(s,a)),a==="wave"?"primary":""));case"idle":return["tap","upgrade","automate","prestige"].map(a=>btn(a.toUpperCase(),()=>commit(stepIdle(s,a,0)),a==="upgrade"?"primary":""));case"party":return s.status==="lobby"?[btn("READY",()=>commit(stepParty(s,"ready")),"primary")]:["hit","wait","bonus"].map(a=>btn(a.toUpperCase(),()=>commit(stepParty(s,a)),a==="hit"?"primary":""));case"educational":return[btn("CORRECT OPTION",()=>commit(stepEducational(s,"correct")),"primary"),btn("WRONG OPTION",()=>commit(stepEducational(s,"wrong"))),btn("HINT",()=>commit(stepEducational(s,"hint")))];default:return[btn("RESTART",restart)]}}
