"use client";

import {useEffect,useMemo,useRef,useState} from "react";
import {compileSpecialistRuntimeV1,createSpecialistState,stepRpgRuntime,puzzleMove,puzzleUndo,puzzleHint,stepActionRuntime} from "../../../lib/game/specialist-runtime-v1.js";

function clamp(v,min,max){return Math.max(min,Math.min(max,v));}
const LABELS={rpg:"RPG / ADVENTURE",puzzle:"PUZZLE / BRAIN",action:"ACTION COMBAT"};

export default function SpecialistRuntimeClient({appId,specification}){
  const config=useMemo(()=>compileSpecialistRuntimeV1(specification),[specification]);const[state,setState]=useState(()=>createSpecialistState(config));const stateRef=useRef(state),canvasRef=useRef(null),inputRef=useRef({x:0,y:0}),actionRef=useRef({attack:false,dodge:false,heavy:false});const[paused,setPaused]=useState(false),[notice,setNotice]=useState("");
  function commit(next){stateRef.current=next;setState(next);return next}function restart(){const next=createSpecialistState(config);commit(next);setPaused(false);setNotice("New run started.")}
  useEffect(()=>{stateRef.current=state},[state]);useEffect(()=>{restart()},[config]);

  useEffect(()=>{if(config.genreId==="puzzle")return;const canvas=canvasRef.current;if(!canvas)return;const ctx=canvas.getContext("2d");let active=true,last=performance.now(),raf=0,lastUi=0;
    function draw(s){const W=canvas.width,H=canvas.height;ctx.fillStyle=config.genreId==="rpg"?"#071a13":"#140a0a";ctx.fillRect(0,0,W,H);ctx.strokeStyle="#ffffff10";for(let x=0;x<W;x+=48){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=48){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}
      if(config.genreId==="rpg"){for(const relic of s.relics){if(relic.taken)continue;ctx.fillStyle="#e8cf69";ctx.beginPath();ctx.arc(relic.x,relic.y,13,0,Math.PI*2);ctx.fill()}for(const enemy of s.enemies){if(enemy.hp<=0)continue;ctx.fillStyle="#d75c55";ctx.beginPath();ctx.arc(enemy.x,enemy.y,22,0,Math.PI*2);ctx.fill()}ctx.fillStyle="#68d7aa";ctx.beginPath();ctx.arc(s.player.x,s.player.y,20,0,Math.PI*2);ctx.fill();}
      else{for(const enemy of s.enemies){if(enemy.hp<=0)continue;ctx.fillStyle=enemy.state==="boss"?"#a344ff":"#ef6159";ctx.fillRect(enemy.x-22,enemy.y-22,44,44);ctx.fillStyle="#fff";ctx.font="11px system-ui";ctx.fillText(`HP ${Math.max(0,enemy.hp)}`,enemy.x-20,enemy.y-29)}ctx.fillStyle=s.invulnerable>0?"#fff19a":"#55cfa0";ctx.beginPath();ctx.arc(s.player.x,s.player.y,21,0,Math.PI*2);ctx.fill();}}
    function frame(now){if(!active)return;const dt=Math.min(config.maxDelta,Math.max(.001,(now-last)/1000));last=now;let current=stateRef.current;if(!paused&&current.status==="playing"){const input=inputRef.current,actions=actionRef.current;const next=config.genreId==="rpg"?stepRpgRuntime(current,{...input,attack:actions.attack},dt):stepActionRuntime(current,{...input,attack:actions.attack,dodge:actions.dodge,heavy:actions.heavy},dt);actionRef.current={attack:false,dodge:false,heavy:false};stateRef.current=next;if(now-lastUi>90){lastUi=now;setState(next);if(next.message)setNotice(next.message)}}draw(stateRef.current);raf=requestAnimationFrame(frame)}raf=requestAnimationFrame(frame);return()=>{active=false;cancelAnimationFrame(raf)}},[config,paused]);

  function move(x,y){inputRef.current={x,y}}function stop(){inputRef.current={x:0,y:0}}function action(type){actionRef.current={...actionRef.current,[type]:true}}
  if(config.genreId==="puzzle")return <PuzzleView config={config} state={state} setState={next=>commit(next)} restart={restart} notice={notice} setNotice={setNotice}/>;
  const rpg=config.genreId==="rpg";
  return <main className="shell"><header><div><small>SOOLENAI · {LABELS[config.genreId]} RUNTIME V1</small><h1>{config.title}</h1><p>{rpg?"Explore · Quest · Combat · XP · Save-ready":"Move · Attack · Dodge · Combo · Boss"}</p></div><span className="platform">iOS · Android · Web Preview</span></header>
    <section className="hud"><div><small>HP</small><b>{Math.round(state.health)}</b></div>{rpg?<><div><small>LEVEL</small><b>{state.level}</b></div><div><small>XP</small><b>{Math.round(state.xp)}</b></div><div><small>GOLD</small><b>{state.gold}</b></div><div><small>QUEST</small><b>{state.quest.found}/{state.quest.required}</b></div></>:<><div><small>STAMINA</small><b>{Math.round(state.stamina)}</b></div><div><small>COMBO</small><b>{state.combo}</b></div><div><small>SCORE</small><b>{state.score}</b></div></>}</section>
    <section className="stage"><canvas ref={canvasRef} width="960" height="600" aria-label={`${LABELS[config.genreId]} playable field`}/>{state.status!=="playing"?<div className="overlay"><b>{state.status==="won"?"COMPLETE":"FAILED"}</b><span>{state.message}</span><button onClick={restart}>Restart</button></div>:paused?<div className="overlay"><b>PAUSED</b><button onClick={()=>setPaused(false)}>Resume</button></div>:null}</section>
    <section className="controls"><div className="dpad"><i/><button onPointerDown={()=>move(0,-1)} onPointerUp={stop}>▲</button><button onPointerDown={()=>move(-1,0)} onPointerUp={stop}>◀</button><button onPointerDown={()=>move(1,0)} onPointerUp={stop}>▶</button><button onPointerDown={()=>move(0,1)} onPointerUp={stop}>▼</button></div><div className="actions"><button className="primary" onClick={()=>action("attack")}>{rpg?"ATTACK":"ATTACK"}</button>{!rpg&&<><button onClick={()=>action("dodge")}>DODGE</button><button onClick={()=>{actionRef.current.heavy=true;action("attack")}}>HEAVY</button></>}<button onClick={()=>setPaused(v=>!v)}>{paused?"RESUME":"PAUSE"}</button><button onClick={restart}>RESTART</button></div></section><div className="notice">{notice||state.message}</div>
    <style jsx>{`.shell{min-height:100vh;background:#020806;color:#eef9f4;padding:18px max(14px,env(safe-area-inset-right)) calc(25px + env(safe-area-inset-bottom)) max(14px,env(safe-area-inset-left));font-family:Inter,system-ui}header,.hud,.stage,.controls,.notice{max-width:1120px;margin:auto}header{display:flex;justify-content:space-between;gap:15px;align-items:end;padding:14px 0}small{font-size:9px;color:#e4c861;font-weight:900;letter-spacing:.1em}h1{font-size:clamp(30px,5vw,58px);margin:5px 0}p,.notice{color:#9db2a8}.platform{font-size:10px;border:1px solid #ffffff14;border-radius:999px;padding:9px 12px}.hud{display:flex;gap:7px;flex-wrap:wrap;margin-bottom:8px}.hud div{min-width:90px;background:#081a14;border:1px solid #ffffff10;border-radius:12px;padding:9px}.hud b{display:block;font-size:18px}.stage{position:relative;border:1px solid #ffffff14;border-radius:22px;overflow:hidden;background:#000}.stage canvas{width:100%;display:block;touch-action:none}.overlay{position:absolute;inset:0;background:#000b;display:grid;place-content:center;text-align:center;gap:12px}.overlay b{font-size:38px}.overlay button,.actions button,.dpad button{min-height:48px;border:1px solid #ffffff16;border-radius:13px;background:#10251c;color:#fff;font-weight:900}.controls{display:grid;grid-template-columns:190px 1fr;gap:12px;margin-top:10px}.dpad{display:grid;grid-template-columns:repeat(3,52px);grid-template-rows:repeat(3,52px);gap:4px}.dpad button:nth-of-type(1){grid-column:2}.dpad button:nth-of-type(2){grid-row:2;grid-column:1}.dpad button:nth-of-type(3){grid-row:2;grid-column:3}.dpad button:nth-of-type(4){grid-row:3;grid-column:2}.actions{display:flex;gap:8px;flex-wrap:wrap;align-content:center}.actions button{padding:0 20px}.actions .primary{background:#b3483f}.notice{padding:10px 0;font-size:11px}@media(max-width:620px){header{display:grid}.controls{grid-template-columns:1fr}.dpad{margin:auto}.actions{justify-content:center}}`}</style>
  </main>;
}

function PuzzleView({config,state,setState,restart,notice,setNotice}){
  function cell(x,y){const next=puzzleMove(state,x,y);setState(next);if(next.status==="won")setNotice("Puzzle target cleared.");else if(next.status==="lost")setNotice("No moves left. Restart or undo earlier.")}
  function hint(){const next=puzzleHint(state);setState(next);setNotice(next.hint?`Hint: swap (${next.hint.a.x+1},${next.hint.a.y+1}) with (${next.hint.b.x+1},${next.hint.b.y+1}).`:"No simple hint found; board remains playable.")}
  function undo(){const next=puzzleUndo(state);setState(next);setNotice(next===state?"No undo available.":"Last move restored.")}
  return <main className="puzzleShell"><header><div><small>SOOLENAI · PUZZLE / BRAIN RUNTIME V1</small><h1>{config.title}</h1><p>Deterministic board · Match logic · Hint · Undo · Completion evidence</p></div><span>iOS · Android · Web Preview</span></header><section className="puzzleHud"><b>Score {state.score}/{state.targetScore}</b><b>Moves {state.moves}</b><b>Hints {state.hints}</b><b>Undo {state.undos}</b></section><section className="board" aria-label="Puzzle board">{state.board.map((row,y)=>row.map((value,x)=><button key={`${x}-${y}`} aria-label={`Puzzle cell ${x+1}, ${y+1}`} className={state.selected?.x===x&&state.selected?.y===y?"selected":""} onClick={()=>cell(x,y)}><i data-v={value}/></button>))}</section><section className="puzzleActions"><button onClick={hint}>HINT</button><button onClick={undo}>UNDO</button><button onClick={restart}>RESTART</button></section><p className="pnotice">{notice||"Select two adjacent pieces to swap."}</p>{state.status!=="playing"&&<div className="result"><b>{state.status==="won"?"PUZZLE COMPLETE":"TRY AGAIN"}</b><button onClick={restart}>New Board</button></div>}<style jsx>{`.puzzleShell{min-height:100vh;background:#050916;color:#eef2ff;padding:20px max(14px,env(safe-area-inset-right)) calc(25px + env(safe-area-inset-bottom)) max(14px,env(safe-area-inset-left));font-family:Inter,system-ui}header,.puzzleHud,.board,.puzzleActions,.pnotice{max-width:760px;margin:auto}header{display:flex;justify-content:space-between;gap:12px;align-items:end;padding:20px 0}small{color:#f0d56d;font-size:9px;font-weight:900;letter-spacing:.1em}h1{font-size:clamp(32px,6vw,62px);margin:4px 0}p{color:#9aa6c5}.puzzleHud{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:12px}.puzzleHud b{border:1px solid #ffffff14;border-radius:999px;padding:8px 12px;font-size:11px}.board{display:grid;grid-template-columns:repeat(6,1fr);gap:7px;background:#0a1027;border:1px solid #ffffff12;border-radius:24px;padding:14px}.board button{aspect-ratio:1;border:1px solid #ffffff15;border-radius:14px;background:#101a38;display:grid;place-items:center;min-width:0}.board button.selected{outline:3px solid #f0d56d}.board i{width:54%;height:54%;border-radius:30%;background:hsl(calc(var(--v,0)*65deg),70%,60%)}.board i[data-v="0"]{background:#ff6d6d}.board i[data-v="1"]{background:#65d4ff}.board i[data-v="2"]{background:#7ce08b}.board i[data-v="3"]{background:#f0d56d}.board i[data-v="4"]{background:#b887ff}.puzzleActions{display:flex;gap:8px;margin-top:12px}.puzzleActions button,.result button{min-height:48px;border:1px solid #ffffff18;border-radius:13px;background:#172348;color:#fff;font-weight:900;padding:0 20px}.pnotice{font-size:11px}.result{position:fixed;inset:0;background:#02040bd9;display:grid;place-content:center;gap:15px;text-align:center}.result b{font-size:40px}@media(max-width:520px){header{display:grid}.board{gap:5px;padding:9px;border-radius:17px}.board button{border-radius:10px}}`}</style></main>;
}
