import { createHash } from "node:crypto";
import { NextResponse } from "next/server";
import { createClient } from "../../../../lib/supabase/server.js";

const MAX_REQUEST_BYTES=9*1024*1024;
const MAX_IMAGE_BYTES=8*1024*1024;
const REQUEST_ID=/^[a-zA-Z0-9._:-]{1,160}$/;
const MIME_EXT=new Map([["image/png","png"],["image/jpeg","jpg"],["image/webp","webp"],["image/svg+xml","svg"]]);
function noStore(payload,status=200){return NextResponse.json(payload,{status,headers:{"Cache-Control":"private, no-store, max-age=0","Pragma":"no-cache","X-Content-Type-Options":"nosniff"}});}
function cleanText(value,max=180){return String(value||"").replace(/[\u0000-\u001f\u007f]/g," ").trim().slice(0,max);}
function sanitizeSvg(text){const svg=String(text||"").trim();if(!svg.startsWith("<svg")||svg.length>1024*1024)throw new Error("INVALID_SVG");if(/<script|<foreignObject|<iframe|<object|<embed|javascript:|\son[a-z]+\s*=|(?:href|xlink:href)\s*=\s*["'](?:https?:|\/\/)/i.test(svg))throw new Error("UNSAFE_SVG");return svg;}
function imageSignatureMatches(mime,buffer){if(!Buffer.isBuffer(buffer)||!buffer.length)return false;if(mime==="image/png")return buffer.length>=8&&buffer.subarray(0,8).toString("hex")==="89504e470d0a1a0a";if(mime==="image/jpeg")return buffer.length>=3&&buffer[0]===0xff&&buffer[1]===0xd8&&buffer[2]===0xff;if(mime==="image/webp")return buffer.length>=12&&buffer.subarray(0,4).toString("ascii")==="RIFF"&&buffer.subarray(8,12).toString("ascii")==="WEBP";if(mime==="image/svg+xml")return buffer.subarray(0,Math.min(buffer.length,256)).toString("utf8").trimStart().startsWith("<svg");return false;}
function parseDataImage(image){const raw=String(image||"");const match=raw.match(/^data:(image\/(?:png|jpeg|webp|svg\+xml))(?:;charset=[^;,]+)?(;base64)?,(.*)$/is);if(!match)return null;const mime=match[1].toLowerCase();let buffer;if(mime==="image/svg+xml"){const decoded=match[2]?Buffer.from(match[3],"base64").toString("utf8"):decodeURIComponent(match[3]);buffer=Buffer.from(sanitizeSvg(decoded),"utf8");}else{if(!match[2])throw new Error("INVALID_IMAGE_BYTES");buffer=Buffer.from(match[3],"base64");}if(!buffer.length||buffer.length>MAX_IMAGE_BYTES)throw new Error("IMAGE_TOO_LARGE");if(!imageSignatureMatches(mime,buffer))throw new Error("INVALID_IMAGE_BYTES");return{mime,buffer};}
function allowedOutputHost(raw){const value=String(raw||"").trim();if(!value||value.length>4000)throw new Error("INVALID_IMAGE_URL");let url;try{url=new URL(value);}catch{throw new Error("INVALID_IMAGE_URL");}if(url.protocol!=="https:"||url.username||url.password)throw new Error("INVALID_IMAGE_URL");const allow=new Set(String(process.env.IMAGE_GENERATION_OUTPUT_HOST_ALLOWLIST||"").split(",").map(v=>v.trim().toLowerCase()).filter(Boolean));try{const endpoint=new URL(String(process.env.IMAGE_GENERATION_ENDPOINT||""));if(endpoint.protocol==="https:")allow.add(endpoint.hostname.toLowerCase());}catch{}if(!allow.has(url.hostname.toLowerCase()))throw new Error("IMAGE_OUTPUT_HOST_NOT_ALLOWED");return url.toString();}
async function fetchRemoteImage(raw){const url=allowedOutputHost(raw);const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),20000);try{const response=await fetch(url,{cache:"no-store",redirect:"error",signal:controller.signal,headers:{Accept:"image/png,image/jpeg,image/webp"}});if(!response.ok)throw new Error("IMAGE_FETCH_FAILED");const mime=String(response.headers.get("content-type")||"").split(";")[0].toLowerCase();if(!MIME_EXT.has(mime)||mime==="image/svg+xml")throw new Error("IMAGE_TYPE_NOT_ALLOWED");const length=Number(response.headers.get("content-length")||0);if(length>MAX_IMAGE_BYTES)throw new Error("IMAGE_TOO_LARGE");const buffer=Buffer.from(await response.arrayBuffer());if(!buffer.length||buffer.length>MAX_IMAGE_BYTES)throw new Error("IMAGE_TOO_LARGE");if(!imageSignatureMatches(mime,buffer))throw new Error("INVALID_IMAGE_BYTES");return{mime,buffer};}finally{clearTimeout(timer);}}

export async function POST(request){
  try{
    const contentLength=Number(request.headers.get("content-length")||0);if(contentLength>MAX_REQUEST_BYTES)return noStore({error:"Image save request is too large."},413);
    const supabase=await createClient();const{data:{user},error:userError}=await supabase.auth.getUser();if(userError||!user)return noStore({error:"Authentication required."},401);
    const body=await request.json().catch(()=>null);if(!body)return noStore({error:"Invalid image save request."},400);if(Buffer.byteLength(JSON.stringify(body),"utf8")>MAX_REQUEST_BYTES)return noStore({error:"Image save request is too large."},413);
    const requestId=cleanText(body?.requestId,160);if(!REQUEST_ID.test(requestId))return noStore({error:"A stable image save request ID is required."},400);
    const image=String(body?.image||"").trim();if(!image)return noStore({error:"Generated image is required."},400);
    const parsed=image.startsWith("data:image/")?parseDataImage(image):await fetchRemoteImage(image);if(!parsed)return noStore({error:"Unsupported generated image format."},400);
    const fingerprint=createHash("sha256").update(parsed.buffer).digest("hex");
    const{data:existing,error:existingError}=await supabase.from("asset_library").select("id,file_name,storage_path,mime_type,file_size,category,created_at").eq("user_id",user.id).eq("content_fingerprint",fingerprint).maybeSingle();if(existingError)throw new Error("ASSET_LOOKUP_FAILED");if(existing)return noStore({success:true,replayed:true,asset:existing});
    const mode=cleanText(body?.mode,40)||"image",style=cleanText(body?.style,40)||"generated";const ext=MIME_EXT.get(parsed.mime)||"bin";const safeRequest=requestId.replace(/[^a-zA-Z0-9._-]/g,"-").slice(0,80);const fileName=`LANERIQ-${mode}-${safeRequest}.${ext}`.slice(0,180);const storagePath=`${user.id}/${crypto.randomUUID()}-${fileName}`;
    const{error:uploadError}=await supabase.storage.from("user-assets").upload(storagePath,parsed.buffer,{contentType:parsed.mime,upsert:false,cacheControl:"3600"});if(uploadError)throw new Error("PRIVATE_IMAGE_UPLOAD_FAILED");
    const intelligence={purpose:"image_studio_generated",generated:true,mode,style,reusableAcrossUsers:false,rawPrivateAssetsReusableAcrossCustomers:false,privateCustomerAsset:true,source:body?.source==="model"?"model":"local"};
    const{data:asset,error:dbError}=await supabase.from("asset_library").insert({user_id:user.id,file_name:fileName,storage_path:storagePath,mime_type:parsed.mime,file_size:parsed.buffer.length,category:"image",alt_text:cleanText(body?.altText,240)||`Generated ${mode} visual`,intelligence,content_fingerprint:fingerprint}).select("id,file_name,storage_path,mime_type,file_size,category,created_at").single();
    if(dbError){await supabase.storage.from("user-assets").remove([storagePath]);if(String(dbError.code||"")==="23505"){const{data:replayed}=await supabase.from("asset_library").select("id,file_name,storage_path,mime_type,file_size,category,created_at").eq("user_id",user.id).eq("content_fingerprint",fingerprint).maybeSingle();if(replayed)return noStore({success:true,replayed:true,asset:replayed});}throw new Error("ASSET_METADATA_SAVE_FAILED");}
    return noStore({success:true,replayed:false,asset});
  }catch(error){console.error("IMAGE_STUDIO_SAVE_ERROR",String(error?.message||"unknown").slice(0,120));const code=String(error?.message||"");if(code==="IMAGE_OUTPUT_HOST_NOT_ALLOWED")return noStore({error:"This model output host is not approved for private library import yet."},409);if(code==="IMAGE_TOO_LARGE")return noStore({error:"Generated image is too large to save."},413);if(["INVALID_SVG","UNSAFE_SVG","IMAGE_TYPE_NOT_ALLOWED","INVALID_IMAGE_URL","INVALID_IMAGE_BYTES"].includes(code))return noStore({error:"Generated image format is not safe to save."},400);return noStore({error:"Unable to save this image to your private Asset Library right now."},500);}
}
