// Soolen Isolation Provider job lifecycle. This is control logic only; a platform adapter must supply real microVM/container operations.
import crypto from "node:crypto";
const TERMINAL=new Set(["destroyed","failed","expired"]),TRANSITIONS={created:new Set(["uploading","destroying","failed"]),uploading:new Set(["ready","destroying","failed"]),ready:new Set(["building","testing","destroying","failed"]),building:new Set(["ready","destroying","failed"]),testing:new Set(["ready","destroying","failed"]),destroying:new Set(["destroyed","failed"])};
function now(){return Date.now();}function clamp(v,d,min,max){const n=Number(v);return Number.isFinite(n)?Math.max(min,Math.min(n,max)):d;}function clean(v){return String(v||"").replace(/(?:bearer\s+\S+|api[_-]?key\s*[:=]\s*\S+|token\s*[:=]\s*\S+|password\s*[:=]\s*\S+)/gi,"[REDACTED]").slice(0,1000);}
export function createJobManager(adapter,{maxJobs=50}={}){const jobs=new Map();function transition(job,next){if(TERMINAL.has(job.state)||!TRANSITIONS[job.state]?.has(next))throw new Error("INVALID_JOB_TRANSITION");job.state=next;job.updatedAt=now();}async function destroy(job,reason="cleanup"){if(!job||TERMINAL.has(job.state))return;try{transition(job,"destroying");await adapter.destroy(job.platformId);transition(job,"destroyed");job.destroyReason=clean(reason);}catch{job.state="failed";job.updatedAt=now();job.destroyReason="destroy-failed";}}
async function reap(){for(const job of jobs.values())if(!TERMINAL.has(job.state)&&job.expiresAt<=now())await destroy(job,"ttl-expired");for(const [id,job] of jobs)if(TERMINAL.has(job.state)&&job.updatedAt<now()-10*60*1000)jobs.delete(id);}
async function create({workspaceId,limits={}}={}){await reap();const live=[...jobs.values()].filter(j=>!TERMINAL.has(j.state));if(live.length>=maxJobs)throw new Error("JOB_LIMIT_REACHED");const ttlMs=clamp(limits.ttlMs||limits.jobTtlMs,180000,30000,300000),id=crypto.randomUUID(),platformId=await adapter.create({jobId:id,workspaceId:clean(workspaceId),limits:{...limits,network:"deny",nonRoot:true,noHostMounts:true,noDockerSocket:true,noSecrets:true}});if(!platformId)throw new Error("PLATFORM_JOB_NOT_CREATED");jobs.set(id,{id,platformId,state:"created",createdAt:now(),updatedAt:now(),expiresAt:now()+ttlMs});return id;}
function requireJob(id){const job=jobs.get(String(id||""));if(!job||TERMINAL.has(job.state))throw new Error("JOB_NOT_AVAILABLE");if(job.expiresAt<=now())throw new Error("JOB_EXPIRED");return job;}
async function putFiles(id,files){const job=requireJob(id);transition(job,"uploading");try{await adapter.putFiles(job.platformId,files);transition(job,"ready");return {passed:true,status:"files-ready"};}catch(e){job.state="failed";job.updatedAt=now();throw new Error(clean(e?.message||"FILE_UPLOAD_FAILED"));}}
async function run(id,kind,options){const job=requireJob(id);if(job.state!=="ready")throw new Error("JOB_NOT_READY");transition(job,kind==="build"?"building":"testing");try{const result=kind==="build"?await adapter.build(job.platformId,options):await adapter.browserTest(job.platformId,options);transition(job,"ready");return result;}catch(e){job.state="failed";job.updatedAt=now();throw new Error(clean(e?.message||`${kind}-failed`));}}
return {createJob:create,putFiles,runBuild:(id,o)=>run(id,"build",o),runBrowserTests:(id,o)=>run(id,"test",o),destroyJob:async id=>{const job=jobs.get(String(id||""));if(job)await destroy(job,"requested");return {passed:true,status:"destroyed"};},reap,status:id=>{const j=jobs.get(String(id||""));return j?{id:j.id,state:j.state,createdAt:j.createdAt,updatedAt:j.updatedAt,expiresAt:j.expiresAt}:null;}};}
