-- Store listing data is generated by AI and reviewed by the customer before publishing.
-- Store credentials/signing secrets are never stored in these tables.
create table if not exists public.store_listings (
  id uuid primary key default gen_random_uuid(),
  app_id uuid not null references public.apps(id) on delete cascade,
  version_id uuid references public.app_versions(id) on delete set null,
  language text not null default 'en',
  apple jsonb not null default '{}'::jsonb,
  google_play jsonb not null default '{}'::jsonb,
  checklist jsonb not null default '[]'::jsonb,
  customer_approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (app_id, version_id, language)
);
create table if not exists public.publish_requests (
  id uuid primary key default gen_random_uuid(),
  app_id uuid not null references public.apps(id) on delete cascade,
  version_id uuid references public.app_versions(id) on delete set null,
  store_listing_id uuid references public.store_listings(id) on delete set null,
  platform text not null check (platform in ('apple','google_play')),
  status text not null default 'draft' check (status in ('draft','customer_approved','building','testing','ready','submitted','published','rejected','failed','cancelled')),
  requested_by uuid not null references auth.users(id),
  customer_approved_at timestamptz,
  submitted_at timestamptz,
  published_at timestamptz,
  failure_reason text,
  provider_reference text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists store_listings_app_idx on public.store_listings(app_id, created_at desc);
create index if not exists publish_requests_app_idx on public.publish_requests(app_id, created_at desc);
alter table public.store_listings enable row level security;
alter table public.publish_requests enable row level security;
revoke all on public.store_listings from anon, authenticated;
revoke all on public.publish_requests from anon, authenticated;
grant select on public.store_listings to authenticated;
grant select on public.publish_requests to authenticated;
create policy "Users can view their own store listings" on public.store_listings for select to authenticated using (exists (select 1 from public.apps a where a.id = store_listings.app_id and a.owner_id = (select auth.uid())));
create policy "Users can view their own publish requests" on public.publish_requests for select to authenticated using ((select auth.uid()) = requested_by);
create or replace function public.approve_store_listing(p_listing_id uuid)
returns public.store_listings language plpgsql security definer set search_path = '' as $$
declare uid uuid := auth.uid(); listing public.store_listings;
begin
  select sl.* into listing from public.store_listings sl join public.apps a on a.id = sl.app_id where sl.id = p_listing_id and a.owner_id = uid for update;
  if not found then raise exception 'Store listing not found'; end if;
  update public.store_listings set customer_approved_at = coalesce(customer_approved_at, now()), updated_at = now() where id = p_listing_id returning * into listing;
  return listing;
end; $$;
revoke all on function public.approve_store_listing(uuid) from public, anon;
grant execute on function public.approve_store_listing(uuid) to authenticated;
