"use client";

import Link from "next/link";
import { useEffect,useMemo,useState } from "react";

const STATUS_LABELS={ready:"Ready",preparable:"AI can prepare",customer_required:"Customer confirm",external_required:"External step"};

export default function PublishingReadinessPanel({appId}){
  const[open,setOpen]=useState(false);const[data,setData]=useState(null);const[error,setError]=useState("");
  useEffect(()=>{let active=true;(async()=>{try{const response=await fetch(`/api/apps/${appId}/publishing-agent`,{cache:"no-store"});const json=await response.json();if(!response.ok)throw new Error(json?.error||"Unable to check store readiness.");if(active)setData(json)}catch(err){if(active)setError(err.message)}})();return()=>{active=false}},[appId]);
  const readiness=data?.storeReadiness;const checks=Array.isArray(readiness?.checks)?readiness.checks:[];
  const grouped=useMemo(()=>({preparable:checks.filter(x=>x.status==="preparable"),customer:checks.filter(x=>x.status==="customer_required"),external:checks.filter(x=>x.status==="external_required"),ready:checks.filter(x=>x.status==="ready")}),[checks]);
  if(error)return null;
  const score=Number(readiness?.readinessScore||0);
  return <div className={`storeReadinessDock ${open?"open":""}`}>
    <button className="storeReadinessToggle" onClick={()=>setOpen(value=>!value)} aria-expanded={open}><span>STORE READINESS</span><b>{data?`${score}%`:"…"}</b></button>
    {open&&<section className="storeReadinessPanel"><div className="head"><div><small>AI PUBLISHING AGENT</small><h2>What is still missing?</h2></div><button onClick={()=>setOpen(false)}>×</button></div>
      {!data?<p>Checking the current saved version…</p>:<>
        <div className="summary"><span><b>{grouped.ready.length}</b> ready</span><span><b>{grouped.preparable.length}</b> AI can prepare</span><span><b>{grouped.customer.length}</b> customer</span><span><b>{grouped.external.length}</b> external</span></div>
        <div className="rows">{checks.map(item=><article key={item.key} className={item.status}><div><strong>{item.label}</strong><small>{item.reason}</small></div><b>{STATUS_LABELS[item.status]||item.status}</b></article>)}</div>
        {grouped.preparable.length>0&&<div className="prepare"><strong>AI-preparable items</strong><p>SoolenAI may prepare drafts/candidates, but real store assets and signed release values still need review.</p><div><Link href="/image-studio">Create Icon / Screenshots</Link><Link href={{pathname:`/editor/${appId}`,query:{instruction:"Prepare every AI-preparable store release item for this project without inventing external credentials, signed build evidence or official submission success. Keep all customer declarations for customer review."}}}>✨ Prepare with AI</Link></div></div>}
        {(readiness?.permissionRequirements||[]).length>0&&<div className="permissions"><strong>Detected device permissions</strong>{readiness.permissionRequirements.map(item=><span key={item.key}>{item.label} · customer must confirm the real purpose</span>)}</div>}
        <p className="truth">Official App Store / Google Play submission remains <b>not completed</b> until the customer's developer accounts, signing, declarations and platform actions are verified.</p>
      </>}
    </section>}
    <style jsx>{`.storeReadinessDock{position:fixed;right:14px;top:104px;z-index:90;font-family:Inter,system-ui,-apple-system,sans-serif;color:#effaf5}.storeReadinessToggle{display:flex;align-items:center;gap:10px;border:1px solid #d8bf6250;border-radius:999px;background:#061a14ee;color:#d8bf62;padding:9px 11px;box-shadow:0 12px 34px #0007;backdrop-filter:blur(16px)}.storeReadinessToggle span{font-size:9px;letter-spacing:.14em;font-weight:900}.storeReadinessToggle b{font-size:15px}.storeReadinessPanel{width:min(430px,calc(100vw - 28px));max-height:72vh;overflow:auto;margin-top:8px;padding:18px;border:1px solid #d8bf6245;border-radius:20px;background:#04130fee;box-shadow:0 24px 70px #0009;backdrop-filter:blur(22px)}.head{display:flex;justify-content:space-between;gap:12px}.head small{color:#d8bf62;font-size:9px;letter-spacing:.16em;font-weight:900}.head h2{margin:5px 0 10px;font-size:25px}.head>button{width:32px;height:32px;border:1px solid #ffffff20;border-radius:10px;background:transparent;color:#fff;font-size:20px}.summary{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin:8px 0 12px}.summary span{padding:9px;border-radius:11px;background:#0a251c;color:#8fa79d;font-size:10px}.summary b{display:block;color:#fff;font-size:18px}.rows{display:grid;gap:6px}.rows article{display:flex;justify-content:space-between;gap:10px;padding:10px;border-radius:12px;border:1px solid #ffffff10;background:#071b15}.rows strong,.rows small{display:block}.rows strong{font-size:12px}.rows small{margin-top:3px;color:#82988f;line-height:1.35;font-size:9px}.rows article>b{height:max-content;white-space:nowrap;font-size:9px;border-radius:999px;padding:5px 7px;color:#d8bf62;background:#d8bf6212}.rows article.ready>b{color:#85ddb7;background:#85ddb712}.rows article.customer_required>b{color:#f1c66e}.rows article.external_required>b{color:#ffaaa1}.prepare,.permissions{margin-top:12px;padding:12px;border-radius:13px;background:#0b261d;border:1px solid #ffffff10}.prepare strong,.permissions strong{display:block;color:#d8bf62;font-size:11px}.prepare p{color:#8da39a;font-size:10px;line-height:1.4}.prepare>div{display:flex;gap:7px;flex-wrap:wrap}.prepare a{border-radius:9px;padding:8px 9px;background:#d8bf62;color:#07130e;text-decoration:none;font-size:10px;font-weight:900}.permissions span{display:block;color:#9db1a8;font-size:10px;margin-top:6px}.truth{font-size:10px;line-height:1.45;color:#8ea39a;margin:12px 2px 0}.truth b{color:#ffb4aa}@media(max-width:620px){.storeReadinessDock{top:auto;right:10px;bottom:138px}.storeReadinessPanel{max-height:62vh}.storeReadinessToggle{margin-left:auto}.summary{grid-template-columns:1fr 1fr}}`}</style>
  </div>;
}
