"use client";

import {useEffect,useRef,useState} from "react";
import {classifyRuntimeDeviceV6,createAdaptiveRuntimeBudgetV6,applyRuntimeFeedbackV6,buildThermalPressureProxyV6} from "../../lib/game/game-world-mobile-adaptive-v6.js";
import {createRuntimeEvidenceSessionV6,recordBrowserContextV6,recordFrameSampleV6,attachRuntimeSubsystemEvidenceV6,sanitizeRuntimeEvidenceForExportV6} from "../../lib/game/game-world-runtime-evidence-v6.js";
import styles from "./runtime-v6.module.css";

function mul(a,b){const o=new Float32Array(16);for(let r=0;r<4;r++)for(let c=0;c<4;c++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o;}
function perspective(fov,aspect,near,far){const f=1/Math.tan(fov/2),nf=1/(near-far);return new Float32Array([f/aspect,0,0,0,0,f,0,0,0,0,(far+near)*nf,-1,0,0,2*far*near*nf,0]);}
function lookAt(e,c){let zx=e[0]-c[0],zy=e[1]-c[1],zz=e[2]-c[2],l=Math.hypot(zx,zy,zz)||1;zx/=l;zy/=l;zz/=l;let xx=zz,xz=-zx;l=Math.hypot(xx,xz)||1;xx/=l;xz/=l;const yx=zy*xz,yy=zz*xx-zx*xz,yz=-zy*xx;return new Float32Array([xx,yx,zx,0,0,yy,zy,0,xz,yz,zz,0,-(xx*e[0]+xz*e[2]),-(yx*e[0]+yy*e[1]+yz*e[2]),-(zx*e[0]+zy*e[1]+zz*e[2]),1]);}
function makeShader(gl,type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s)||"shader compile failed");return s;}
function makeProgram(gl){const vs=makeShader(gl,gl.VERTEX_SHADER,`attribute vec3 aPosition;attribute vec3 aColor;uniform mat4 uVP;varying vec3 vColor;void main(){vColor=aColor;gl_Position=uVP*vec4(aPosition,1.0);}`),fs=makeShader(gl,gl.FRAGMENT_SHADER,`precision mediump float;varying vec3 vColor;void main(){gl_FragColor=vec4(vColor,1.0);}`),p=gl.createProgram();gl.attachShader(p,vs);gl.attachShader(p,fs);gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p)||"program link failed");return p;}
function height(x,z,seed){return Math.sin((x+seed%97)*.026)*5+Math.cos((z-seed%83)*.021)*4+Math.sin((x+z)*.012)*2;}
function geometry(chunk,grid){const out=[],size=chunk.size,step=size/grid,x0=chunk.center[0]-size/2,z0=chunk.center[2]-size/2;const push=(x,z)=>{const y=height(x,z,chunk.heightSeed),h=Math.min(1,Math.abs(y)/12);out.push(x,y,z,.10+.20*h,.32+.36*(1-h),.23+.18*(1-h));};for(let z=0;z<grid;z++)for(let x=0;x<grid;x++){const ax=x0+x*step,bx=ax+step,az=z0+z*step,bz=az+step;push(ax,az);push(bx,az);push(ax,bz);push(bx,az);push(bx,bz);push(ax,bz);}return new Float32Array(out);}
function buffer(gl,data){const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,data,gl.STATIC_DRAW);return{b,count:data.length/6};}
function rendererClass(gl){try{const ext=gl.getExtension("WEBGL_debug_renderer_info"),raw=ext?String(gl.getParameter(ext.UNMASKED_RENDERER_WEBGL)||""):"";return /swiftshader|llvmpipe|software/i.test(raw)?"software":raw?"hardware-or-driver":"unknown";}catch{return"unknown";}}

export default function RuntimeV6Canvas({runtime}){
  const canvasRef=useRef(null),control=useRef({keys:new Set(),yaw:Math.PI,pitch:-.18,pos:[0,10,28],drag:false,x:0,y:0});
  const [ui,setUi]=useState({api:"starting",fps:0,resident:0,profile:runtime.adaptive.profile,scale:runtime.adaptive.renderScale,pressure:"normal",rendererClass:"unknown",error:""});
  useEffect(()=>{
    const canvas=canvasRef.current;if(!canvas)return;
    const gl2=canvas.getContext("webgl2",{antialias:true,powerPreference:"high-performance"});const gl=gl2||canvas.getContext("webgl",{antialias:true,powerPreference:"high-performance"});
    if(!gl){setUi(x=>({...x,api:"unavailable",error:"WebGL unavailable"}));return;}
    let prog;try{prog=makeProgram(gl);}catch(e){setUi(x=>({...x,api:"shader-error",error:String(e.message||e)}));return;}
    const signals={touch:matchMedia?.("(pointer: coarse)")?.matches===true,hardwareConcurrency:navigator.hardwareConcurrency||4,deviceMemoryGb:navigator.deviceMemory||4,maxTextureSize:gl.getParameter(gl.MAX_TEXTURE_SIZE)||4096,webgl2:Boolean(gl2),viewportPixels:Math.max(1,innerWidth*innerHeight)};
    const classified=classifyRuntimeDeviceV6(signals);let budget=createAdaptiveRuntimeBudgetV6({profile:runtime.requestedProfile==="auto"?classified.profile:runtime.adaptive.profile});
    let evidence=createRuntimeEvidenceSessionV6({worldId:runtime.worldId,route:"/game-world-v6",source:"browser"});const rClass=rendererClass(gl);evidence=recordBrowserContextV6(evidence,{contextCreated:true,api:gl2?"WebGL2":"WebGL1",rendererClass:rClass,webgl2:Boolean(gl2),maxTextureSize:signals.maxTextureSize});evidence=attachRuntimeSubsystemEvidenceV6(evidence,{navPathPoints:runtime.navPathPoints,physicsBodies:runtime.physicsBodies,adaptiveProfile:budget.profile});
    const pos=gl.getAttribLocation(prog,"aPosition"),col=gl.getAttribLocation(prog,"aColor"),vp=gl.getUniformLocation(prog,"uVP");
    const chunks=(runtime.terrain.chunks||[]).map(c=>({...c,gpu:buffer(gl,geometry(c,Math.min(c.grid||16,budget.terrainGrid||16)))}));gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);gl.clearColor(.018,.034,.052,1);
    control.current.pos=[...(runtime.spawn?.position||[0,10,28])];
    const kd=e=>{control.current.keys.add(e.key.toLowerCase());},ku=e=>control.current.keys.delete(e.key.toLowerCase());
    const pd=e=>{control.current.drag=true;control.current.x=e.clientX;control.current.y=e.clientY;},pm=e=>{const s=control.current;if(!s.drag)return;s.yaw-=(e.clientX-s.x)*.005;s.pitch=Math.max(-1,Math.min(.55,s.pitch-(e.clientY-s.y)*.004));s.x=e.clientX;s.y=e.clientY;},pu=()=>control.current.drag=false;
    addEventListener("keydown",kd);addEventListener("keyup",ku);canvas.addEventListener("pointerdown",pd);addEventListener("pointermove",pm);addEventListener("pointerup",pu);
    let raf=0,last=performance.now(),windowStart=last,frames=0,longFrames=0,frameTotal=0,samples=[];
    const bind=x=>{gl.bindBuffer(gl.ARRAY_BUFFER,x.b);gl.enableVertexAttribArray(pos);gl.vertexAttribPointer(pos,3,gl.FLOAT,false,24,0);gl.enableVertexAttribArray(col);gl.vertexAttribPointer(col,3,gl.FLOAT,false,24,12);};
    const loop=now=>{const ms=Math.min(100,now-last),dt=ms/1000;last=now;frameTotal+=ms;if(ms>34)longFrames++;frames++;const s=control.current,k=s.keys,spd=(k.has("shift")?26:14)*dt,fx=Math.sin(s.yaw),fz=-Math.cos(s.yaw),rx=Math.cos(s.yaw),rz=Math.sin(s.yaw);let f=0,q=0;if(k.has("w")||k.has("arrowup"))f++;if(k.has("s")||k.has("arrowdown"))f--;if(k.has("d")||k.has("arrowright"))q++;if(k.has("a")||k.has("arrowleft"))q--;s.pos[0]+=(fx*f+rx*q)*spd;s.pos[2]+=(fz*f+rz*q)*spd;s.pos[1]=height(s.pos[0],s.pos[2],chunks[0]?.heightSeed||1)+8;
      const dpr=Math.min(2,devicePixelRatio||1),scale=Math.max(.5,Math.min(1.05,budget.renderScale||.8)),w=Math.max(2,Math.floor(canvas.clientWidth*dpr*scale)),h=Math.max(2,Math.floor(canvas.clientHeight*dpr*scale));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}gl.viewport(0,0,w,h);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.useProgram(prog);const dir=[Math.sin(s.yaw)*Math.cos(s.pitch),Math.sin(s.pitch),-Math.cos(s.yaw)*Math.cos(s.pitch)],center=[s.pos[0]+dir[0],s.pos[1]+dir[1],s.pos[2]+dir[2]];gl.uniformMatrix4fv(vp,false,mul(perspective(Math.PI/3,w/h,.1,700),lookAt(s.pos,center)));let resident=0;for(const c of chunks){if(Math.hypot(s.pos[0]-c.center[0],s.pos[2]-c.center[2])>c.size*2.15)continue;if(resident>=budget.maxResidentChunks)break;resident++;bind(c.gpu);gl.drawArrays(gl.TRIANGLES,0,c.gpu.count);}
      if(now-windowStart>=800){const elapsed=now-windowStart,fps=Math.round(frames*1000/elapsed),avgMs=frameTotal/Math.max(1,frames),longFrameRatio=longFrames/Math.max(1,frames);budget=applyRuntimeFeedbackV6(budget,{fps,longFrameRatio});samples.push({fps,longFrameRatio});evidence=recordFrameSampleV6(evidence,{fps,frameMs:avgMs,longFrameRatio,residentChunks:resident,renderScale:budget.renderScale,atMs:now});const thermal=buildThermalPressureProxyV6(samples);const exported=sanitizeRuntimeEvidenceForExportV6(evidence);window.__LANERIQ_V6_EVIDENCE__={...exported,thermalProxy:thermal};setUi({api:gl2?"WebGL2 LIVE":"WebGL1 LIVE",fps,resident,profile:budget.profile,scale:budget.renderScale,pressure:budget.pressure,rendererClass:rClass,error:""});frames=0;longFrames=0;frameTotal=0;windowStart=now;}raf=requestAnimationFrame(loop);};raf=requestAnimationFrame(loop);
    return()=>{cancelAnimationFrame(raf);removeEventListener("keydown",kd);removeEventListener("keyup",ku);canvas.removeEventListener("pointerdown",pd);removeEventListener("pointermove",pm);removeEventListener("pointerup",pu);for(const c of chunks)gl.deleteBuffer(c.gpu.b);gl.deleteProgram(prog);};
  },[runtime]);
  const hold=(key,on)=>()=>{if(on)control.current.keys.add(key);else control.current.keys.delete(key);};
  return <div className={styles.runtime} data-testid="runtime-v6"><canvas ref={canvasRef} className={styles.canvas} data-testid="runtime-v6-canvas" aria-label="LANERIQ Game World V6 runtime"/><div className={styles.hud} data-testid="gpu-status" data-api={ui.api} data-fps={ui.fps} data-resident={ui.resident} data-renderer-class={ui.rendererClass}><b>{ui.api}</b><span>{ui.fps?`${ui.fps} FPS`:"measuring"}</span><span>{ui.resident} chunks</span><span>{ui.profile} · scale {Number(ui.scale).toFixed(2)}</span><span>pressure {ui.pressure}</span>{ui.error?<em>{ui.error}</em>:null}</div><div className={styles.touch} aria-label="Touch movement controls"><button onPointerDown={hold("w",true)} onPointerUp={hold("w",false)} onPointerCancel={hold("w",false)}>↑</button><div><button onPointerDown={hold("a",true)} onPointerUp={hold("a",false)}>←</button><button onPointerDown={hold("s",true)} onPointerUp={hold("s",false)}>↓</button><button onPointerDown={hold("d",true)} onPointerUp={hold("d",false)}>→</button></div></div></div>;
}
