import Link from "next/link";
import { PRODUCT_POLICY } from "../../config/product-policy.js";

export default function PricingPage(){
  const pricing=PRODUCT_POLICY.pricing;
  const promo=PRODUCT_POLICY.promotion.freeFirstProject;
  return <main className="page"><div className="bg"/><div className="wrap">
    <header><Link href="/">← LANERIQ AI</Link><span>SOOLENAI</span></header>
    <section className="hero"><small>FAIR PRICE · FAIR USE</small><h1>Build your first project.<br/><em>Free until you publish.</em></h1><p>Eligible customers can create one App + Website, keep asking AI to refine it until it fits their needs, preview it, run quality checks and complete the SoolenAI publishing flow without a Standard creation charge. Fair Use applies.</p><div className="promo"><b>FREE FIRST PROJECT</b><span>1 App + Website · AI modifications until ready · Preview · Quality checks · Publishing workflow</span><small>Mobile Game Creator is a Professional feature. Apple/Google developer fees and other third-party charges are paid directly to those providers. Existing license rules stay unchanged.</small></div></section>
    <section className="plans">
      <article><span>STANDARD</span><h2><b>${pricing.standard.priceUsd}</b> one time</h2><p>For later Standard creation access after the free first-project promotion or when otherwise applicable.</p><ul><li>Premium design quality</li><li>App + Website creation</li><li>No-code AI changes</li><li>Preview and publishing preparation</li><li>Project ownership preserved</li></ul><Link href="/create">Start Creating →</Link></article>
      <article className="pro"><span>PROFESSIONAL</span><h2><b>${pricing.professional.priceUsd}</b> / 12 months</h2><p>One payment for 365 days of Professional tools. No automatic renewal.</p><ul><li>Everything in Standard</li><li>Pro Mobile Game Creator · Fair Use</li><li>AI Copilot</li><li>Pro Design · Logic · Release</li><li>Database and workflow control</li><li>Publishing Assistant</li><li>Version history and advanced operations</li></ul><Link href="/game-builder">Open Pro Game Creator →</Link></article>
    </section>
    <section className="policy"><div><small>OUR PROMISE</small><h2>Fair use should feel generous for real customers.</h2></div><div className="grid"><p>✓ Useful included access comes first.</p><p>✓ We do not lower ordinary quality to force an upgrade.</p><p>✓ No hidden per-click billing.</p><p>✓ Extra paid usage, if ever offered, must show the price before confirmation.</p><p>✓ Projects and ownership remain with the customer after Pro access ends.</p><p>✓ Abuse safeguards protect reliability for everyone.</p></div></section>
    <section className="review"><h2>Price review policy</h2><p>Prices may be reviewed once every <b>{pricing.reviewPolicy.reviewIntervalYears} years</b>. A review does not mean prices must increase. If the current price remains fair and sustainable, it can stay unchanged.</p></section>
    <section className="stores"><h2>Apple & Google fees are not our fees.</h2><p>Developer-account and store charges are paid by the customer directly to Apple or Google. LANERIQ AI does not collect or mark up those platform fees.</p><div><a href={PRODUCT_POLICY.publishing.externalStoreFees.appleDeveloperProgram.officialEnrollmentUrl} target="_blank" rel="noreferrer">Apple Developer →</a><a href={PRODUCT_POLICY.publishing.externalStoreFees.googlePlayDeveloper.officialRegistrationUrl} target="_blank" rel="noreferrer">Google Play Console →</a></div></section>
  </div><style>{`.page{min-height:100vh;background:#04130f;color:#f5fff9;position:relative;padding-bottom:80px}.bg{position:fixed;inset:0;background:radial-gradient(circle at 72% 8%,#d9b84d2e,transparent 25%),linear-gradient(180deg,#02100dcc,#04130ff5),url('/soolen-ai-landscape.jpg') center/cover;z-index:0}.wrap{position:relative;z-index:1;width:min(1080px,calc(100% - 30px));margin:auto}header{display:flex;justify-content:space-between;padding:24px 0;font-size:11px;letter-spacing:.14em;font-weight:950}header a{color:#fff;text-decoration:none}.hero{padding:80px 0 40px}.hero small,.policy small,.plans article>span{color:#e5c767;letter-spacing:.18em;font-size:10px;font-weight:950}.hero h1{font-size:clamp(50px,9vw,92px);line-height:.94;letter-spacing:-.055em;margin:14px 0}.hero em{font-style:normal;color:#e5c767}.hero p{max-width:800px;color:#c0d0c9;line-height:1.7;font-size:18px}.promo{margin-top:22px;border:1px solid #e5c76755;background:linear-gradient(135deg,#e5c76718,#061813e8);border-radius:22px;padding:18px;display:grid;gap:7px}.promo b{color:#e5c767;font-size:13px;letter-spacing:.12em}.promo span{font-weight:850}.promo small{color:#9eb1a9;letter-spacing:0;font-size:12px;line-height:1.5}.plans{display:grid;grid-template-columns:1fr 1fr;gap:14px}.plans article,.policy,.review,.stores{border:1px solid #ffffff12;background:#061813e8;border-radius:25px;padding:26px}.plans article.pro{border-color:#d8bf6250;background:linear-gradient(145deg,#d8bf6212,#061813ea)}.plans h2{font-size:29px;margin:10px 0}.plans h2 b{font-size:48px;color:#e5c767}.plans p,.review p,.stores p{color:#9eb1a9;line-height:1.65}.plans ul{padding-left:18px;color:#d7e2dd;line-height:1.9}.plans a,.stores a{display:inline-flex;margin-top:12px;padding:13px 16px;border-radius:13px;background:#d8bf62;color:#07130e;text-decoration:none;font-weight:900}.policy,.review,.stores{margin-top:14px}.policy h2,.review h2,.stores h2{font-size:32px;margin:7px 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.grid p{margin:0;padding:13px;border-radius:13px;background:#0a241b;color:#c4d2cc}.stores>div{display:flex;gap:9px;flex-wrap:wrap}.stores a{background:transparent;color:#e5c767;border:1px solid #d8bf6235}@media(max-width:720px){.plans,.grid{grid-template-columns:1fr}.hero{padding-top:55px}}`}</style></main>;
}
