export const LANERIQ_COMMUNICATIONS_SERVICE_POLICY = Object.freeze({
  name:"LANERIQ Zero-Cost OmniChannel Communication",
  version:"2026-09-omnichannel-v1",
  launchYearMonths:12,
  customerPlatformFee:0,
  currency:"MYR",
  defaultMode:"zero",
  externalSpendCap:0,
  channels:Object.freeze(["in_app","push","email","telegram","line","wechat","whatsapp","sms"]),
  channelPriority:Object.freeze(["in_app","push","email","telegram","line","wechat","whatsapp","sms"]),
  omnichannelRouterEnabled:true,
  paidSmsEnabled:false,
  paidSmsFallback:false,
  paidWhatsAppAutoSelect:false,
  meteredProvidersAllowedInZeroMode:false,
  unknownCostProvidersAllowedInZeroMode:false,
  freeQuotaOverageAllowed:false,
  customerBilledProviderAutoSelect:false,
  providerFallbackAcrossChannels:true,
  fallbackRequiresZeroCostEligibility:true,
  hiddenProviderFees:false,
  passThroughProviderFees:false,
  autoChargeCustomer:false,
  providerCostAbsorbedByLaneriqDuringLaunchYear:true,
  fairUse:true,
  abuseProtection:true,
  budgetProtection:true,
  idempotencyRequired:true,
  persistentRateLimits:true,
  recipientStoredAsHashOnly:true,
  messageBodyStored:false,
  providerOpaqueToGeneratedApps:true,
  storeAdapterReplaceable:true,
  deliveryAdapterReplaceable:true,
  providerAdapterContractRequired:true,
  costMetadataRequiredBeforeZeroModeSend:true,
  quotaMetadataRequiredForFreeQuotaRoutes:true,
  overBudgetBehavior:"pause_or_use_available_free_route",
  billingFailureBehavior:"never_auto_charge_customer",
  evidencePolicy:Object.freeze({
    adapterContract:"CODE",
    configuredProvider:"PROVIDER_READY",
    successfulExternalDelivery:"LIVE",
    physicalPhoneReceipt:"DEVICE_VERIFIED",
  }),
});

export function communicationServicePolicy(){
  return LANERIQ_COMMUNICATIONS_SERVICE_POLICY;
}
