// Platform isolation driver contract. Every execution occurs in a fresh external container/microVM.
const REQUIRED=["createJob","putFiles","runBuild","runBrowserTests","destroyJob"],MAX_FILES=500,MAX_FILE_BYTES=250000,MAX_TOTAL_BYTES=5000000;
export function validateIsolationProvider(provider){const missing=REQUIRED.filter(k=>typeof provider?.[k]!=="function");return {passed:missing.length===0,missing};}
function bytes(s){return new TextEncoder().encode(String(s||"")).length;}function clamp(v,d,min,max){const n=Number(v);return Number.isFinite(n)?Math.max(min,Math.min(n,max)):d;}
function filesFrom(spec={}){const input=Array.isArray(spec.sourceFiles)?spec.sourceFiles:Array.isArray(spec.files)?spec.files:[];if(!input.length)throw new Error("SOURCE_FILES_REQUIRED");if(input.length>MAX_FILES)throw new Error("TOO_MANY_SOURCE_FILES");let total=0;const seen=new Set(),files=[];for(const f of input){const path=String(f?.path||"");const content=String(f?.content||"");if(!path||path.length>500||path.startsWith("/")||path.includes("\\")||path.split("/").some(x=>!x||x==="."||x===".."))throw new Error("UNSAFE_SOURCE_PATH");if(seen.has(path))throw new Error("DUPLICATE_SOURCE_PATH");seen.add(path);const size=bytes(content);if(size>MAX_FILE_BYTES)throw new Error("SOURCE_FILE_TOO_LARGE");total+=size;if(total>MAX_TOTAL_BYTES)throw new Error("SOURCE_TOTAL_TOO_LARGE");files.push({path,content});}return files;}
function limits(policy={}){return {network:"deny",nonRoot:true,readOnlyRoot:true,noHostMounts:true,noDockerSocket:true,noSecrets:true,memoryMB:clamp(policy.maxMemoryMB,768,128,1024),cpu:clamp(policy.maxCpu,2,0.25,2),pids:clamp(policy.maxPids,128,16,128),diskMB:1024,outputBytes:2_000_000};}
function validResult(r,kind){if(!r||typeof r!=="object")return {passed:false,status:`invalid-${kind}-result`,errors:[`${kind}-result-not-object`]};if(r.passed!==true&&r.passed!==false&&r.passed!==null)return {passed:false,status:`invalid-${kind}-result`,errors:[`${kind}-passed-invalid`]};if(typeof r.status!=="string"||!r.status)return {passed:false,status:`invalid-${kind}-result`,errors:[`${kind}-status-missing`]};return r;}
export function createPlatformIsolationDriver(provider){const valid=validateIsolationProvider(provider);async function job(request,kind){if(!valid.passed)return {passed:null,status:"isolation-provider-not-connected",errors:valid.missing.map(x=>`missing-provider:${x}`)};let id;try{const files=filesFrom(request.specification),resourceLimits=limits(request.policy);id=await provider.createJob({workspaceId:request.workspaceId,limits:resourceLimits,ttlMs:clamp(request.policy?.jobTtlMs,180000,30000,300000)});if(!id)throw new Error("ISOLATION_JOB_NOT_CREATED");const uploaded=await provider.putFiles(id,files);if(uploaded?.passed===false)throw new Error("SOURCE_UPLOAD_FAILED");let result;if(kind==="build")result=await provider.runBuild(id,{commands:["install","build"],timeoutMs:clamp(request.policy?.maxBuildMs,120000,1000,120000)});else result=await provider.runBrowserTests(id,{plan:request.plan||{},timeoutMs:clamp(request.policy?.maxTestMs,60000,1000,60000),externalNetwork:false,buildBeforeTest:true});return validResult(result,kind);}catch(e){const code=String(e?.message||`${kind}-failed`).replace(/[^A-Z0-9:_-]/gi,"-").slice(0,160);return {passed:false,status:`isolated-${kind}-failed`,errors:[code]};}finally{if(id)await provider.destroyJob(id).catch(()=>{});}}
return {build:r=>job(r,"build"),test:r=>job(r,"test")};}
}
