// Soolen Executor Backend control plane. Generated code executes only in an external isolated job.
import http from "node:http";import crypto from "node:crypto";import {createPlatformIsolationDriver} from "./platform-driver.js";import {createHttpIsolationProvider,isolationProviderConfigured} from "./provider-http.js";
const PORT=Number(process.env.PORT||8790),TOKEN=String(process.env.SOOLEN_EXECUTOR_BACKEND_TOKEN||""),MAX_BODY=2_000_000,MAX_CONCURRENT=20;const provider=createHttpIsolationProvider(),driver=createPlatformIsolationDriver(provider);let active=0;
function bytes(s){return Buffer.byteLength(String(s||""),"utf8");}function send(res,status,data){const out=JSON.stringify(data);res.writeHead(status,{"content-type":"application/json","cache-control":"no-store","x-content-type-options":"nosniff","content-security-policy":"default-src 'none'"});res.end(bytes(out)>MAX_BODY?JSON.stringify({passed:false,status:"response-too-large",errors:["Executor output exceeded limit"]}):out);}
function auth(req){if(!TOKEN)return false;const got=String(req.headers.authorization||"").replace(/^Bearer\s+/i,"");const a=Buffer.from(got),b=Buffer.from(TOKEN);return a.length===b.length&&crypto.timingSafeEqual(a,b);}async function body(req){if(!String(req.headers["content-type"]||"").toLowerCase().startsWith("application/json"))throw new Error("CONTENT_TYPE_REQUIRED");let raw="",size=0;for await(const c of req){size+=Buffer.byteLength(c);if(size>MAX_BODY)throw new Error("BODY_TOO_LARGE");raw+=c;}try{return JSON.parse(raw||"{}");}catch{throw new Error("INVALID_JSON");}}
function clamp(v,d,min,max){const n=Number(v);return Number.isFinite(n)?Math.max(min,Math.min(n,max)):d;}function safePolicy(p={}){return {network:"deny",secrets:"none",readOnlyRoot:true,nonRoot:true,noHostMounts:true,noDockerSocket:true,maxBuildMs:clamp(p.maxBuildMs,120000,1000,120000),maxTestMs:clamp(p.maxTestMs,60000,1000,60000),maxMemoryMB:clamp(p.maxMemoryMB,768,128,1024),maxCpu:clamp(p.maxCpu,2,0.25,2),maxPids:clamp(p.maxPids,128,16,128),jobTtlMs:clamp(p.jobTtlMs,180000,30000,300000)};}
function validate(kind,b){const errors=[];if(!b||typeof b!=="object"||Array.isArray(b))errors.push("REQUEST_OBJECT_REQUIRED");if(typeof b?.workspaceId!=="string"||!b.workspaceId||b.workspaceId.length>100)errors.push("WORKSPACE_ID_INVALID");if(!b?.specification||typeof b.specification!=="object"||Array.isArray(b.specification))errors.push("SPECIFICATION_INVALID");if(kind==="test"&&(!b?.plan||!Array.isArray(b.plan.checks)||!b.plan.checks.length))errors.push("RUNTIME_PLAN_INVALID");return errors;}
async function execute(kind,b){const errors=validate(kind,b);if(errors.length)return {http:400,data:{passed:false,status:"invalid-request",errors}};if(!provider)return {http:503,data:{passed:null,status:"isolation-provider-not-configured",errors:["Configure SOOLEN_ISOLATION_PROVIDER_URL before executing generated code"]}};if(active>=MAX_CONCURRENT)return {http:429,data:{passed:false,status:"executor-busy",errors:["Concurrent isolated job limit reached"]}};active++;try{const request={workspaceId:b.workspaceId,specification:b.specification,plan:b.plan||{},policy:safePolicy(b.policy)};return {http:200,data:await driver[kind](request)};}finally{active--;}}
http.createServer(async(req,res)=>{try{if(req.method==="GET"&&req.url==="/health")return send(res,200,{status:"ok",providerConfigured:isolationProviderConfigured(),active,maxConcurrent:MAX_CONCURRENT});if(!auth(req))return send(res,401,{error:"UNAUTHORIZED"});if(req.method!=="POST")return send(res,405,{error:"POST_ONLY"});const b=await body(req);if(req.url==="/v1/build"||req.url==="/v1/test"){const kind=req.url.endsWith("build")?"build":"test",result=await execute(kind,b);return send(res,result.http,result.data);}return send(res,404,{error:"NOT_FOUND"});}catch(e){const code=String(e?.message||"EXECUTOR_ERROR"),status=code==="BODY_TOO_LARGE"?413:["INVALID_JSON","CONTENT_TYPE_REQUIRED"].includes(code)?400:500;return send(res,status,{error:["BODY_TOO_LARGE","INVALID_JSON","CONTENT_TYPE_REQUIRED"].includes(code)?code:"EXECUTOR_ERROR"});}}).listen(PORT,()=>console.log(`Soolen Executor Backend listening on ${PORT}`));
