"use client";

import Link from "next/link";
import {useMemo,useState} from "react";
import {
  createBossCombatRuntime,stepBossCombat,validateBehaviorTree,tickBehaviorTree,createTalentState,unlockTalent,
  rollItemAffixes,rollLootTable,validateDialogueGraph,dialogueChoices,createWorldTimeWeather,stepWorldTimeWeather,worldLightingState,
  generateDungeon,createDestructible,damageDestructible,validateCutsceneTimeline,cutsceneStateAt,createCameraDirector,directCamera,
  validateUgcSceneDocument
} from "../../lib/game/advanced-3d-gameplay-systems-v1.js";

const TABS=["Boss","AI Tree","Talent & Loot","Dialogue","World","Dungeon","Cutscene","UGC Scene"];

export default function Advanced3dGameLab(){
  const[tab,setTab]=useState("Boss");
  return <main className="shell"><div className="bg"/><header><Link href="/game-builder">← GAME BUILDER</Link><span>SOOLENAI · ADVANCED 3D GAME LAB</span></header>
    <section className="hero"><small>PRO · ADVANCED 3D GAMEPLAY SYSTEMS</small><h1>Design the systems<br/><em>behind bigger games.</em></h1><p>Boss phases, behavior trees, talents, deterministic loot, dialogue graphs, day/night weather, dungeon generation, destructible environments, cutscene camera direction and safe UGC scene validation are executable local contracts. Renderer quality and live backend evidence remain separate.</p></section>
    <nav>{TABS.map(item=><button key={item} className={tab===item?"active":""} onClick={()=>setTab(item)}>{item}</button>)}</nav>
    <section className="panel">{tab==="Boss"?<BossLab/>:tab==="AI Tree"?<AiLab/>:tab==="Talent & Loot"?<TalentLootLab/>:tab==="Dialogue"?<DialogueLab/>:tab==="World"?<WorldLab/>:tab==="Dungeon"?<DungeonLab/>:tab==="Cutscene"?<CutsceneLab/>:<UgcSceneLab/>}</section>
    <section className="truth"><b>Evidence boundary</b><span>These tools prove deterministic gameplay-system behavior. They do not claim final 3D art/animation quality, production renderer performance, live persistence, public UGC moderation, platform trophies or real-device certification without external evidence.</span></section>
    <style jsx>{`.shell{min-height:100vh;background:#020705;color:#effaf5;font-family:Inter,system-ui;padding-bottom:70px}.bg{position:fixed;inset:0;background:radial-gradient(circle at 78% 12%,#d8bf6224,transparent 30%),linear-gradient(180deg,#020705e9,#020705fb),url('/soolen-ai-landscape.jpg') center/cover;z-index:0}header,.hero,nav,.panel,.truth{position:relative;z-index:1;width:min(1100px,calc(100% - 28px));margin:auto}header{display:flex;justify-content:space-between;padding:24px 0;font-size:10px;letter-spacing:.13em;font-weight:950}header a{color:#fff;text-decoration:none}header span,.hero small{color:#e2c566}.hero{padding:58px 0 24px}.hero h1{font-size:clamp(48px,8vw,88px);line-height:.94;letter-spacing:-.05em;margin:10px 0}.hero em{font-style:normal;color:#e2c566}.hero p{max-width:900px;color:#aabcb4;line-height:1.7}nav{display:flex;gap:7px;flex-wrap:wrap;margin-bottom:12px}nav button{border:1px solid #ffffff12;background:#071811;color:#9fb1a9;padding:9px 12px;border-radius:999px;font-weight:850;font-size:10px}nav button.active{background:#e2c566;color:#07110d}.panel,.truth{border:1px solid #ffffff12;background:#061813e9;border-radius:24px;padding:22px;backdrop-filter:blur(16px)}.truth{margin-top:12px;display:grid;gap:5px}.truth b{color:#e2c566}.truth span{color:#8fa199;font-size:11px;line-height:1.5}:global(.labGrid){display:grid;grid-template-columns:1fr 1fr;gap:12px}:global(.card){border:1px solid #ffffff10;background:#091f17;border-radius:18px;padding:16px}:global(.card h2){margin:0 0 8px;font-size:22px}:global(.card p),:global(.card li){color:#9cafa6;font-size:11px;line-height:1.55}:global(.row){display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}:global(button.action){border:0;border-radius:12px;background:#d9bf61;color:#07110d;padding:10px 12px;font-weight:900}:global(button.secondary){border:1px solid #ffffff12;border-radius:12px;background:#0a2119;color:#d7e5de;padding:10px 12px;font-weight:800}:global(input.field),:global(textarea.field){width:100%;box-sizing:border-box;border:1px solid #ffffff12;border-radius:12px;background:#020a08;color:#fff;padding:11px;margin-top:8px}:global(.metric){font-size:30px;font-weight:950;color:#e2c566}:global(.mono){font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:10px;white-space:pre-wrap;color:#a9bbb2;background:#020a08;border-radius:12px;padding:10px;max-height:280px;overflow:auto}@media(max-width:720px){:global(.labGrid){grid-template-columns:1fr}.hero{padding-top:42px}}`}</style>
  </main>;
}

function BossLab(){const[state,setState]=useState(()=>createBossCombatRuntime({maxHealth:2400}));function hit(damage,interrupt=false){setState(s=>stepBossCombat(s,{damage,interrupt},.1));}return <div className="labGrid"><div className="card"><h2>3D Boss Combat Runtime</h2><div className="metric">Phase {state.phase}</div><p>HP {state.health}/{state.maxHealth} · telegraph {state.telegraph||"none"}</p><div className="row"><button className="action" onClick={()=>hit(220)}>Attack</button><button className="secondary" onClick={()=>hit(70,true)}>Interrupt</button><button className="secondary" onClick={()=>setState(createBossCombatRuntime({maxHealth:2400}))}>Restart</button></div></div><div className="card"><h2>Runtime State</h2><div className="mono">{JSON.stringify(state,null,2)}</div></div></div>}

function AiLab(){const tree={root:"root",nodes:[{id:"root",type:"selector",children:["attack","patrol"]},{id:"attack",type:"sequence",children:["near","strike"]},{id:"near",type:"condition"},{id:"strike",type:"action"},{id:"patrol",type:"action"}]};const[near,setNear]=useState(false);const checked=validateBehaviorTree(tree),tick=tickBehaviorTree(tree,{near},{condition:(n,c)=>n.id==="near"&&c.near,action:n=>n.id==="strike"?"success":"success"});return <div className="labGrid"><div className="card"><h2>Behavior Tree</h2><p>Selector → attack sequence when target is near, otherwise patrol.</p><button className="action" onClick={()=>setNear(v=>!v)}>Target {near?"Near":"Far"}</button><div className="mono">{JSON.stringify(checked,null,2)}</div></div><div className="card"><h2>Tick Trace</h2><div className="metric">{tick.status}</div><div className="mono">{JSON.stringify(tick,null,2)}</div></div></div>}

function TalentLootLab(){const tree=[{id:"power",cost:1,requires:[]},{id:"meteor",cost:2,requires:["power"]}];const[talent,setTalent]=useState(()=>createTalentState(3));const[seed,setSeed]=useState("hero-001");function unlock(id){const result=unlockTalent(talent,tree,id);if(result.ok)setTalent(result.state);}const affixes=useMemo(()=>rollItemAffixes({seed,rarity:"epic"}),[seed]),loot=useMemo(()=>rollLootTable([{id:"gold",weight:70,min:10,max:30},{id:"gem",weight:25,min:1,max:3},{id:"legendary_core",weight:5,min:1,max:1}],{seed,rolls:3}),[seed]);return <div className="labGrid"><div className="card"><h2>Talent Tree</h2><p>Points {talent.points} · unlocked {[...talent.unlocked].join(", ")||"none"}</p><div className="row"><button className="action" onClick={()=>unlock("power")}>Unlock Power</button><button className="secondary" onClick={()=>unlock("meteor")}>Unlock Meteor</button></div></div><div className="card"><h2>Loot + Random Affixes</h2><input className="field" value={seed} onChange={e=>setSeed(e.target.value)}/><div className="mono">{JSON.stringify({affixes,loot},null,2)}</div></div></div>}

function DialogueLab(){const graph=[{id:"start",text:"Will you help?",choices:[{label:"Yes",next:"quest"},{label:"Ask about reward",next:"reward",condition:"trusted"}]},{id:"quest",text:"Then begin.",terminal:true,choices:[]},{id:"reward",text:"A rare relic awaits.",terminal:true,choices:[]}];const[trusted,setTrusted]=useState(false),checked=validateDialogueGraph(graph),choices=dialogueChoices(graph,"start",{trusted});return <div className="labGrid"><div className="card"><h2>Dialogue Graph</h2><button className="action" onClick={()=>setTrusted(v=>!v)}>Trusted: {String(trusted)}</button><ul>{choices.map(c=><li key={c.label}>{c.label} → {c.next}</li>)}</ul></div><div className="card"><h2>Validation</h2><div className="mono">{JSON.stringify(checked,null,2)}</div></div></div>}

function WorldLab(){const[state,setState]=useState(()=>createWorldTimeWeather({hour:17,weather:"clear"}));const light=worldLightingState(state);return <div className="labGrid"><div className="card"><h2>Day / Night & Weather</h2><div className="metric">Day {state.day} · {state.hour.toFixed(1)}h</div><p>{state.weather} · visibility {state.visibility} · wind {state.wind}</p><div className="row"><button className="action" onClick={()=>setState(s=>stepWorldTimeWeather(s,{dtSeconds:10,timeScale:600}))}>Advance Time</button><button className="secondary" onClick={()=>setState(s=>stepWorldTimeWeather(s,{nextWeather:"storm"}))}>Transition Storm</button></div></div><div className="card"><h2>Gameplay Lighting State</h2><div className="mono">{JSON.stringify(light,null,2)}</div></div></div>}

function DungeonLab(){const[seed,setSeed]=useState("dungeon-001"),dungeon=useMemo(()=>generateDungeon({seed,width:11,height:11,rooms:16}),[seed]);const[wall,setWall]=useState(()=>createDestructible({id:"wall",maxHealth:180,persistenceKey:"d1-wall"}));return <div className="labGrid"><div className="card"><h2>Seeded Dungeon</h2><input className="field" value={seed} onChange={e=>setSeed(e.target.value)}/><p>{dungeon.cells.length} connected cells · checksum {dungeon.checksum}</p><div className="mono">{dungeon.grid.map(row=>row.map(v=>v?"██":"··").join(" ")).join("\n")}</div></div><div className="card"><h2>Destructible Environment</h2><div className="metric">{wall.state}</div><p>HP {wall.health}/{wall.maxHealth} · fragments {wall.fragments}</p><button className="action" onClick={()=>setWall(s=>damageDestructible(s,70))}>Damage Wall</button></div></div>}

function CutsceneLab(){const shots=[{id:"intro",start:0,duration:2,camera:"wide",reducedMotionCamera:"static-wide"},{id:"boss",start:2,duration:2,camera:"boss-close",lockGameplay:true},{id:"player",start:4,duration:1.5,camera:"hero-orbit",skippable:true}],checked=validateCutsceneTimeline(shots);const[time,setTime]=useState(0),[camera,setCamera]=useState(()=>createCameraDirector());const view=cutsceneStateAt(shots,time,{reducedMotion:false});function advance(){const next=Math.min(6,time+1);setTime(next);if(view.active)setCamera(c=>directCamera(c,{mode:"cinematic",targetId:view.active.id,priority:10,blend:.4,shake:.15}));}return <div className="labGrid"><div className="card"><h2>Cutscene Timeline</h2><div className="metric">{time.toFixed(1)}s</div><button className="action" onClick={advance}>Advance 1s</button><div className="mono">{JSON.stringify({checked,view},null,2)}</div></div><div className="card"><h2>Camera Director</h2><div className="mono">{JSON.stringify(camera,null,2)}</div></div></div>}

function UgcSceneLab(){const[name,setName]=useState("Ancient Ruins"),[count,setCount]=useState(6);const scene={name,entities:Array.from({length:Math.max(0,count)},(_,i)=>({id:`entity-${i}`,type:i===0?"spawn":"prop",assets:[`asset-${i}`]}))},result=validateUgcSceneDocument(scene);return <div className="labGrid"><div className="card"><h2>UGC Scene Editor Contract</h2><label>Name<input className="field" value={name} onChange={e=>setName(e.target.value)}/></label><label>Entities<input className="field" type="number" min="0" max="1100" value={count} onChange={e=>setCount(Number(e.target.value))}/></label><p>No executable scripts or arbitrary external assets are allowed in the scene document.</p></div><div className="card"><h2>Scene Validation</h2><div className="mono">{JSON.stringify(result,null,2)}</div></div></div>}
